SELECT
	MAX(A.LOAD_DATE)
FROM
	DESA_CLIENTES.JL.TMP_STG_OUTPUT_DIGITAL_FILE_CUSTOMER_OFFER_SYD A
;--'2022-07-01 12:32:02'
/*****
DESA_CLIENTES.RU.TMP_STG_OUTPUT_DIGITAL_FILE_CUSTOMER_OFFER A
DELETE
FROM
	DESA_CLIENTES.RU.TMP_STG_OUTPUT_DIGITAL_FILE_CUSTOMER_OFFER_TB_ALVI A
WHERE
	A.LOAD_DATE = '2022-02-24 17:02:52'
*/
SELECT 
	COUNT(DISTINCT A.OFFER_ID)
	, COUNT(*)
FROM
	DESA_CLIENTES.JL.TMP_ALLOCATION_FILE_SYD_ALVI A--272
;--5	2630
SELECT
	COUNT(DISTINCT A.ID_OFERTA)
	, COUNT(*)
FROM
	DESA_CLIENTES.JL.TMP_STG_OUTPUT_DIGITAL_FILE_CUSTOMER_OFFER_SYD A
WHERE
	A.LOAD_DATE ='2022-07-01 12:32:02'
;--5	2630
/***********************************************************/

SELECT
	COUNT(DISTINCT A.OFFER_ID)
FROM
	DESA_CLIENTES.JL.APP_ALVI_JOURNEYDOWN A
WHERE
	A.CYCLE = 2
--5
;

/***********************************************************/
SELECT
	*
FROM
	DESA_CLIENTES.JL.TMP_STG_OUTPUT_DIGITAL_FILE_OFFER_SYD A
;--5

SELECT
	COUNT(DISTINCT A.ID_OFERTA)
FROM
	DESA_CLIENTES.JL.TMP_STG_OUTPUT_DIGITAL_FILE_CUSTOMER_OFFER_SYD A
WHERE
	A.LOAD_DATE = '2022-07-01 12:32:02'
;--5

SELECT
	COUNT(*)
FROM
	DESA_CLIENTES.JL.TMP_STG_OUTPUT_DIGITAL_FILE_CUSTOMER_OFFER_SYD B
WHERE
	B.LOAD_DATE ='2022-07-01 12:32:02'
;--2630 --CARGA A MONGO

/***
UPDATE
	DESA_CLIENTES.RU.TMP_STG_OUTPUT_DIGITAL_FILE_CUSTOMER_OFFER_TB
SET
	FECHA_INICIO_CICLO = '2021-03-11 09:13:19'
WHERE
	LOAD_DATE = '2021-03-11 09:13:19'
;
/**************EXPORT ARCHIVO OFERTA***********************/
SELECT
	--A.NOMBRE_ARCHIVO,
	A.ID_FORMATO	
	, A.ID_APLICA_OFERTA	
	, A.ID_OFERTA	
	, A.ID_PERIODO	
	, A.FECHA_INICIO_PERIODO	
	, A.FECHA_FIN_PERIODO	
	, A.MAX_USO	
	, A.MAX_UNIDADES_X_USO::INTEGER AS 	MAX_UNIDADES_X_USO
	, A.UNIDAD_MEDIDA	
	, A.DESCRIPCION_OFERTA	
	, A.ID_MECANICA	
	, A.CONTENIDO_MECANICA	
	, A.LEGAL	
	, A.CANAL	
	, A.ID_CATALOGO	
	, A.DESCRIPCION_TIPO	
	, A.ORDEN_DCTO	
	, A.UNICARD_DCTO
FROM
	DESA_CLIENTES.JL.TMP_STG_OUTPUT_DIGITAL_FILE_OFFER_SYD A
;