SELECT
	--DISTINCT A.LOAD_DATE
	MAX(A.LOAD_DATE)
FROM
	DESA_CLIENTES.RU.TMP_STG_OUTPUT_DIGITAL_FILE_CUSTOMER_OFFER A
WHERE
	A.LOAD_DATE = '2022-07-18 16:59:10'
;--'2022-05-02 10:45:35' 

SELECT 
	COUNT(*)
	, COUNT(DISTINCT A.OFFER_ID)
FROM
	DESA_CLIENTES.RU.APP_ALVI_TMP_ALLOCATION_FILE_OP A
;--805193	116


SELECT
	COUNT(DISTINCT A.ID_OFERTA)
	, COUNT(*)
FROM
	DESA_CLIENTES.RU.TMP_STG_OUTPUT_DIGITAL_FILE_CUSTOMER_OFFER A
WHERE
	A.TIPO_OFERTA = 2
	AND A.LOAD_DATE = '2022-07-18 16:59:10'
;--116	805193

SELECT
	COUNT(DISTINCT A.ID_OFERTA)
	, COUNT(*)
FROM
	NZ_CLIENTES.STG.STG_OUTPUT_DIGITAL_FILE_CUSTOMER_OFFER A
WHERE
	A.TIPO_OFERTA = 2
;--116	805193
/************************************************************/

SELECT
	COUNT(DISTINCT A.HASH_RUT)
FROM
	DESA_CLIENTES.RU.TMP_STG_OUTPUT_DIGITAL_FILE_CUSTOMER_OFFER A
WHERE
	A.LOAD_DATE = '2022-07-18 16:59:10'
	AND A.TIPO_OFERTA = 2
;--145843

SELECT
	COUNT(*)
FROM
	DESA_CLIENTES.RU.TMP_STG_OUTPUT_DIGITAL_FILE_CUSTOMER_OFFER A
WHERE
	A.LOAD_DATE ='2022-07-18 16:59:10'
;--2450908

SELECT
	COUNT(1)
FROM
	DESA_CLIENTES.RU.TMP_STG_OUTPUT_DIGITAL_FILE_CUSTOMER A--REVISAR
;--145843

SELECT
	COUNT(*)
FROM
	DESA_CLIENTES.RU.APP_ALVI_TMP_CUSTOMER_SCORE_FILE C
;--168598

/***********************************************************/
SELECT
	COUNT(*)
	, COUNT(DISTINCT A.OFFER_ID)
FROM
	DESA_CLIENTES.RU.APP_ALVI_TMP_ALLOCATION_FILE_PC A
;--1645678	112

SELECT
	COUNT(DISTINCT A.ID_OFERTA)
	, COUNT(*)
FROM
	DESA_CLIENTES.RU.TMP_STG_OUTPUT_DIGITAL_FILE_CUSTOMER_OFFER A
WHERE
	A.TIPO_OFERTA = 6
	AND A.LOAD_DATE = '2022-07-18 16:59:10'
;--112	1645678

SELECT
	COUNT(DISTINCT A.ID_OFERTA)
	, COUNT(*)
FROM
	NZ_CLIENTES.STG.STG_OUTPUT_DIGITAL_FILE_CUSTOMER_OFFER A
WHERE
	A.TIPO_OFERTA = 6
;--112	1645678

SELECT
	*
FROM
	DESA_CLIENTES.RU.TMP_STG_OUTPUT_DIGITAL_FILE_CUSTOMER_OFFER A
WHERE
	A.TIPO_OFERTA = 4 --MASIVA
	AND A.LOAD_DATE = '2022-07-18 16:59:10'
;--28

SELECT
	COUNT(DISTINCT A.ID_OFERTA)
FROM
	DESA_CLIENTES.RU.TMP_STG_OUTPUT_DIGITAL_FILE_CUSTOMER_OFFER A
WHERE
	A.TIPO_OFERTA = 9 --KIOSCO
	AND A.LOAD_DATE = '2022-07-18 16:59:10'
;--9

SELECT
	COUNT(DISTINCT A.ID_OFERTA)
FROM
	NZ_CLIENTES.STG.STG_OUTPUT_DIGITAL_FILE_CUSTOMER_OFFER A
WHERE
	A.TIPO_OFERTA = 4
;--28

SELECT
	COUNT(DISTINCT A.ID_OFERTA)
FROM
	NZ_CLIENTES.STG.STG_OUTPUT_DIGITAL_FILE_CUSTOMER_OFFER A
WHERE
	A.TIPO_OFERTA = 9
;--9

SELECT
	COUNT(DISTINCT A.ID_OFERTA)
	, COUNT(*)
FROM
	NZ_CLIENTES.STG.STG_OUTPUT_DIGITAL_FILE_CUSTOMER_OFFER A
;--153	2450908--carga a mongo

--2750279


SELECT COUNT(DISTINCT P.OFFER_ID) FROM--SELECT * FROM
	DESA_CLIENTES.NS.APP_ALVI_OFERTAS P
WHERE
	P.CYCLE = 9
;--137

/***********************************************************/
SELECT
	COUNT(DISTINCT A.HASH_RUT)
FROM
	DESA_CLIENTES.RU.TMP_STG_OUTPUT_DIGITAL_FILE_CUSTOMER A
;--145843
SELECT
	COUNT(DISTINCT A.HASH_RUT)
FROM
	NZ_CLIENTES.STG.STG_OUTPUT_DIGITAL_FILE_CUSTOMER_OFFER A--139908
WHERE
	A.TIPO_OFERTA = 2
;--145843
SELECT
	COUNT(DISTINCT A.HASH_RUT)
FROM
	NZ_CLIENTES.STG.STG_OUTPUT_DIGITAL_FILE_CUSTOMER_OFFER A--162884
WHERE
	A.TIPO_OFERTA IN (2,6)--179477
;

SELECT
	COUNT(DISTINCT A.ID_OFERTA)
FROM
	DESA_CLIENTES.RU.TMP_STG_OUTPUT_DIGITAL_FILE_CUSTOMER_OFFER A--169537
WHERE
	A.LOAD_DATE = '2022-07-18 16:59:10'
;--153

SELECT
	COUNT(DISTINCT A.OFFER_ID)
FROM
	DESA_CLIENTES.NS.APP_ALVI_OFERTAS A
WHERE
	A.CYCLE = 9
	AND A.TIPO_OFERTA LIKE 'Personalizada%'
;--113

/**************EXPORT ARCHIVO OFERTA***********************/
SELECT
	--A.NOMBRE_ARCHIVO,
	A.ID_FORMATO	
	, A.ID_APLICA_OFERTA	
	, A.ID_OFERTA	
	, A.ID_PERIODO	
	, A.FECHA_INICIO_PERIODO	
	, A.FECHA_FIN_PERIODO	
	--, '2022-07-19 23:59:59'
	, A.MAX_USO	
	, A.MAX_UNIDADES_X_USO	
	, A.UNIDAD_MEDIDA	
	, A.DESCRIPCION_OFERTA	
	, A.ID_MECANICA	
	, A.CONTENIDO_MECANICA	
	, A.LEGAL	
	, A.CANAL	
	, A.ID_CATALOGO	
	, A.DESCRIPCION_TIPO	
	, A.ORDEN_DCTO	
	, A.UNICARD_DCTO
	, 'NO' AS HASDEPTH
    , '' AS OFFER_LEVEL
    , '' AS UNITPRICE
    , '' AS DEPTHMECANICAID
    , '' AS DEPTHMECANICA
	, 'FALSE' AS UNIPAY
	, CASE WHEN A.CHANNEL = 'ALL' THEN ''
	ELSE '' END AS CHANNEL
FROM
	DESA_CLIENTES.RU.TMP_STG_OUTPUT_DIGITAL_FILE_OFFER A
;