SELECT
	MAX(A.LOAD_DATE)
FROM-- select distinct LOAD_DATE from 
	DESA_CLIENTES.JL.TMP_STG_OUTPUT_DIGITAL_FILE_CUSTOMER_OFFER_MAIPU_m10 A
;--'2022-07-15 13:51:56'

SELECT 
	COUNT(DISTINCT A.OFFER_ID)
	, COUNT(*)
FROM
	DESA_CLIENTES.CT.TMP_MAIPU_APP_M10_TMP_ALLOCATION_FILE_NEW A--272
;--8	487018

/***********************************************************/

SELECT
	COUNT(DISTINCT A.OFFER_ID)
FROM--  select * from 
	DESA_CLIENTES.ct.APP_M10_TOTAL_BOLETA_OFERTAS A
WHERE
	A.CYCLE = $CICLO
--8
;

SELECT
	*
FROM
	NZ_CLIENTES.STG.TMP_STG_OUTPUT_DIGITAL_FILE_OFFER_MAIPU_ALVI A
WHERE
	A.ID_OFERTA IN (1536, 285);
/***********************************************************/
SELECT
	*
FROM
	DESA_CLIENTES.JL.TMP_STG_OUTPUT_DIGITAL_FILE_OFFER_MAIPU_M10 A
;--8             
SELECT
	*
FROM
	NZ_CLIENTES.STG.STG_OUTPUT_DIGITAL_FILE_OFFER A
;--261

SELECT
COUNT(1)
FROM
	DESA_CLIENTES.JL.TMP_STG_OUTPUT_DIGITAL_FILE_CUSTOMER_OFFER_MAIPU_M10 A
WHERE
	A.LOAD_DATE ='2022-07-12 13:20:03'
;--462765


SELECT
	--A.NOMBRE_ARCHIVO,
	--REGION CAMPOS
	A.ID_FORMATO	
	, A.ID_APLICA_OFERTA	
	, A.ID_OFERTA	
	, A.ID_PERIODO	
	, A.FECHA_INICIO_PERIODO	
	, A.FECHA_FIN_PERIODO	
	, A.MAX_USO	
	, A.MAX_UNIDADES_X_USO::INTEGER AS 	MAX_UNIDADES_X_USO
	, A.UNIDAD_MEDIDA	
	, A.DESCRIPCION_OFERTA	
	, A.ID_MECANICA	
	, A.CONTENIDO_MECANICA	
	, A.LEGAL	
	, A.CANAL	
	, A.ID_CATALOGO	
	, A.DESCRIPCION_TIPO	
	, A.ORDEN_DCTO	
	, A.UNICARD_DCTO
	, 'FALSE' AS UNIPAY
	, 'ONLY_STORE' AS CHANNEL
	--END REGION
FROM
	DESA_CLIENTES.JL.TMP_STG_OUTPUT_DIGITAL_FILE_OFFER_MAIPU_m10 A
	'OFERTA_220420_220712_2_4.csv'
;