/***********************************
REVISAR RANKING Y 
OFFER ID DUPLICADOS
************************************/

SELECT
	A.CUSTOMER_ID
	, A.OFFER_ID
	, COUNT(*)
FROM
	DESA_CLIENTES.CT.TMP_TB_APP_M10_TMP_ALLOCATION_FILE_NEW A--43732583
GROUP BY 1,2
HAVING COUNT > 1
;

SELECT
	A.CUSTOMER_ID
	--, A.OFFER_RANK
	, COUNT(*)
FROM
	DESA_CLIENTES.CT.TMP_TB_APP_M10_TMP_ALLOCATION_FILE_NEW A
GROUP BY 1
HAVING COUNT > 1
;

/************************************************************/

SELECT
	COUNT(*)
FROM
	DESA_CLIENTES.CT.TMP_TB_APP_M10_TMP_ALLOCATION_FILE_NEW A--462765
WHERE CONTROL = 'M'
;
SELECT
	COUNT(*)
FROM
	DESA_CLIENTES.CT.TMP_TB_APP_M10_TMP_ALLOCATION_FILE_NEW A--24253
	WHERE CONTROL = 'C'
;

SELECT
	COUNT(DISTINCT A.OFFER_ID)
FROM--SELECT * FROM
	DESA_CLIENTES.CT.APP_M10_TOTAL_BOLETA_OFERTAS A
WHERE
	A.CYCLE = $CICLO
;--8

SELECT
	COUNT(DISTINCT A.OFFER_ID)
FROM
	DESA_CLIENTES.CT.TMP_TB_APP_M10_TMP_ALLOCATION_FILE_NEW A--204
INNER JOIN--SELECT * FROM
	DESA_CLIENTES.CT.APP_M10_TOTAL_BOLETA_OFERTAS P--207
ON--37284
	A.OFFER_ID = P.OFFER_ID
WHERE
	P.CYCLE = $CICLO
;--8

SELECT
	A.OFFER_ID
	, COUNT(*)
FROM
	DESA_CLIENTES.CT.TMP_TB_APP_M10_TMP_ALLOCATION_FILE_NEW A
GROUP BY 1
;
