/**********************EJECUTAR SP*************************************/
EXEC DESA_CLIENTES.RU.SP_LOAD_APP_ALLOCATION_FILES_TB_ALVI();
EXEC DESA_CLIENTES.RU.SP_LOAD_STG_OUTPUT_DIGITAL_FILE_OFFER_TB_ALVI(14);
EXEC DESA_CLIENTES.RU.SP_LOAD_STG_OUTPUT_DIGITAL_FILE_CUSTOMER_OFFER_TB_ALVI(14);

/**********************CAMBIARSE DE BD*********************************/
SET CATALOG NZ_CLIENTES;
EXEC NZ_CLIENTES.STG.SP_LOAD_STG_OUTPUT_RD_FILES_BETATEST_TB_ALVI();
/************************TRUNCAR TABLAS********************************/
TRUNCATE TABLE NZ_CLIENTES.STG.STG_OUTPUT_DIGITAL_FILE_CUSTOMER;
TRUNCATE TABLE NZ_CLIENTES.STG.STG_OUTPUT_DIGITAL_FILE_OFFER;
TRUNCATE TABLE NZ_CLIENTES.STG.STG_OUTPUT_DIGITAL_FILE_CUSTOMER_OFFER;

