SELECT
	--DISTINCT A.LOAD_DATE
	MAX(A.LOAD_DATE)
FROM
	DESA_CLIENTES.JL.TMP_STG_OUTPUT_DIGITAL_FILE_CUSTOMER_OFFER_BLIND A
WHERE
	A.LOAD_DATE = '2022-06-30 11:46:04'
;--'2022-02-24 12:49:06'LOAD_DATE, 

SELECT 
	COUNT(*)
	, COUNT(DISTINCT A.OFFER_ID)
FROM
	DESA_CLIENTES.JL.APP_ALVI_TMP_ALLOCATION_FILE_OP_BLINDAJE A
;--884520	36

SELECT
	COUNT(DISTINCT A.ID_OFERTA)
	, COUNT(*)
FROM
	DESA_CLIENTES.JL.TMP_STG_OUTPUT_DIGITAL_FILE_CUSTOMER_OFFER_BLIND A
WHERE
	A.TIPO_OFERTA = 2
	AND A.LOAD_DATE = '2022-06-30 11:46:04'
;--36	884520

SELECT
	COUNT(DISTINCT A.ID_OFERTA)
	, COUNT(*)
FROM
	NZ_CLIENTES.STG.STG_OUTPUT_DIGITAL_FILE_CUSTOMER_OFFER A
WHERE
	A.TIPO_OFERTA = 2
;--36	884520
/************************************************************/

SELECT
	COUNT(DISTINCT A.HASH_RUT)
FROM
	DESA_CLIENTES.JL.TMP_STG_OUTPUT_DIGITAL_FILE_CUSTOMER_OFFER_BLIND A
WHERE
	A.LOAD_DATE = '2022-06-30 11:46:04'
	AND A.TIPO_OFERTA = 2
;--24570

SELECT
	COUNT(1)
FROM
	DESA_CLIENTES.JL.TMP_STG_OUTPUT_DIGITAL_FILE_CUSTOMER_OFFER_BLIND A
WHERE
	A.LOAD_DATE ='2022-06-30 11:46:04'
;--884520

/***********************************************************/
SELECT
	COUNT(DISTINCT A.ID_OFERTA)
FROM
	DESA_CLIENTES.JL.TMP_STG_OUTPUT_DIGITAL_FILE_CUSTOMER_OFFER_BLIND A--169537
WHERE
	A.LOAD_DATE = '2022-06-30 11:46:04'
;--36

SELECT
	COUNT(DISTINCT A.OFFER_ID)
FROM
	DESA_CLIENTES.JL.APP_ALVI_OFERTAS_BLIND A
WHERE
	A.CYCLE = 9
	AND A.TIPO_OFERTA LIKE 'Personalizada%'
;--113

/**************EXPORT ARCHIVO OFERTA***********************/
SELECT
	--A.NOMBRE_ARCHIVO,
	A.ID_FORMATO	
	, A.ID_APLICA_OFERTA	
	, A.ID_OFERTA	
	, A.ID_PERIODO	
	, A.FECHA_INICIO_PERIODO	
	, A.FECHA_FIN_PERIODO	
	, A.MAX_USO	
	, A.MAX_UNIDADES_X_USO	
	, A.UNIDAD_MEDIDA	
	, A.DESCRIPCION_OFERTA	
	, A.ID_MECANICA	
	, A.CONTENIDO_MECANICA	
	, A.LEGAL	
	, A.CANAL	
	, A.ID_CATALOGO	
	, A.DESCRIPCION_TIPO	
	, A.ORDEN_DCTO	
	, A.UNICARD_DCTO
	, 'FALSE' AS UNIPAY
	, CASE WHEN A.CHANNEL = 'ALL' THEN ''
	ELSE '' END AS CHANNEL
FROM
	DESA_CLIENTES.JL.TMP_STG_OUTPUT_DIGITAL_FILE_OFFER_BLIND A
;