--REGION INSERCION DE CAMPAÑAS
SELECT
	*
FROM
	NZ_CLIENTES.IC.DIM_CAMPAIGN_DH	
WHERE	
	CAMPAIGN_ID IN (114,116)
;
INSERT INTO NZ_CLIENTES.IC.DIM_CAMPAIGN_DH
SELECT
	5 AS ORGANIZATION_ID
	, MAX(DCD.CAMPAIGN_ID) + 1 AS CAMPAIGN_ID
	, 'ALVI BLINDADOS' AS CAMPAIGN_NAME
	, '2022-06-01 00:00:00' AS START_DATE
	, '2022-12-31 00:00:00' AS END_DATE
	, 'CAMPAÑA BLINDADOS ALVI' AS DESCRIPTION
	, NOW()::DATE AS LOAD_DATE
	, 'JL' AS LOAD_OWNER
	, 'APP' AS CAMPAIGN_CHANEL
FROM
	NZ_CLIENTES.IC.DIM_CAMPAIGN_DH DCD
CROSS JOIN
	(
		--REGION PERIODO
		SELECT
			DISTINCT A.FECHA_INICIO_PERIODO
			, A.FECHA_FIN_PERIODO
		FROM
			DESA_CLIENTES.RU.APP_ALVI_OFERTAS A
		--END REGION
	) B
GROUP BY 1,3,4,5,6,7,8
;
--END REGION
;
--120 resto del año
--REGION CAMPAING_TYPE AND CAMPAIGN_LVL
SELECT
	*
FROM
	NZ_CLIENTES.IC.DIM_CAMPAIGN_TYPE_DH
;

SELECT
	*
FROM
	NZ_CLIENTES.IC.DIM_CAMPAIGN_LVL_DH
--END REGION
;

--REGION INSERCION DE CICLO
SELECT
	*
FROM --SELECT MAX(A.CYCLE_ID) FROM
	NZ_CLIENTES.IC.DIM_CYCLE_DH A 
WHERE	
	CAMPAIGN_ID = 120
	AND 
	CYCLE_ID >= 1203
;

INSERT INTO NZ_CLIENTES.IC.DIM_CYCLE_DH
--REGION OFERTAS PERSONALIZADAS
SELECT
	5 AS ORGANIZATION_ID
	, 120 AS CAMPAIGN_ID
	, 2 AS CAMPAIGN_TYPE_ID
	, MAX(CYCLE_ID) + 1 AS CYCLE_ID
	, B.CYCLE_NUMBER AS CYCLE_NUMBER
	, B.CYCLE_DESCRIPTION AS CYCLE_DESCRIPTION
	, B.START_DATE AS START_DATE
	, B.END_DATE AS END_DATE
	, 5 AS SOURCE_ID
	, NOW()::DATE AS LOAD_DATE
	, 'JL' AS LOAD_OWNER
FROM --SELECT * FROM
	NZ_CLIENTES.IC.DIM_CYCLE_DH A
CROSS JOIN
	(
		--REGION OFERTAS PERSONALIZADAS
		SELECT
			DISTINCT
			'C'||CYCLE|| ' APP PERSONALIZED OFFERS BLIND' AS CYCLE_DESCRIPTION
			, CYCLE AS CYCLE_NUMBER
			, A.FECHA_INICIO_CICLO::DATE AS START_DATE
			, A.FECHA_FIN_CICLO::DATE AS END_DATE
			--SELECT *
		FROM
			DESA_CLIENTES.JL.APP_ALVI_OFERTAS_BLIND A
		WHERE
			A.CYCLE = $CICLO
			AND UPPER(A.TIPO_OFERTA) LIKE UPPER('Personalizada%')
		--END REGION
	) B
GROUP BY 1,2,3,5,6,7,8,9
--END REGION

;
--END REGION
;

--REGION SPOT.DIM_OFFER_CYCLE
SELECT
	*
FROM
	NZ_CLIENTES.SPOT.DIM_OFFER_CYCLE_DH
WHERE
	CYCLE_ID >= 1203
	--CYCLE_ID IN (116,117,118) --OP 
	--CYCLE_ID IN (52,56,60,66,68,72) --PC
	--CYCLE_ID IN (53,57,62,65,69,73) --MAS 
	--CYCLE_ID IN (54,58,61,63,70,74) --TOTALBOLETA 
;

INSERT INTO NZ_CLIENTES.SPOT.DIM_OFFER_CYCLE_DH
--REGION OFERTAS PERSONALIZADAS
SELECT
	B.CYCLE_ID AS CYCLE_ID
	, A.*
FROM
	(
		--REGION OFERTAS
		SELECT
			DISTINCT
			A.OFFER_ID AS OFFER_ID
			, A.OFFER_RANK AS OFFER_RANK
			, A.MAX_UNITS AS MAX_UNITS
			, A.MAX_UNITS AS MAX_UNITS_GEO
			, A.UNIDAD_MEDIDA AS UNIDAD_MEDIDA
			, CASE
				WHEN A.OFFER_ID = 90000 THEN A.DCTO::INTEGER
				WHEN ROUND(DCTO::FLOAT,2)*100::INTEGER < 100 THEN ROUND(DCTO::FLOAT,2)*100::INTEGER
				WHEN ROUND(DCTO::FLOAT,2)*100::INTEGER > 1 THEN ROUND(DCTO::FLOAT,2)*100::INTEGER 
				END AS DISCOUNT_PERC
			, 'DIGALV'||LPAD(A.ID_PERIODO,3, '0')||LPAD($CICLO,3, '0')||LPAD(A.OFFER_ID,5, '0') AS LOYALTY_ID 
			, SQLEXT..REPLACE(ID_PROMOTION, 'IMP_', '')::INT AS DISCOUNT_ID --DCTO REAL
			, ID_PROMOTION AS OFFER_KPI_CODE --------------------------------DCTO REAL
			, NULL AS OFFER_BAR_CODE
			, A.OFFER_DESC AS OFFER_DESC
			, A.OFFER_MAX_USES AS OFFER_MAX_USES
			, A.FECHA_INICIO_CICLO::DATE AS OFFER_START_DATE
			, A.FECHA_INICIO_CICLO::DATE AS OFFER_START_DATE_GEO
			, A.FECHA_FIN_CICLO::DATE AS OFFER_END_DATE
			, A.FECHA_FIN_CICLO::DATE AS OFFER_END_DATE_GEO
			, NZ_CLIENTES.ADMIN.REPLACE(NZ_CLIENTES.ADMIN.REPLACE(NZ_CLIENTES.ADMIN.REPLACE(NZ_CLIENTES.ADMIN.REPLACE(NZ_CLIENTES.ADMIN.REPLACE(NZ_CLIENTES.ADMIN.REPLACE(A.OFFER_LEGAL,'{FECHA_INICIO_CICLO}',A.FECHA_INICIO_CICLO::VARCHAR(50)),'{FECHA_FIN_CICLO}',A.FECHA_FIN_CICLO::VARCHAR(50)),'{MAX_UNITS}',A.MAX_UNITS::VARCHAR(1000)),'{UNIDAD_MEDIDA}', A.UNIDAD_LEGAL::VARCHAR(1000)),'{STOCK}',A.OFFER_STOCK::VARCHAR(1000)),'{OFFER_DESC}',A.OFFER_DESC::VARCHAR(1000))::VARCHAR(5000) AS OFFER_LEGAL
			, CASE WHEN A.OFFER_ID <> 90000 THEN 'APP'||LPAD(A.ORGANIZATION_ID,2,0)||LPAD(A.ID_PERIODO,2,0)||LPAD($CICLO,3,0)||LPAD(A.OFFER_ID,5,0) END AS OFFER_PRODUCT_LIST
			, 'APP' AS OFFER_PROMOTION_TYPE
			, A.TIPO_FINANCIAMIENTO||' CRM_ALVI_APP_'||A.CYCLE||'_'||A.OFFER_ID AS FINANCE_TYPE
			, NULL AS FINANCING_FLAG
			, A.OFFER_STOCK AS OFFER_STOCK
			, 1 AS OFFER_TYPE_ID --PROMO REAL --------------------------<<<<<<<<<<<<<<<<<<<<<  OFFER TYPE ID (TARJETA)
		FROM--SELECT * FROM
			(
			SELECT 
				OF.* 
				, CASE WHEN OF.UNIDAD_MEDIDA = 'UN' THEN 'unidades' ELSE OF.UNIDAD_MEDIDA END UNIDAD_LEGAL
			FROM
				DESA_CLIENTES.JL.APP_ALVI_OFERTAS_BLIND OF
			) A
		INNER JOIN--SELECT * FROM
			DESA_CLIENTES.JL.APP_ALVI_REL_IDS_BLIND B
		ON
			A.OFFER_ID = SUBSTR(B.ID_GEOLOYALTY, 13, 5)::INT
			AND A.CYCLE = B.CICLO -----------comentar para total boleta
		WHERE
		--	A.OFFER_ID = 90000
			A.CYCLE = $CICLO
			AND UPPER(A.TIPO_OFERTA) LIKE UPPER('Personalizada%')
		--END REGION
	) A
CROSS JOIN
	(
		--REGION CYCLE_ID
		SELECT
			CYCLE_ID
		FROM
			NZ_CLIENTES.IC.DIM_CYCLE_DH A
		WHERE
			A.CAMPAIGN_ID = 120
			AND A.CYCLE_NUMBER = $CICLO
			AND A.CAMPAIGN_TYPE_ID = 2 --OFERTAS PERSONALIZADAS
		--END REGION
	) B
--END REGION

--END REGION
;

--REGION INSERCION CICLO CENTRO
SELECT
	A.CYCLE_ID
	, COUNT(*)
FROM--SELECT * FROM
	NZ_CLIENTES.IC.FACT_CENTER_CYCLE_DH A
WHERE
	A.CYCLE_ID >= 1203
GROUP BY 1
;

INSERT INTO NZ_CLIENTES.IC.FACT_CENTER_CYCLE_DH
SELECT
	B.CYCLE_ID
	, A.CENTER_ID
FROM
	(
		--REGION CENTROS ALVI
		SELECT 
			DISTINCT
			FM.CENTER_ID
		FROM
			NZ_PRODUCCION.BDF.FACT_MONTH_CENTER FM
		INNER JOIN
			NZ_PRODUCCION.BDF.DIM_CENTER DC
		ON
			FM.CENTER_ID = DC.CENTER_ID
			AND DC.ORGANIZATION_ID = 5
		WHERE
			FM.MONTH_ID >= 202206
		--END REGION
	) A
CROSS JOIN
	(
		--REGION CICLOS CAMPAÑA 21
		SELECT
			DISTINCT CYCLE_ID
		FROM
			NZ_CLIENTES.IC.DIM_CYCLE_DH A
		WHERE
			A.CAMPAIGN_ID = 120
			AND A.CYCLE_NUMBER = $CICLO
		--END REGION
	) B

--END REGION
;

--REGION OFFER_CYCLE
SELECT
	*
FROM
	NZ_CLIENTES.IC.FACT_OFFER_CYCLE_DH A
WHERE
	A.CYCLE_ID >= 1203
;

INSERT INTO NZ_CLIENTES.IC.FACT_OFFER_CYCLE_DH
SELECT
	DISTINCT
	A.CYCLE_ID
	, A.OFFER_ID
	, A.DISCOUNT_ID
	, CASE WHEN A.DISCOUNT_PERC > 100000 THEN A.DISCOUNT_PERC/100 ELSE A.DISCOUNT_PERC END || CASE WHEN A.DISCOUNT_PERC < 100 THEN '% ' ELSE ' ' END || A.OFFER_DESC AS OFFER_DESC
	, A.OFFER_TYPE_ID
	, A.OFFER_MAX_USES
	, CASE WHEN A.DISCOUNT_PERC > 100000 THEN A.DISCOUNT_PERC/100 ELSE A.DISCOUNT_PERC END AS DISCOUNT_PERC
FROM--SELECT A.* FROM 
	NZ_CLIENTES.SPOT.DIM_OFFER_CYCLE_DH A
INNER JOIN
	NZ_CLIENTES.IC.DIM_CYCLE_DH B
ON
	A.CYCLE_ID = B.CYCLE_ID
WHERE
	B.CAMPAIGN_ID = 120
	AND B.CYCLE_NUMBER = $CICLO

--END REGION
;


--REGION CLIENTE OFERTA CICLO
SELECT
	A.CYCLE_ID
	, A.OFFER_ID
	, COUNT(*)
FROM--SELECT * FROM
	NZ_CLIENTES.IC.FACT_CUSTOMER_OFFER_CYCLE_DH A
WHERE
	CYCLE_ID >=1203 --OP 
	--CYCLE_ID IN (52,56,60,66,68,72)--PC
	--CYCLE_ID IN (53,57,62,65,73) --MAS  NO VA
	--CYCLE_ID IN (54,58,61,63,74) --TOTALBOLETA  no va	
GROUP BY 1,2
--TOTAL DE REGISTROS, TIENE QUE CUADRAR EL TOTAL DE OP Y ALOCATION
;

DROP TABLE DESA_CLIENTES.RU.TMP_BASE_CARGA_CUSTOMER_OFFER_CYCLE IF EXISTS;
CREATE TABLE DESA_CLIENTES.RU.TMP_BASE_CARGA_CUSTOMER_OFFER_CYCLE AS
--REGION CLIENTE OFERTA CICLO
SELECT
	*--SELECT DISTINCT A.LOAD_DATE
FROM
	 DESA_CLIENTES.JL.TMP_STG_OUTPUT_DIGITAL_FILE_CUSTOMER_OFFER_BLIND A
where load_date = '2022-06-30 11:46:04'
	AND A.TIPO_OFERTA IN (2,6)
--END REGION
;--2561799  


SELECT
A.CYCLE_ID,
	count(*)
--DELETE	
FROM
	NZ_CLIENTES.IC.FACT_CUSTOMER_OFFER_CYCLE_DH A
WHERE 
	A.CYCLE_ID >= 1203
	group by 1
LIMIT 1000
;

INSERT INTO NZ_CLIENTES.IC.FACT_CUSTOMER_OFFER_CYCLE_DH 
SELECT
	DISTINCT
	B.CYCLE_ID
	, A.CUSTOMER_ID
	, A.OFFER_ID
	, A.OFFER_RANK
	, A.EAN
FROM
	(
		--REGION CLIENTE OFERTA
		SELECT
			DISTINCT
			CASE WHEN A.NOMBRE_ARCHIVO LIKE '%_2_5.csv' THEN 2 WHEN A.NOMBRE_ARCHIVO LIKE '%_6_5.csv' THEN 6 END AS CAMPAIGN_TYPE_ID
			, B.CUSTOMER_ID
			, A.ID_OFERTA AS OFFER_ID
			, A.RANKING_OFERTA AS OFFER_RANK
			, TRIM(A.IMAGEN)::BIGINT AS EAN
		FROM--SELECT * FROM--SELECT DISTINCT NOMBRE_ARCHIVO, LOAD_DATE FROM
		   DESA_CLIENTES.RU.TMP_BASE_CARGA_CUSTOMER_OFFER_CYCLE A
		INNER JOIN
			NZ_CLIENTES.IC.CL_HASH B
		ON
			A.HASH_RUT = B.HASH_STRING
		INNER JOIN
			(
				--REGION OFERTAS ACTIVAS
				SELECT
					DISTINCT OFFER_ID
				FROM
					DESA_CLIENTES.JL.APP_ALVI_OFERTAS_BLIND
				WHERE
					UPPER(TIPO_OFERTA) LIKE UPPER('Personalizada%')
					AND CYCLE = $CICLO
				--END REGION
			) C
		ON
			A.ID_OFERTA = C.OFFER_ID
		WHERE
			(A.NOMBRE_ARCHIVO LIKE '%_2_5.csv' OR A.NOMBRE_ARCHIVO LIKE '%_6_5.csv')
		--END REGION
	) A
INNER JOIN
	(
		--REGION CYCLE OF PER AND PEN CATEGORY
		SELECT
			A.CYCLE_ID
			, A.CAMPAIGN_TYPE_ID
		FROM
			NZ_CLIENTES.IC.DIM_CYCLE_DH A
		WHERE
			A.CAMPAIGN_ID = 120
			AND A.CAMPAIGN_TYPE_ID IN (2,6)
			AND A.CYCLE_ID >= $CYCLE_ID
		--END REGION
	) B
ON
	A.CAMPAIGN_TYPE_ID = B.CAMPAIGN_TYPE_ID
	
	
--END REGION
;



--REGION CLIENTE CICLO
SELECT
	CYCLE_ID
	, COUNT(*)
FROM--select * from
	NZ_CLIENTES.IC.FACT_CUSTOMER_CYCLE_DH
WHERE
	--CYCLE_ID IN (100,101,102) --OP 
	CYCLE_ID >= 1203--PC
	--CYCLE_ID IN (53,57,62,65) --MAS 
	--CYCLE_ID IN (54,58,61,63) --TOTALBOLETA  
GROUP BY 1



INSERT INTO NZ_CLIENTES.IC.FACT_CUSTOMER_CYCLE_DH
SELECT
	B.CYCLE_ID
	, A.*
FROM
	(
		--REGION CLIENTES DH
		SELECT DISTINCT
			Y.CUSTOMER_ID
			, NOW()::DATE AS INSERT_DATE
			, 1 AS TARGET_GROUP
			, X.RANKING AS DH_SCORE
		FROM
			(
				SELECT 
					DISTINCT A.HASH_RUT
					, A.RANKING
				FROM--SELECT * FROM 
			    	DESA_CLIENTES.JL.TMP_STG_OUTPUT_DIGITAL_FILE_CUSTOMER_BLIND A
			) X
		INNER JOIN
			NZ_CLIENTES.IC.CL_HASH Y
		ON
			X.HASH_RUT = Y.HASH_STRING
		
		--END REGION
	) A
CROSS JOIN
	(
		--REGION CICLOS OP Y PC
		SELECT
			DISTINCT CYCLE_ID
		FROM--SELECT * FROM
			NZ_CLIENTES.IC.DIM_CYCLE_DH 
		WHERE
			CAMPAIGN_ID = 120
			AND CAMPAIGN_TYPE_ID IN (2,6)
			AND CYCLE_NUMBER = $CICLO
			AND CYCLE_ID >=$CYCLE_ID
		--END REGION
	) B
	--263786 
--END REGION
;

--REGION OFERTA EAN	
SELECT
	*
FROM
	NZ_CLIENTES.SPOT.DIM_OFFER_CYCLE_SKU_EAN_DH A
WHERE 
	A.CYCLE_ID >= 1203
;

--REGION INSERT SPOT
INSERT INTO NZ_CLIENTES.SPOT.DIM_OFFER_CYCLE_SKU_EAN_DH
SELECT
	DISTINCT
	B.CYCLE_ID
	, B.OFFER_ID
	, A.MATERIAL
	, A.EAN
FROM
	(
		--REGION OFERTA EAN
			SELECT
				DISTINCT
				A.OFFER_ID
				, B.MATERIAL
				, A.EAN
			FROM--SELECT * FROM
				DESA_CLIENTES.JL.APP_ALVI_OFERTAS_PLU_BLIND A
			INNER JOIN
				(
					--REGION LINEA POR EAN
					SELECT DISTINCT
						TRIM(P.EAN)::BIGINT AS EAN
						, LTRIM(H.SKU_PRODUCT,'0') AS MATERIAL
				 	FROM
						PROD_AMP_MART.AMP.DIM_PRODUCT P
					INNER JOIN --SELECT * FROM 
				        PROD_AMP_MART.AMP.DIM_SKU_HIERARCHY_H H
				 	ON
				        P.SKU_KEY = H.SKU_KEY
					--END REGION
				) B
			ON
				A.EAN = B.EAN
			WHERE
				A.CYCLE = $CICLO
		--END REGION
	) A
INNER JOIN
	(
		--REGION OFERTA CICLO <<<<<<<<<<<<<< CAMPAÑA 18
		SELECT
			DISTINCT
			A.CYCLE_ID
			, A.OFFER_ID	
		FROM
			NZ_CLIENTES.IC.FACT_OFFER_CYCLE_DH  A
		INNER JOIN
			NZ_CLIENTES.IC.DIM_CYCLE_DH B
		ON
			A.CYCLE_ID = B.CYCLE_ID
		WHERE
			B.CAMPAIGN_ID = 120
			AND B.CYCLE_NUMBER = $CICLO
		--END REGION
	) B
ON
	A.OFFER_ID = B.OFFER_ID
--END REGION
;
--1769 

SELECT
	*
FROM
	NZ_CLIENTES.IC.FACT_OFFER_CYCLE_ARTICLE_DH A
WHERE 
	A.CYCLE_ID >= 1203
;

--REGION INSERT FACT
INSERT INTO	NZ_CLIENTES.IC.FACT_OFFER_CYCLE_ARTICLE_DH
SELECT DISTINCT
	DI.ORGANIZATION_ID
	, ART.CYCLE_ID AS CYCLE_ID
	, ART.OFFER_ID
	, DI.ITEM_ARTICLE_ID
FROM--select * from
	NZ_CLIENTES.SPOT.DIM_OFFER_CYCLE_SKU_EAN_DH ART
INNER JOIN
	PROD_AMP_MART.AMP.DIM_PRODUCT_HIERARCHY DPH
ON
	ART.EAN::BIGINT = TRIM(DPH.EAN)
INNER JOIN
	NZ_PRODUCCION.BDF.DIM_ITEM_ARTICLE DI
ON
	LTRIM(DPH.SKU_PRODUCT,'0') = LTRIM(DI.ITEM_ARTICLE_ID_NUM,'0')
	AND DI.ORGANIZATION_ID =5
INNER JOIN--SELECT DISTINCT DC.CAMPAIGN_ID, DC.CYCLE_ID FROM
	NZ_CLIENTES.IC.DIM_CYCLE_DH DC
ON
	ART.CYCLE_ID = DC.CYCLE_ID
WHERE
	DC.CAMPAIGN_ID = 120
	AND DC.CYCLE_NUMBER = $CICLO
--END REGION

--END REGION
;
DROP TABLE DESA_CLIENTES.RU.TMP_BASE_CARGA_CUSTOMER_OFFER_CYCLE IF EXISTS;
