--REGION CONSULTA CREAR TB
DROP TABLE DESA_CLIENTES.JL.TMP_STG_OUTPUT_DIGITAL_FILE_CUSTOMER_BLIND IF EXISTS;
CREATE TABLE DESA_CLIENTES.JL.TMP_STG_OUTPUT_DIGITAL_FILE_CUSTOMER_BLIND AS
--REGION CICLO
SELECT
B.NOMBRE_ARCHIVO
, A.*
FROM
(
			--REGION CLIENTES
			SELECT DISTINCT
			1 ID_FORMATO
			, NULL AS GEO_CUSTOMER
			, B.HASH_STRING AS HASH_RUT
			, A.PROFILE
			, A.RANKING
			FROM
			(
				--REGION CLIENTES CICLO
				SELECT
				DISTINCT
				CL.CUSTOMER_ID
				, 'P' AS PROFILE
				, COALESCE(CL.CUSTOMER_SCORE, 0) AS RANKING
				FROM--SELECT * FROM
				(
					--REGION TOTAL CLIENTES
					SELECT
					CUSTOMER_ID
					, CASE
					WHEN (COUNT_OFFER_ID < 4) THEN 1
					WHEN (COUNT_OFFER_ID = 4) THEN 2
					WHEN (COUNT_OFFER_ID = 5) THEN 3
					WHEN (COUNT_OFFER_ID = 6) THEN 4
					WHEN (COUNT_OFFER_ID > 6) THEN 5
					ELSE 1 END AS CUSTOMER_SCORE
					FROM
					(
						SELECT
						A.CUSTOMER_ID
						, COUNT(DISTINCT A.OFFER_ID) AS COUNT_OFFER_ID
						FROM--SELECT * FROM
						DESA_CLIENTES.JL.APP_ALVI_TMP_ALLOCATION_FILE_OP_BLINDAJE A
						GROUP BY 1
					) A
					--END REGION
				) CL
				--END REGION
			) A
			INNER JOIN
			NZ_CLIENTES.IC.CL_HASH B
			ON
			A.CUSTOMER_ID = B.CUSTOMER_ID
			--END REGION
) A
CROSS JOIN
(
			--REGION NOMBRE ARCHIVO CLIENTES
			SELECT
			DISTINCT 'CLIENTES_'||TO_CHAR(FECHA_INICIO_CICLO, 'YYMMDD')||'_'||TO_CHAR(FECHA_FIN_CICLO, 'YYMMDD')||'_1.csv' AS NOMBRE_ARCHIVO
			FROM--SELECT * FROM 
			DESA_CLIENTES.JL.APP_ALVI_OFERTAS_BLIND
			WHERE
			CYCLE = $CICLO_
			--END REGION
) B



--END REGION
;
--END REGION 