SELECT
	MAX(A.LOAD_DATE)
FROM
	DESA_CLIENTES.JL.TMP_STG_OUTPUT_DIGITAL_FILE_CUSTOMER_OFFER_CAU A
;--'2022-07-21 16:45:49'
/*****
DESA_CLIENTES.RU.TMP_STG_OUTPUT_DIGITAL_FILE_CUSTOMER_OFFER A
DELETE
FROM
	DESA_CLIENTES.RU.TMP_STG_OUTPUT_DIGITAL_FILE_CUSTOMER_OFFER_TB_ALVI A
WHERE
	A.LOAD_DATE = '2022-02-24 17:02:52'
*/
SELECT 
	COUNT(DISTINCT A.OFFER_ID)
	, COUNT(*)
FROM
	DESA_CLIENTES.JL.TMP_ALLOCATION_FILE_CAU_UNI A--272
;--1	131927
SELECT
	COUNT(DISTINCT A.ID_OFERTA)
	, COUNT(*)
FROM
	DESA_CLIENTES.JL.TMP_STG_OUTPUT_DIGITAL_FILE_CUSTOMER_OFFER_CAU A
WHERE
	A.LOAD_DATE ='2022-07-21 16:45:49'
;--1	131927
/***********************************************************/

SELECT
	COUNT(DISTINCT A.OFFER_ID)
	--SELECT * 
FROM
	DESA_CLIENTES.JL.APP_UNI_CAU A
WHERE
	A.CYCLE = $CICLO
--5
;

/***********************************************************/
SELECT
	*
FROM
	DESA_CLIENTES.JL.TMP_STG_OUTPUT_DIGITAL_FILE_OFFER_CAU A
;--5

SELECT
	COUNT(DISTINCT A.ID_OFERTA)
FROM
	DESA_CLIENTES.JL.TMP_STG_OUTPUT_DIGITAL_FILE_CUSTOMER_OFFER_CAU A
WHERE
	A.LOAD_DATE = '2022-07-21 16:45:49'
;--1

SELECT
*
FROM
TRUNCATE 
	DESA_CLIENTES.JL.TMP_STG_OUTPUT_DIGITAL_FILE_CUSTOMER_OFFER_CAU B
WHERE
	B.LOAD_DATE ='2022-07-21 16:45:49'
;--131927 --CARGA A MONGO

/***
UPDATE
	DESA_CLIENTES.RU.TMP_STG_OUTPUT_DIGITAL_FILE_CUSTOMER_OFFER_TB
SET
	FECHA_INICIO_CICLO = '2021-03-11 09:13:19'
WHERE
	LOAD_DATE = '2021-03-11 09:13:19'
;
/**************EXPORT ARCHIVO OFERTA***********************/
SELECT
	--A.NOMBRE_ARCHIVO,
	A.ID_FORMATO	
	, A.ID_APLICA_OFERTA	
	, A.ID_OFERTA	
	, A.ID_PERIODO	
	, A.FECHA_INICIO_PERIODO	
	, A.FECHA_FIN_PERIODO	
	, A.MAX_USO	
	, A.MAX_UNIDADES_X_USO::INTEGER AS 	MAX_UNIDADES_X_USO
	, A.UNIDAD_MEDIDA	
	, A.DESCRIPCION_OFERTA	
	, 11 AS ID_MECANICA
	, A.CONTENIDO_MECANICA	
	, A.LEGAL	
	, A.CANAL	
	, A.ID_CATALOGO	
	, A.DESCRIPCION_TIPO	
	, A.ORDEN_DCTO	
	, A.UNICARD_DCTO
	, 'NO' AS HASDEPTH
    , '' AS OFFER_LEVEL
    , '' AS UNITPRICE
    , '' AS DEPTHMECANICAID
    , '' AS DEPTHMECANICA
	, 'FALSE' AS UNIPAY
	, 'ONLY STORE' AS CHANNEL
FROM
	DESA_CLIENTES.JL.TMP_STG_OUTPUT_DIGITAL_FILE_OFFER_CAU A
;