SELECT
	DISTINCT *
FROM DESA_CLIENTES.JL.TMP_ALLOCATION_FILE_SYD_ALVI
;--440808

SELECT * FROM DESA_CLIENTES.JL.TMP_SYD_APP_ALVI_TMP_ALLOCATION_FILE

--REGION INSERT TABLA FINAL
TRUNCATE TABLE DESA_CLIENTES.JL.TMP_SYD_APP_ALVI_TMP_ALLOCATION_FILE;
INSERT INTO DESA_CLIENTES.JL.TMP_SYD_APP_ALVI_TMP_ALLOCATION_FILE (CUSTOMER_ID,OFFER_ID,SHABIT)
SELECT
	A.CUSTOMER_ID,
	A.OFFER_ID,
	NULL AS RANK
FROM--SELECT * FROM	
	DESA_CLIENTES.JL.TMP_ALLOCATION_FILE_SYD_ALVI A
;	
--END REGION

-
--VALIDAR QUE CLIENTE NO TENGA MAS DE 1 OFERTA FUGADOS
SELECT
	A.CUSTOMER_ID
	, COUNT(*)
FROM DESA_CLIENTES.JL.TMP_ALLOCATION_FILE_SYD_ALVI A
GROUP BY 1
HAVING COUNT > 1
;

SELECT
	*
FROM --UPDATE
	DESA_CLIENTES.JL.APP_ALVI_JOURNEYDOWN

;--4


/*OFERTA 10%*/
SELECT
	A.OFFER_ID,
	COUNT(*)
FROM DESA_CLIENTES.JL.TMP_SYD_APP_TMP_ALLOCATION_FILE A
WHERE
	A.OFFER_ID = 85065
GROUP BY 1
;--44065