--FUGADOS

SELECT
	COUNT(*)
FROM DESA_CLIENTES.NS.TMP_ALLOCATION_FILE_FUG_ALVI_VESPUCIO A
WHERE
	A.CONTROL = 'M'
;--467

SELECT
	COUNT(*)
FROM DESA_CLIENTES.NS.TMP_ALLOCATION_FILE_FUG_ALVI_VESPUCIO A
WHERE
	A.CONTROL = 'C'
;--25

SELECT
	DISTINCT *
FROM DESA_CLIENTES.NS.TMP_ALLOCATION_FILE_FUG_ALVI_VESPUCIO
;--492

SELECT * FROM DESA_CLIENTES.RU.TMP_TB_APP_ALVI_TMP_ALLOCATION_FILE

--REGION INSERT TABLA FINAL
TRUNCATE TABLE DESA_CLIENTES.RU.TMP_TB_APP_ALVI_TMP_ALLOCATION_FILE;
INSERT INTO DESA_CLIENTES.RU.TMP_TB_APP_ALVI_TMP_ALLOCATION_FILE
SELECT
	A.CUSTOMER_ID,
	A.OFFER_ID,
	NULL AS RANK
FROM--SELECT * FROM	
	DESA_CLIENTES.NS.TMP_ALLOCATION_FILE_FUG_ALVI_VESPUCIO A
WHERE
	A.CONTROL = 'M'
;	
--END REGION


--REGION INSERTA RUTS_ADMINS A TABLA SALIDA DESA_CLIENTES.RU.TMP_TB_APP_ALVI_TMP_ALLOCATION_FILE

INSERT INTO DESA_CLIENTES.RU.TMP_TB_APP_ALVI_TMP_ALLOCATION_FILE(
	CUSTOMER_ID 
	,OFFER_ID
)VALUES ('2766034935','90060');

INSERT INTO DESA_CLIENTES.RU.TMP_TB_APP_ALVI_TMP_ALLOCATION_FILE(
	CUSTOMER_ID 
	,OFFER_ID
)VALUES ('14901908856','90060');

INSERT INTO DESA_CLIENTES.RU.TMP_TB_APP_ALVI_TMP_ALLOCATION_FILE(
	CUSTOMER_ID 
	,OFFER_ID
)VALUES ('9301853370','90060');

INSERT INTO DESA_CLIENTES.RU.TMP_TB_APP_ALVI_TMP_ALLOCATION_FILE(
	CUSTOMER_ID 
	,OFFER_ID
)VALUES ('12541661346','90060');


--END REGION

-- COMPRUEBA LA OFERTA EN TABLA DE SALIDAD PARA LOS CUSTOMER ADMS
SELECT * FROM DESA_CLIENTES.RU.TMP_TB_APP_ALVI_TMP_ALLOCATION_FILE 
WHERE CUSTOMER_ID IN ('8721001477','12541661346','9301853370','14901908856','8490767007','2766034935')

--FUGADOS
SELECT
	A.OFFER_ID,
	COUNT(*)
FROM DESA_CLIENTES.NS.TMP_ALLOCATION_FILE_FUG_ALVI_VESPUCIO A
WHERE
	UPPER(A.TARGETING) = 'LAPSER'
GROUP BY 1
;--4 5962

--CAIDOS
SELECT
	A.OFFER_ID,
	COUNT(*)
FROM DESA_CLIENTES.CT.TMP_ALLOCATION_FILE_FUG_ALVI A
WHERE
	UPPER(A.TARGETING) = 'DECLINER'
GROUP BY 1
;-- 4 11703

--VALIDAR QUE CLIENTE NO TENGA MAS DE 1 OFERTA TOTAL BOLETA VESPUCIO
SELECT
	A.CUSTOMER_ID
	, COUNT(*)
FROM DESA_CLIENTES.NS.TMP_ALLOCATION_FILE_FUG_ALVI_VESPUCIO A
GROUP BY 1
HAVING COUNT > 1
;

--CLIENTE NO PUEDE ESTAR EN FUGADOS Y EN CAIDOS

SELECT
	A.CUSTOMER_ID
	, COUNT(*)
FROM
	(
		SELECT
			*
		FROM 
			DESA_CLIENTES.SG.TMP_TB_APP_ALLOCATION_FILE A
		WHERE
			UPPER(A.TARGETING) = 'LAPSER'
		UNION ALL
		SELECT
			*
		FROM 
			DESA_CLIENTES.SG.TMP_TB_APP_ALLOCATION_FILE A
		WHERE
			UPPER(A.TARGETING) = 'DECLINER'
	) A
GROUP BY 1
HAVING COUNT > 1
;

SELECT
	*
FROM --SELECT * FROM 
	DESA_CLIENTES.CT.APP_ALVI_TOTAL_BOLETA_OFERTAS
;--1


/*OFERTA 10%*/
SELECT
	A.OFFER_ID,
	COUNT(*)
FROM DESA_CLIENTES.RU.TMP_TB_APP_TMP_ALLOCATION_FILE A
WHERE
	A.OFFER_ID = 85065
GROUP BY 1
;--44065