--FUGADOS

SELECT
	COUNT(*)
FROM DESA_CLIENTES.CT.TMP_ALLOCATION_FILE_FUG_ALVI A
WHERE
	A.CONTROL = 'M'
;--83802

SELECT
	COUNT(*)
FROM DESA_CLIENTES.CT.TMP_ALLOCATION_FILE_FUG_ALVI A
WHERE
	A.CONTROL = 'C'
;--4543

SELECT
	DISTINCT *
FROM DESA_CLIENTES.CT.TMP_ALLOCATION_FILE_FUG_ALVI
;--440808

SELECT * FROM DESA_CLIENTES.RU.TMP_TB_APP_ALVI_TMP_ALLOCATION_FILE

--REGION INSERT TABLA FINAL
TRUNCATE TABLE DESA_CLIENTES.RU.TMP_TB_APP_ALVI_TMP_ALLOCATION_FILE;
INSERT INTO DESA_CLIENTES.RU.TMP_TB_APP_ALVI_TMP_ALLOCATION_FILE
SELECT
	A.CUSTOMER_ID,
	A.OFFER_ID,
	NULL AS RANK
FROM--SELECT * FROM	
	DESA_CLIENTES.RU.TMP_TB_APP_ALVI_TMP_ALLOCATION_FILE A
WHERE
	A.CONTROL = 'M'
;	
--END REGION --NO HACER--

--FUGADOS
SELECT
	A.OFFER_ID,
	COUNT(*)
FROM DESA_CLIENTES.RU.TMP_TB_APP_ALVI_TMP_ALLOCATION_FILE A
WHERE
	UPPER(A.TARGETING) = 'LAPSER'
GROUP BY 1
;--4 5962

--CAIDOS
SELECT
	A.OFFER_ID,
	COUNT(*)
FROM DESA_CLIENTES.RU.TMP_TB_APP_ALVI_TMP_ALLOCATION_FILE A
WHERE
	UPPER(A.TARGETING) = 'DECLINER'
GROUP BY 1
;-- 4 11703

--VALIDAR QUE CLIENTE NO TENGA MAS DE 1 OFERTA FUGADOS
SELECT
	A.CUSTOMER_ID
	, COUNT(*)
FROM DESA_CLIENTES.CT.TMP_ALLOCATION_FILE_FUG_ALVI A
GROUP BY 1
HAVING COUNT > 1
;

--CLIENTE NO PUEDE ESTAR EN FUGADOS Y EN CAIDOS

SELECT
	A.CUSTOMER_ID
	, COUNT(*)
FROM
	(
		SELECT
			*
		FROM 
			DESA_CLIENTES.RU.TMP_TB_APP_ALVI_TMP_ALLOCATION_FILE A
		WHERE
			UPPER(A.TARGETING) = 'LAPSER'
		UNION ALL
		SELECT
			*
		FROM 
			DESA_CLIENTES.RU.TMP_TB_APP_ALVI_TMP_ALLOCATION_FILE A
		WHERE
			UPPER(A.TARGETING) = 'DECLINER'
	) A
GROUP BY 1
HAVING COUNT > 1
;

SELECT
	*
FROM --SELECT * FROM 
	DESA_CLIENTES.CT.APP_ALVI_TOTAL_BOLETA_OFERTAS
;--4


/*OFERTA 10%*/
SELECT
	A.OFFER_ID,
	COUNT(*)
FROM DESA_CLIENTES.RU.TMP_TB_APP_TMP_ALLOCATION_FILE A
WHERE
	A.OFFER_ID = 85065
GROUP BY 1
;--44065