SELECT
	B.OFFER_ID
	, A.ID_OFERTA_GEO
	, B.OFFER_DESC
	, ROUND(NZ_CLIENTES.ADMIN.REPLACE(NZ_CLIENTES.ADMIN.REPLACE(upper(B.DCTO),',','.'),'X','')::FLOAT,2) AS DESCUENTO
	, C.ID_PROMOTION
	, C.LISTAS_PRODUCTOS
	, B.MAX_UNITS
	, B.TIPO_OFERTA
	, P.CANTIDAD_PRODUCTOS
FROM--SELECT * FROM
	(
	SELECT
		DISTINCT A.ID_OFERTA_GEO
		, ID_OFERTA
	FROM-- select distinct load_date from 
		DESA_CLIENTES.RU.TMP_STG_OUTPUT_DIGITAL_FILE_CUSTOMER_OFFER_M10 A
	WHERE
		A.LOAD_DATE = (select max(load_date) from DESA_CLIENTES.RU.TMP_STG_OUTPUT_DIGITAL_FILE_CUSTOMER_OFFER_M10)
	) A
INNER JOIN-- select * from 
	DESA_CLIENTES.RU.APP_M10_OFERTAS B
ON
	A.ID_OFERTA = B.OFFER_ID
	AND B.CYCLE = $CICLO
INNER JOIN--SELECT * FROM
	DESA_CLIENTES.RU.APP_M10_REL_IDS C
ON
	C.CICLO = B.CYCLE
	AND CASE WHEN LENGTH(C.LISTAS_PRODUCTOS) > 0 THEN SQLEXT..REPLACE(C.LISTAS_PRODUCTOS,'APP'||LPAD(B.ORGANIZATION_ID,2,0)||LPAD(B.ID_PERIODO,2,0)||LPAD(B.CYCLE,3,0), '')::INT END= B.OFFER_ID
INNER JOIN
	(
	SELECT
		DISTINCT
		A.OFFER_ID
		,A.COUNT(A.EAN) AS CANTIDAD_PRODUCTOS
	FROM 
		DESA_CLIENTES.RU.APP_M10_OFERTAS_PLU A
	WHERE
		A.CYCLE = $CICLO
	GROUP BY 1
	)P
ON
	P.OFFER_ID = B.OFFER_ID
;
	
	
-------------------------------------------------------------------------------------------------------------	
	select a.OFFER_ID , b.id_oferta from 
	DESA_CLIENTES.RU.APP_M10_OFERTAS A 
	left join 
	(
		select distinct id_oferta from 
	DESA_CLIENTES.RU.TMP_STG_OUTPUT_DIGITAL_FILE_CUSTOMER_OFFER_M10 A
	WHERE
		A.LOAD_DATE = (select max(load_date) from DESA_CLIENTES.RU.TMP_STG_OUTPUT_DIGITAL_FILE_CUSTOMER_OFFER_M10)
	
	
	) B
	on a.OFFER_ID = b.id_oferta
	where 	A.CYCLE = $CICLO
	
	select distinct id_oferta from 
	DESA_CLIENTES.RU.TMP_STG_OUTPUT_DIGITAL_FILE_CUSTOMER_OFFER_M10 A
	WHERE
		A.LOAD_DATE = (select max(load_date) from DESA_CLIENTES.RU.TMP_STG_OUTPUT_DIGITAL_FILE_CUSTOMER_OFFER_M10)
	
	
	select * from 
	DESA_CLIENTES.RU.APP_M10_OFERTAS A 
	where OFFER_ID = 689
	
	SELECT
	A.ID_FORMATO||'_'||A.ID_PERIODO||'_'||A.ID_OFERTA AS REF_ID
	, A.HASH_RUT	
	, A.GEO_CUSTOMER AS GEO_CUSTOMER
	, COALESCE(A.ID_OFERTA_GEO||'','') AS ID_OFERTA_GEO
	, COALESCE(A.ID_PERIODO||'','') AS ID_PERIODO
	, COALESCE(A.ID_CICLO||'','') AS ID_CICLO
	, A.ID_FORMATO	
	, A.ID_OFERTA	
	, A.IMAGEN	
	, A.IMAGEN_DEFECTO
	, A.RANKING_OFERTA	
	, A.TIPO_OFERTA	
	, A.FECHA_INICIO_CICLO	
	, A.FECHA_FIN_CICLO	
FROM 
	NZ_CLIENTES.STG.STG_OUTPUT_DIGITAL_FILE_CUSTOMER_OFFER A
;