/***********************************
REVISAR RANKING Y 
OFFER ID DUPLICADOS
************************************/

SELECT
	A.CUSTOMER_ID
	, A.OFFER_ID
	, COUNT(*)
FROM
	DESA_CLIENTES.RU.APP_M10_TMP_ALLOCATION_FILE_OP A--43732583
GROUP BY 1,2
HAVING COUNT > 1	
;

SELECT
	A.CUSTOMER_ID
	, A.OFFER_ID
	, COUNT(*)
FROM
	DESA_CLIENTES.RU.APP_M10_TMP_ALLOCATION_FILE_PC A--43732583
GROUP BY 1,2
HAVING COUNT > 1
;

SELECT
	A.CUSTOMER_ID
	, A.OFFER_ID
	, COUNT(*)
FROM
	(
		SELECT
			*
		FROM 
			DESA_CLIENTES.RU.APP_M10_TMP_ALLOCATION_FILE_OP A
		UNION ALL
		SELECT
			*
		FROM 
			DESA_CLIENTES.RU.APP_M10_TMP_ALLOCATION_FILE_PC B
	) A--43732583
GROUP BY 1,2
HAVING COUNT > 1
;

SELECT
	A.CUSTOMER_ID
	, A.OFFER_RANK
	, COUNT(*)
FROM
	DESA_CLIENTES.RU.APP_M10_TMP_ALLOCATION_FILE_OP A
GROUP BY 1,2
HAVING COUNT > 1
;

SELECT
	A.CUSTOMER_ID
	, A.OFFER_RANK
	, COUNT(*)
FROM
	DESA_CLIENTES.RU.APP_M10_TMP_ALLOCATION_FILE_PC A
GROUP BY 1,2
HAVING COUNT > 1
;

/************************************************************/
SELECT
	COUNT(*)
FROM
	DESA_CLIENTES.RU.APP_M10_TMP_ALLOCATION_FILE_OP A--22035438
;

SELECT
	COUNT(DISTINCT A.OFFER_ID)
FROM
	DESA_CLIENTES.RU.APP_M10_TMP_ALLOCATION_FILE_OP A--156
;

SELECT
	COUNT(DISTINCT A.OFFER_ID)
FROM
	DESA_CLIENTES.RU.APP_M10_TMP_ALLOCATION_FILE_PC A--138
;

SELECT
	COUNT(DISTINCT A.CUSTOMER_ID)
FROM
	DESA_CLIENTES.RU.APP_M10_TMP_ALLOCATION_FILE_OP A--6046224
;

SELECT
*
FROM
	DESA_CLIENTES.RU.APP_M10_OFERTAS A
WHERE
	A.CYCLE = $CICLO
	--AND A.TIPO_OFERTA LIKE '%Perso%'
;--207 OFERTAS EN TOTAL
--162 personalizadas
--45 masivas

SELECT
*
FROM
	DESA_CLIENTES.RU.APP_M10_OFERTAS_PLU A
WHERE
	A.CYCLE = $CICLO
;--670

SELECT DISTINCT OFFER_ID, CYCLE
FROM DESA_CLIENTES.RU.APP_M10_OFERTAS 
WHERE OFFER_ID NOT IN (SELECT OFFER_ID FROM DESA_CLIENTES.RU.APP_M10_OFERTAS_PLU)
AND CYCLE = $CICLO

DELETE FROM DESA_CLIENTES.RU.APP_M10_OFERTAS 
WHERE OFFER_ID = 7019
AND CYCLE = $CICLO

SELECT
	COUNT(DISTINCT A.OFFER_ID)
FROM
	DESA_CLIENTES.RU.APP_M10_OFERTAS A
WHERE
	A.CYCLE = $CICLO
	AND UPPER(A.TIPO_OFERTA) LIKE UPPER('Personalizada%')
;--165
--masivas 145 = total 247

SELECT
	COUNT(DISTINCT A.OFFER_ID)
FROM
	DESA_CLIENTES.RU.APP_M10_TMP_ALLOCATION_FILE_OP A--192
INNER JOIN--SELECT * FROM
	DESA_CLIENTES.RU.APP_M10_OFERTAS P--116
ON--37284
	A.OFFER_ID = P.OFFER_ID
WHERE
	P.CYCLE = $CICLO
	AND UPPER(P.TIPO_OFERTA) LIKE UPPER('Personalizada%')
;--155 Faltan 52

SELECT
	DISTINCT
	A.OFFER_ID
	, P.OFFER_ID
FROM
	DESA_CLIENTES.RU.APP_M10_TMP_ALLOCATION_FILE_PC A--257
LEFT JOIN
	DESA_CLIENTES.RU.APP_M10_OFERTAS P--227
ON
	A.OFFER_ID = P.OFFER_ID
	AND P.CYCLE = $CICLE
	AND UPPER(P.TIPO_OFERTA) LIKE UPPER('Personalizada%')
;--118

/*--
ofertas está en los archivos de DH-OP, pero no en el archivo oferta
SELECT * FROM 
DESA_CLIENTES.RU.APP_M10_OFERTAS WHERE OFFER_ID IN (
6308)
*/

--OFFER_ID, UPDATE DESA_CLIENTES.RU.APP_M10_TMP_ALLOCATION_FILE_OP SET OFFER_ID = 3077  WHERE OFFER_ID = 941

SELECT
	DISTINCT
	A.OFFER_ID
	, P.OFFER_ID
FROM
	DESA_CLIENTES.RU.APP_M10_TMP_ALLOCATION_FILE_OP A--257
RIGHT JOIN
	DESA_CLIENTES.RU.APP_M10_OFERTAS P--227
ON
	A.OFFER_ID = P.OFFER_ID
WHERE
	P.CYCLE = $CICLE
	AND UPPER(P.TIPO_OFERTA) LIKE UPPER('Personalizada%')
;--100


SELECT
*
FROM
	--DESA_CLIENTES.RU.APP_M10_TMP_ALLOCATION_FILE_PC A
	DESA_CLIENTES.RU.APP_M10_OFERTAS A
WHERE A.OFFER_ID IN (
6063,
6109,
6106,
6108,
6194,
6096,
6084,
6097,
6107
)
/* Estan en el archivo oferta pero no el Allocation-OP
6096
6084
6097
Estan en Op pero no en Ofertas
*/

SELECT
	*
FROM
	DESA_CLIENTES.RU.APP_M10_TMP_ALLOCATION_FILE_PC A--246
WHERE
	A.OFFER_ID IN (43)
;

DELETE FROM
--SELECT DISTINCT(OFFER_ID) FROM
	DESA_CLIENTES.RU.APP_M10_OFERTAS A--246
WHERE
CYCLE = 43 AND
	A.OFFER_ID IN (6108,
6063,
6109,
6194,
6084,
6096,
6097,
6106,
6107)
;

SELECT DISTINCT A.OFFER_ID FROM 
DESA_CLIENTES.RU.APP_M10_OFERTAS A
WHERE A.OFFER_ID NOT IN (
SELECT OFFER_ID FROM 
DESA_CLIENTES.RU.APP_M10_TMP_ALLOCATION_FILE_OP P
UNION
SELECT OFFER_ID FROM 
DESA_CLIENTES.RU.APP_M10_TMP_ALLOCATION_FILE_PC C
)
AND A.CYCLE = $CICLO

--REGION OBTENCION DE OFERTAS FALTANTES EN OP Y PC
SELECT
	DISTINCT
	A.OFFER_ID
FROM
	(
	SELECT
		DISTINCT
		A.OFFER_ID
	FROM
		DESA_CLIENTES.RU.APP_M10_OFERTAS A
	LEFT JOIN
		DESA_CLIENTES.RU.APP_M10_TMP_ALLOCATION_FILE_OP P
	ON
		P.OFFER_ID = A.OFFER_ID
	WHERE
		A.CYCLE = $CICLO
		AND UPPER(A.TIPO_OFERTA) = UPPER('Personalizada')
		AND P.OFFER_ID IS NULL
	)A
LEFT JOIN
	DESA_CLIENTES.RU.APP_M10_TMP_ALLOCATION_FILE_PC B
ON
	A.OFFER_ID = B.OFFER_ID
WHERE
	B.OFFER_ID IS NULL
;
--END REGION

/*
OFFER_ID	OFFER_DESC
*/

/************************PENETRACIÓN CATEGORIA**********************/
SELECT
	COUNT(*)
FROM
	DESA_CLIENTES.RU.APP_M10_TMP_ALLOCATION_FILE_PC A--32781380
;

SELECT
	COUNT(DISTINCT A.OFFER_ID)
FROM
	DESA_CLIENTES.RU.APP_M10_TMP_ALLOCATION_FILE_PC A--138
;

SELECT
	COUNT(DISTINCT A.CUSTOMER_ID)
FROM
	DESA_CLIENTES.RU.APP_M10_TMP_ALLOCATION_FILE_PC A--7650297
;


SELECT
	COUNT(DISTINCT A.OFFER_ID)
FROM
	DESA_CLIENTES.RU.APP_M10_OFERTAS A
WHERE
	A.CYCLE = $CICLE
	AND UPPER(A.TIPO_OFERTA) LIKE UPPER('Personalizada%')
;--164

SELECT
	COUNT(DISTINCT A.OFFER_ID),
	COUNT(*)
FROM -- select * from
	DESA_CLIENTES.RU.APP_M10_TMP_ALLOCATION_FILE_PC A--190
INNER JOIN--SELECT * FROM
	DESA_CLIENTES.RU.APP_M10_OFERTAS P--207
ON--37284
	A.OFFER_ID = P.OFFER_ID
WHERE
	P.CYCLE = $CICLE
	AND UPPER(P.TIPO_OFERTA) LIKE UPPER('Personalizada%')
;--137	32474807

SELECT
	DISTINCT
	A.OFFER_ID
	, P.OFFER_ID
FROM
	DESA_CLIENTES.RU.APP_M10_TMP_ALLOCATION_FILE_PC A--257
LEFT JOIN
	DESA_CLIENTES.RU.APP_M10_OFERTAS P--227
ON
	A.OFFER_ID = P.OFFER_ID
	AND P.CYCLE = $CICLE
	AND UPPER(P.TIPO_OFERTA) LIKE UPPER('Personalizada%')
;--95

/*
--ESTÁN EN ARCHIVO DE ALLOCATION PERO NO EN EL ARCHIVO OFERTA
*/	

SELECT
	DISTINCT
	A.OFFER_ID
	, P.OFFER_ID
FROM
	DESA_CLIENTES.RU.APP_M10_TMP_ALLOCATION_FILE_PC A--257
RIGHT JOIN
	DESA_CLIENTES.RU.APP_M10_OFERTAS P--227
ON
	A.OFFER_ID = P.OFFER_ID
WHERE 
	P.CYCLE = $CICLE
	AND UPPER(P.TIPO_OFERTA) LIKE UPPER('Personalizada%')
;--145


SELECT
	DISTINCT
	A.OFFER_ID
FROM
	DESA_CLIENTES.RU.APP_M10_TMP_ALLOCATION_FILE_OP A
WHERE A.OFFER_ID IN (
6097,
6084,
6096
)
--En el archivo oferta pero no en el allocation-PC
/*
6097,
6084,
6096
*/
DELETE 
FROM DESA_CLIENTES.RU.APP_M10_OFERTAS_PLU A
WHERE A.OFFER_ID IN (
6097,
6084,
6096
)

SELECT
	*
FROM
	DESA_CLIENTES.RU.APP_M10_OFERTAS A--115
WHERE
	A.CYCLE = 44
;--209

--REGION OBTENER OFERTAS QUE NO ESTAN EN ALLOCATION OP NI PC 

SELECT
	B.OFFER_ID
FROM
	(
	SELECT
		DISTINCT
		P.OFFER_ID
	FROM
		DESA_CLIENTES.RU.APP_M10_TMP_ALLOCATION_FILE_OP A
	RIGHT JOIN-- select * from
		DESA_CLIENTES.RU.APP_M10_OFERTAS P
	ON
		A.OFFER_ID = P.OFFER_ID
	WHERE
		P.CYCLE = $ciclo
		AND UPPER(P.TIPO_OFERTA) = UPPER('%Personalizada%')
		AND A.OFFER_ID IS NULL
	)A
INNER JOIN
	(
	SELECT
		DISTINCT
		P.OFFER_ID
	FROM
		DESA_CLIENTES.RU.APP_M10_TMP_ALLOCATION_FILE_PC A
	RIGHT JOIN
		DESA_CLIENTES.RU.APP_M10_OFERTAS P
	ON
		A.OFFER_ID = P.OFFER_ID
	WHERE 
		P.CYCLE = $ciclo
		AND UPPER(P.TIPO_OFERTA) = UPPER('Personalizada%')
		AND A.OFFER_ID IS NULL
	)B
ON
	A.OFFER_ID = B.OFFER_ID 
--END REGION	
;--

--REGION NO VIENE EN DH BY JL
SELECT OFFER_ID FROM DESA_CLIENTES.RU.APP_M10_OFERTAS X
WHERE X.OFFER_ID NOT IN (
SELECT DISTINCT A.OFFER_ID FROM(
SELECT DISTINCT OFFER_ID FROM 
DESA_CLIENTES.RU.APP_M10_TMP_ALLOCATION_FILE_OP
UNION 
SELECT DISTINCT OFFER_ID FROM 
DESA_CLIENTES.RU.APP_M10_TMP_ALLOCATION_FILE_PC) AS A)
AND UPPER(X.TIPO_OFERTA) = UPPER('Personalizada')
AND CYCLE = $CICLO
--END REGION

/************************VALIDA CRUCE DE OFERTAS************************************/
--VALIDACION DE CARGAS DE CRM


SELECT
	DISTINCT A.OFFER_ID
FROM 
	DESA_CLIENTES.RU.APP_M10_OFERTAS A
WHERE
	A.CYCLE = $CICLO
;--211

SELECT
	DISTINCT A.OFFER_ID
FROM 
	DESA_CLIENTES.RU.APP_M10_OFERTAS_PLU A
WHERE
	A.CYCLE = $CICLO
;--211

/*************************REVISAR EANS DUPLICADOS*********************************+*/
SELECT B.EAN
FROM
(SELECT
	A.EAN
	, COUNT(*)
FROM 
	DESA_CLIENTES.RU.APP_M10_OFERTAS_PLU A
WHERE
	A.CYCLE = $CICLO GROUP BY 1
HAVING COUNT > 1) B
;

SELECT * FROM DESA_CLIENTES.RU.APP_M10_OFERTAS_PLU
WHERE EAN IN (
SELECT 
A.EAN
FROM DESA_CLIENTES.RU.APP_M10_OFERTAS_PLU A
WHERE
	A.CYCLE = $CICLO
GROUP BY A.EAN
HAVING COUNT(A.EAN) > 1)
AND CYCLE = $CICLO
;

DELETE FROM DESA_CLIENTES.RU.APP_M10_OFERTAS
WHERE OFFER_ID IN (6308 , 7113)

SELECT 
	A.ROWID
FROM 
	DESA_CLIENTES.RU.APP_M10_OFERTAS_PLU A
INNER JOIN
	(
	SELECT 
		ROW_NUMBER()OVER(PARTITION BY A.EAN ORDER BY A.EAN)AS POS,
		A.EAN,
        A.ROWID
        FROM 
			DESA_CLIENTES.RU.APP_M10_OFERTAS_PLU A
        INNER JOIN 
        	(
            SELECT 
            	A.EAN,
            	COUNT(*)
            FROM 
				DESA_CLIENTES.RU.APP_M10_OFERTAS_PLU A 
			WHERE
				A.CYCLE = $CICLO
            GROUP BY A.EAN
            HAVING COUNT(*) > 1
        ) TB
        ON A.EAN = TB.EAN
		WHERE
		A.CYCLE = $CICLO
	)B
	ON	A.ROWID = B.ROWID
	AND B.POS > 1
;--OBTENER DUPLICADOS       

SELECT
	COUNT(A.OFFER_ID)
FROM 
	DESA_CLIENTES.RU.APP_M10_OFERTAS_PLU A
WHERE
	A.CYCLE = $CICLO
;--672

SELECT
	COUNT(*)
FROM 
	DESA_CLIENTES.RU.APP_M10_OFERTAS A
WHERE
	A.CYCLE = $CICLO
;--211


/*OFFER ID DUPLICADOS 31,67,73,78,83,175,177,181*/

DELETE
FROM
	DESA_CLIENTES.RU.APP_M10_OFERTAS_PLU A
WHERE
	ROWID IN 
			(
			SELECT 
				A.ROWID
			FROM 
				DESA_CLIENTES.RU.APP_M10_OFERTAS_PLU A
			INNER JOIN
			(
			SELECT 
				ROW_NUMBER()OVER(PARTITION BY A.EAN ORDER BY A.EAN)AS POS,
				A.EAN,
		        A.ROWID
		        FROM 
					DESA_CLIENTES.RU.APP_M10_OFERTAS_PLU A
		        INNER JOIN 
		        	(
		            SELECT 
		            	A.EAN,
		            	COUNT(*)
		            FROM 
						DESA_CLIENTES.RU.APP_M10_OFERTAS_PLU A 
					WHERE
						A.CYCLE = $CICLO
		            GROUP BY A.EAN
		            HAVING COUNT(*) > 1
		        ) TB
		        ON A.EAN = TB.EAN
				WHERE
				A.CYCLE = $CICLO
			)B
			ON	A.ROWID = B.ROWID
			AND B.POS > 1  
			)
;

SELECT
	A.OFFER_ID,
	COUNT(A.OFFER_ID)
FROM 
	DESA_CLIENTES.RU.APP_M10_OFERTAS A
	--DESA_CLIENTES.RU.APP_M10_OFERTAS_PLU A
WHERE
	A.CYCLE = $CICLO
	GROUP BY 1
	HAVING COUNT(A.OFFER_ID)> 1
;--172
7054
SELECT
	DISTINCT
	A.OFFER_ID
FROM 
	DESA_CLIENTES.RU.APP_M10_OFERTAS_PLU A
WHERE
	A.CYCLE = $CICLO
;--209


SELECT
	COUNT(*)
FROM 
	DESA_CLIENTES.RU.APP_M10_OFERTAS_PLU A
WHERE
	A.CYCLE = $CICLO
;--670

SELECT 
	* 
FROM 
	DESA_CLIENTES.RU.APP_M10_OFERTAS A
WHERE
	A.CYCLE = $CICLO
	--207

--PRECIO REFERENCIAL, SIEMPRE ES NULL, A MENOS QUE TENGA PRECIO FIJO
--ID WORKFLOW PUEDE SER NULL PERO TIENE QUE SER TIPO_FINANCIAMIENTO S/F
--DCTO NO PUEDE SER NULL
--MARCA NO PUEDE SER NULLCYCLE, 
;
	