--REGION INSERCION DE CAMPAÑAS
--Esta query se utiliza cuando se realiza un cambio de periodo
SELECT
	*
FROM
	NZ_CLIENTES.IC.DIM_CAMPAIGN_DH A
WHERE
A.CAMPAIGN_NAME = 'M10 FUGADOS Y CAIDOS 2022'
	A.CAMPAIGN_ID = 96
;

--CAMPAING_ID 66
INSERT INTO NZ_CLIENTES.IC.DIM_CAMPAIGN_DH
SELECT
	1 AS ORGANIZATION_ID
	, MAX(DCD.CAMPAIGN_ID) + 1 AS CAMPAIGN_ID
	, 'M10 FUGADOS Y CAIDOS 2022' AS CAMPAIGN_NAME
	, '2021-10-06 00:00:00'::DATE AS START_DATE
	, '2022-01-04 00:00:00'::DATE AS END_DATE
	, 'M10 FUGADOS Y CAIDOS 2022' AS DESCRIPTION
	, NOW()::DATE AS LOAD_DATE
	, 'JL' AS LOAD_OWNER
	, 'APP' AS CAMPAIGN_CHANEL
FROM
	NZ_CLIENTES.IC.DIM_CAMPAIGN_DH DCD
CROSS JOIN
	(
		--REGION PERIODO
		SELECT
			DISTINCT A.FECHA_INICIO_PERIODO
			, A.FECHA_FIN_PERIODO
		FROM
			DESA_CLIENTES.CT.APP_M10_TOTAL_BOLETA_OFERTAS A
		--END REGION
	) B
GROUP BY 1,3,4,5,6,7,8
;
--END REGION
;
--96 el resto del año

--REGION CAMPAING_TYPE AND CAMPAIGN_LVL
SELECT
	*
FROM
	NZ_CLIENTES.IC.DIM_CAMPAIGN_TYPE_DH
;

SELECT
	*
FROM
	NZ_CLIENTES.IC.DIM_CAMPAIGN_LVL_DH
--END REGION
;
--FUGADOS 1164
--CAIDOS 1165

--REGION INSERCION DE CICLO
SELECT
	*
FROM--SELECT CYCLE_ID FROM
	NZ_CLIENTES.IC.DIM_CYCLE_DH
WHERE	
	CAMPAIGN_ID = 96
	AND CYCLE_ID >= 1219
;
--FUGADOS 1219
--CAIDOS 1220

INSERT INTO NZ_CLIENTES.IC.DIM_CYCLE_DH
--REGION TOTAL BOLETA FUGADOS
--CAMBIA CYCLE ID
SELECT
	4 AS ORGANIZATION_ID
	, 96 AS CAMPAIGN_ID
	, 13 AS CAMPAIGN_TYPE_ID
	, MAX(CYCLE_ID) + 1 AS CYCLE_ID
	, B.CYCLE_NUMBER AS CYCLE_NUMBER
	, B.CYCLE_DESCRIPTION AS CYCLE_DESCRIPTION
	, B.START_DATE AS START_DATE
	, B.END_DATE AS END_DATE
	, 5 AS SOURCE_ID
	, NOW()::DATE AS LOAD_DATE
	, 'JL' AS LOAD_OWNER
FROM --SELECT * FROM
	NZ_CLIENTES.IC.DIM_CYCLE_DH A
CROSS JOIN
	(
		--REGION OFERTAS TOTAL BOLETA
		SELECT
			DISTINCT
			'C'||$CICLO|| ' APP BASKET TB FUGADOS M10' AS CYCLE_DESCRIPTION
			, $CICLO AS CYCLE_NUMBER
			, A.FECHA_INICIO_CICLO AS START_DATE
			, A.FECHA_FIN_CICLO AS END_DATE
		FROM--SELECT * FROM
			DESA_CLIENTES.CT.APP_M10_TOTAL_BOLETA_OFERTAS A
		WHERE
			A.CYCLE = $CICLO	
			--CYCLE_ID 512
		--END REGION
	) B
GROUP BY 1,2,3,5,6,7,8,9
--END REGION
UNION ALL
--REGION TOTAL BOLETA CAIDOS
--CAMBIA CYCLE ID
SELECT
	4 AS ORGANIZATION_ID
	, 96 AS CAMPAIGN_ID
	, 13 AS CAMPAIGN_TYPE_ID
	, MAX(CYCLE_ID) + 2 AS CYCLE_ID
	, B.CYCLE_NUMBER AS CYCLE_NUMBER
	, B.CYCLE_DESCRIPTION AS CYCLE_DESCRIPTION
	, B.START_DATE AS START_DATE
	, B.END_DATE AS END_DATE
	, 5 AS SOURCE_ID
	, NOW()::DATE AS LOAD_DATE
	, 'JL' AS LOAD_OWNER
FROM --SELECT * FROM
	NZ_CLIENTES.IC.DIM_CYCLE_DH A
CROSS JOIN
	(
		--REGION OFERTAS TOTAL BOLETA
		SELECT
			DISTINCT
			'C'||$CICLO|| ' APP BASKET TB CAIDOS M10' AS CYCLE_DESCRIPTION
			, $CICLO AS CYCLE_NUMBER
			, A.FECHA_INICIO_CICLO AS START_DATE
			, A.FECHA_FIN_CICLO AS END_DATE
		FROM--SELECT * FROM
			DESA_CLIENTES.CT.APP_M10_TOTAL_BOLETA_OFERTAS A
		WHERE
			A.CYCLE = $CICLO	
			--CYCLE_ID 512
		--END REGION
	) B
GROUP BY 1,2,3,5,6,7,8,9
--END REGION
;

--END REGION
;
---QUEDE ACA
--REGION SPOT.DIM_OFFER_CYCLE
SELECT
	*
FROM
	NZ_CLIENTES.SPOT.DIM_OFFER_CYCLE_DH
WHERE
	CYCLE_ID > 1219
	--CYCLE_ID IN (51,55,59,64,67,71) --OP 
	--CYCLE_ID IN (52,56,60,66,68,72) --PC
	--CYCLE_ID IN (53,57,62,65,69,73) --MAS 
	--CYCLE_ID IN (54,58,61,63,70,74) --TOTALBOLETA 
;
OFFER_ID, 
INSERT INTO NZ_CLIENTES.SPOT.DIM_OFFER_CYCLE_DH
--SE NECESITAN LOS CODIGOS DE PROMOCION PARA HACER EL INSERT
--REGION TOTAL BOLETA FUGADOS
SELECT
	B.CYCLE_ID AS CYCLE_ID
	, A.*
FROM
	(
		--REGION OFERTAS
		SELECT
			DISTINCT
			A.OFFER_ID AS OFFER_ID
			, A.OFFER_RANK AS OFFER_RANK
			, A.MAX_UNITS AS MAX_UNITS
			, A.MAX_UNITS AS MAX_UNITS_GEO
			, A.UNIDAD_MEDIDA AS UNIDAD_MEDIDA
			, CASE
				WHEN A.OFFER_ID = 90000 THEN NZ_CLIENTES.ADMIN.REPLACE(NZ_CLIENTES.ADMIN.REPLACE(A.DCTO,',','.'),'X','')::INTEGER
				WHEN ROUND(NZ_CLIENTES.ADMIN.REPLACE(NZ_CLIENTES.ADMIN.REPLACE(DCTO,',','.'),'X','')::FLOAT,2)*100::INTEGER < 100 THEN ROUND(NZ_CLIENTES.ADMIN.REPLACE(NZ_CLIENTES.ADMIN.REPLACE(DCTO,',','.'),'X','')::FLOAT,2)*100::INTEGER
				WHEN ROUND(NZ_CLIENTES.ADMIN.REPLACE(NZ_CLIENTES.ADMIN.REPLACE(DCTO,',','.'),'X','')::FLOAT,2)*100::INTEGER > 100 THEN ROUND(NZ_CLIENTES.ADMIN.REPLACE(NZ_CLIENTES.ADMIN.REPLACE(DCTO,',','.'),'X','')::FLOAT,2)::INTEGER 
				END AS DISCOUNT_PERC
			, 'DIGMAY'||LPAD(A.ID_PERIODO,3, '0')||LPAD($CICLO,3, '0')||LPAD(A.OFFER_ID,5, '0') AS LOYALTY_ID 
			, SQLEXT..REPLACE(SQLEXT..REPLACE(B.ID_PROMOTION, 'IMP_', ''),',','.')::INT AS DISCOUNT_ID --DCTO REAL
			, B.ID_PROMOTION AS OFFER_KPI_CODE --------------------------------DCTO REAL
			, NULL AS OFFER_BAR_CODE
			, A.OFFER_DESC AS OFFER_DESC
			, A.OFFER_MAX_USES AS OFFER_MAX_USES
			--OFERTAS REGULARES
			, A.FECHA_INICIO_CICLO::DATE AS OFFER_START_DATE
			, A.FECHA_INICIO_CICLO::DATE AS OFFER_START_DATE_GEO
			, A.FECHA_FIN_CICLO::DATE AS OFFER_END_DATE
			, A.FECHA_FIN_CICLO::DATE AS OFFER_END_DATE_GEO
			--OFERTAS REGULARES FIN
			, (CASE WHEN A.OFFER_ID = 90000 THEN 'Oferta válida para miembros del Club Ahorro Unimarc, mayores de 18 años, que descarguen la APP Club Ahorro, activen su cupón y lo canjeen en caja, entre el '||A.FECHA_INICIO_CICLO::VARCHAR(50)||' y '||A.FECHA_FIN_CICLO::VARCHAR(50)||', ambas fechas inclusive. El descuento es válido para una sola compra por cliente. Cupón INTRANSFERIBLE. Descuento no acumulable con otras ofertas y/o promociones. Promoción válida sólo para compras con boleta. Bases legales en www.unimarc.cl.' 
				ELSE NZ_CLIENTES.ADMIN.REPLACE(NZ_CLIENTES.ADMIN.REPLACE(NZ_CLIENTES.ADMIN.REPLACE(NZ_CLIENTES.ADMIN.REPLACE(NZ_CLIENTES.ADMIN.REPLACE(NZ_CLIENTES.ADMIN.REPLACE(A.OFFER_LEGAL,'{FECHA_INICIO_CICLO}',A.FECHA_INICIO_CICLO::VARCHAR(50)),'{FECHA_FIN_CICLO}',A.FECHA_FIN_CICLO::VARCHAR(50)),'{MAX_UNITS}',A.MAX_UNITS::VARCHAR(1000)),'{UNIDAD_MEDIDA}', A.UNIDAD_LEGAL::VARCHAR(1000)),'{STOCK}',A.OFFER_STOCK::VARCHAR(1000)),'{OFFER_DESC}',A.OFFER_DESC::VARCHAR(1000)) END)::VARCHAR(5000) AS OFFER_LEGAL
			, CASE WHEN A.OFFER_ID <> 90000 THEN 'CRM_APP_TB_' || A.OFFER_ID END AS OFFER_PRODUCT_LIST
			, 'APP' AS OFFER_PROMOTION_TYPE
			, A.TIPO_FINANCIAMIENTO||' CRM_APP_TB'||A.CYCLE||'_'||A.OFFER_ID AS FINANCE_TYPE
			, NULL AS FINANCING_FLAG
			, A.OFFER_STOCK AS OFFER_STOCK
			, 1 AS OFFER_TYPE_ID --PROMO REAL --------------------------<<<<<<<<<<<<<<<<<<<<<  OFFER TYPE ID (TARJETA)
		FROM--SELECT * FROM
			(
			SELECT 
				OF.* 
				, CASE WHEN OF.UNIDAD_MEDIDA = 'UN' THEN 'unidades' ELSE OF.UNIDAD_MEDIDA END UNIDAD_LEGAL
			FROM
				DESA_CLIENTES.CT.APP_M10_TOTAL_BOLETA_OFERTAS OF
			WHERE
				OF.CAMPAIGN LIKE '%FUGADOS%'
			) A
		INNER JOIN--SELECT * FROM
			DESA_CLIENTES.CT.APP_M10_REL_IDS_TB B
		ON
			A.OFFER_ID = SUBSTR(B.ID_GEOLOYALTY, 13, 5)::INT
			AND A.CYCLE = B.CICLO
		WHERE
			A.CYCLE = $CICLO
		--END REGION
	) A
CROSS JOIN
	(
		--REGION CYCLE_ID
		SELECT
			CYCLE_ID
		FROM
			NZ_CLIENTES.IC.DIM_CYCLE_DH A
		WHERE
			A.CAMPAIGN_ID = 96
			AND A.CYCLE_NUMBER = $CICLO
			AND A.CYCLE_ID = 1219
			-->= $CYCLE_ID
			AND A.CAMPAIGN_TYPE_ID = 13 --TOTAL BOLETA
			AND A.CYCLE_DESCRIPTION LIKE '%FUGADOS%'
		--END REGION
	) B

--END REGION
UNION ALL
--REGION TOTAL BOLETA CAIDOS
SELECT
	B.CYCLE_ID AS CYCLE_ID
	, A.*
FROM
	(
		--REGION OFERTAS
		SELECT
			DISTINCT
			A.OFFER_ID AS OFFER_ID
			, A.OFFER_RANK AS OFFER_RANK
			, A.MAX_UNITS AS MAX_UNITS
			, A.MAX_UNITS AS MAX_UNITS_GEO
			, A.UNIDAD_MEDIDA AS UNIDAD_MEDIDA
			, CASE
				WHEN A.OFFER_ID = 90000 THEN NZ_CLIENTES.ADMIN.REPLACE(NZ_CLIENTES.ADMIN.REPLACE(A.DCTO,',','.'),'X','')::INTEGER
				WHEN ROUND(NZ_CLIENTES.ADMIN.REPLACE(NZ_CLIENTES.ADMIN.REPLACE(DCTO,',','.'),'X','')::FLOAT,2)*100::INTEGER < 100 THEN ROUND(NZ_CLIENTES.ADMIN.REPLACE(NZ_CLIENTES.ADMIN.REPLACE(DCTO,',','.'),'X','')::FLOAT,2)*100::INTEGER
				WHEN ROUND(NZ_CLIENTES.ADMIN.REPLACE(NZ_CLIENTES.ADMIN.REPLACE(DCTO,',','.'),'X','')::FLOAT,2)*100::INTEGER > 100 THEN ROUND(NZ_CLIENTES.ADMIN.REPLACE(NZ_CLIENTES.ADMIN.REPLACE(DCTO,',','.'),'X','')::FLOAT,2)::INTEGER 
				END AS DISCOUNT_PERC
			, 'DIGMAY'||LPAD(A.ID_PERIODO,3, '0')||LPAD($CICLO,3, '0')||LPAD(A.OFFER_ID,5, '0') AS LOYALTY_ID 
			, SQLEXT..REPLACE(SQLEXT..REPLACE(B.ID_PROMOTION, 'IMP_', ''),',','.')::INT AS DISCOUNT_ID --DCTO REAL
			, B.ID_PROMOTION AS OFFER_KPI_CODE --------------------------------DCTO REAL
			, NULL AS OFFER_BAR_CODE
			, A.OFFER_DESC AS OFFER_DESC
			, A.OFFER_MAX_USES AS OFFER_MAX_USES
			--OFERTAS REGULARES
			, A.FECHA_INICIO_CICLO::DATE AS OFFER_START_DATE
			, A.FECHA_INICIO_CICLO::DATE AS OFFER_START_DATE_GEO
			, A.FECHA_FIN_CICLO::DATE AS OFFER_END_DATE
			, A.FECHA_FIN_CICLO::DATE AS OFFER_END_DATE_GEO
			--OFERTAS REGULARES FIN
			, (CASE WHEN A.OFFER_ID = 90000 THEN 'Oferta válida para miembros del Club Ahorro Unimarc, mayores de 18 años, que descarguen la APP Club Ahorro, activen su cupón y lo canjeen en caja, entre el '||A.FECHA_INICIO_CICLO::VARCHAR(50)||' y '||A.FECHA_FIN_CICLO::VARCHAR(50)||', ambas fechas inclusive. El descuento es válido para una sola compra por cliente. Cupón INTRANSFERIBLE. Descuento no acumulable con otras ofertas y/o promociones. Promoción válida sólo para compras con boleta. Bases legales en www.unimarc.cl.' 
				ELSE NZ_CLIENTES.ADMIN.REPLACE(NZ_CLIENTES.ADMIN.REPLACE(NZ_CLIENTES.ADMIN.REPLACE(NZ_CLIENTES.ADMIN.REPLACE(NZ_CLIENTES.ADMIN.REPLACE(NZ_CLIENTES.ADMIN.REPLACE(A.OFFER_LEGAL,'{FECHA_INICIO_CICLO}',A.FECHA_INICIO_CICLO::VARCHAR(50)),'{FECHA_FIN_CICLO}',A.FECHA_FIN_CICLO::VARCHAR(50)),'{MAX_UNITS}',A.MAX_UNITS::VARCHAR(1000)),'{UNIDAD_MEDIDA}', A.UNIDAD_LEGAL::VARCHAR(1000)),'{STOCK}',A.OFFER_STOCK::VARCHAR(1000)),'{OFFER_DESC}',A.OFFER_DESC::VARCHAR(1000)) END)::VARCHAR(5000) AS OFFER_LEGAL
			, CASE WHEN A.OFFER_ID <> 90000 THEN 'CRM_APP_TB_' || A.OFFER_ID END AS OFFER_PRODUCT_LIST
			, 'APP' AS OFFER_PROMOTION_TYPE
			, A.TIPO_FINANCIAMIENTO||' CRM_APP_TB'||A.CYCLE||'_'||A.OFFER_ID AS FINANCE_TYPE
			, NULL AS FINANCING_FLAG
			, A.OFFER_STOCK AS OFFER_STOCK
			, 1 AS OFFER_TYPE_ID --PROMO REAL --------------------------<<<<<<<<<<<<<<<<<<<<<  OFFER TYPE ID (TARJETA)
		FROM--SELECT * FROM
			(
			SELECT 
				OF.* 
				, CASE WHEN OF.UNIDAD_MEDIDA = 'UN' THEN 'unidades' ELSE OF.UNIDAD_MEDIDA END UNIDAD_LEGAL
			FROM
				DESA_CLIENTES.CT.APP_M10_TOTAL_BOLETA_OFERTAS OF
			WHERE
				OF.CAMPAIGN LIKE '%CAIDOS%'
			) A
		INNER JOIN--SELECT * FROM
			DESA_CLIENTES.CT.APP_M10_REL_IDS_TB B
		ON
			A.OFFER_ID = SUBSTR(B.ID_GEOLOYALTY, 13, 5)::INT
			AND A.CYCLE = B.CICLO
		WHERE
			A.CYCLE = $CICLO
		--END REGION
	) A
CROSS JOIN
	(
		--REGION CYCLE_ID
		SELECT
			CYCLE_ID
		FROM
			NZ_CLIENTES.IC.DIM_CYCLE_DH A
		WHERE
			A.CAMPAIGN_ID = 96
			AND A.CYCLE_NUMBER = $CICLO
			AND A.CYCLE_ID = 1220
			AND A.CAMPAIGN_TYPE_ID = 13 --TOTAL BOLETA
			AND A.CYCLE_DESCRIPTION LIKE '%CAIDOS%'
		--END REGION
		
	) B

--END REGION
--END REGION

DESA_CLIENTES.DESA_CLIENTES.--REGION INSERCION CICLO CENTRO
SELECT
	A.CYCLE_ID
	, COUNT(*)
FROM--SELECT * FROM
	NZ_CLIENTES.IC.FACT_CENTER_CYCLE_DH A
WHERE
	A.CYCLE_ID IN (1219,1220)
GROUP BY 1
;

INSERT INTO NZ_CLIENTES.IC.FACT_CENTER_CYCLE_DH
--CANTIDAD DE TIENDAS 
SELECT
	B.CYCLE_ID
	, A.CENTER_ID
FROM
	(
		--REGION CENTROS M10
		SELECT 
			DISTINCT
			FM.CENTER_ID
		FROM
			NZ_PRODUCCION.BDF.FACT_MONTH_CENTER FM
		INNER JOIN
			NZ_PRODUCCION.BDF.DIM_CENTER DC
		ON
			FM.CENTER_ID = DC.CENTER_ID
			AND DC.ORGANIZATION_ID = 4
		WHERE
			FM.MONTH_ID >= 202207
		--END REGION
	) A
CROSS JOIN
	(
		--REGION CICLOS CAMPAÑA 23
		SELECT
			DISTINCT CYCLE_ID
		FROM
			NZ_CLIENTES.IC.DIM_CYCLE_DH A
		WHERE
			A.CAMPAIGN_ID = 96
			AND A.CYCLE_NUMBER = $CICLO
			AND A.CYCLE_ID IN (1219,1220)
		--END REGION
	) B

--END REGION
;

--REGION OFFER_CYCLE
SELECT
	*
FROM
	NZ_CLIENTES.IC.FACT_OFFER_CYCLE_DH A
WHERE
	A.CYCLE_ID IN (1219,1220)
;


INSERT INTO NZ_CLIENTES.IC.FACT_OFFER_CYCLE_DH
SELECT
	DISTINCT
	A.CYCLE_ID
	, A.OFFER_ID
	, A.DISCOUNT_ID
	, CASE WHEN A.DISCOUNT_PERC > 100000 THEN A.DISCOUNT_PERC/100 ELSE A.DISCOUNT_PERC END || CASE WHEN A.DISCOUNT_PERC < 100 THEN '% ' ELSE ' ' END || A.OFFER_DESC AS OFFER_DESC
	, A.OFFER_TYPE_ID
	, A.OFFER_MAX_USES
	, CASE WHEN A.DISCOUNT_PERC > 100000 THEN A.DISCOUNT_PERC/100 ELSE A.DISCOUNT_PERC END AS DISCOUNT_PERC
FROM--SELECT A.* FROM 
	NZ_CLIENTES.SPOT.DIM_OFFER_CYCLE_DH A
INNER JOIN
	NZ_CLIENTES.IC.DIM_CYCLE_DH B
ON
	A.CYCLE_ID = B.CYCLE_ID
WHERE
	B.CAMPAIGN_ID = 96
	AND B.CYCLE_NUMBER = $CICLO
	AND B.CYCLE_ID IN (1219,1220)

--END REGION
;

--REGION CLIENTE OFERTA CICLO FUGADOS Y CAIDOS

--REGION CLIENTE OFERTA CICLO FUGADOS Y CAIDOS
DROP TABLE DESA_CLIENTES.CT.TMP_BASE_CARGA_CUSTOMER_OFFER_CYCLE_TB_M10 IF EXISTS;
CREATE TABLE DESA_CLIENTES.CT.TMP_BASE_CARGA_CUSTOMER_OFFER_CYCLE_TB_M10 AS

SELECT
	*
	--	SELECT MAX(A.LOAD_DATE)
FROM
	DESA_CLIENTES.RU.TMP_STG_OUTPUT_DIGITAL_FILE_CUSTOMER_OFFER_TB_M10 A
WHERE
	A.LOAD_DATE = '2022-07-12 13:20:03'
;	
--END REGION
-- 49973
-- 442641

--REGION FUGADOS
SELECT
	A.CYCLE_ID
	, A.OFFER_ID
	, COUNT(*)
FROM--SELECT * FROM 
	NZ_CLIENTES.IC.FACT_CUSTOMER_OFFER_CYCLE_DH A
WHERE
	CYCLE_ID IN (1219) 
	-->= $CYCLE_ID_FUGADOS--ID_FUGADOS
	
GROUP BY 1,2
;

SELECT
	A.CYCLE_ID
	, COUNT(*)
FROM--SELECT * FROM 
	NZ_CLIENTES.IC.FACT_CUSTOMER_FUGADOS_CAIDOS_CYCLE_DH A
WHERE
	CYCLE_ID IN (1220) 
	--= $CYCLE_ID_CAIDOS
	
GROUP BY 1
;

--REGION GRUPO CONTROL FUGADOS
INSERT INTO NZ_CLIENTES.IC.FACT_CUSTOMER_FUGADOS_CAIDOS_CYCLE_DH
SELECT
	B.CYCLE_ID AS CYCLE_ID
	, A.*
FROM
	(	
	--REGION LAPSER
	SELECT
		DISTINCT
			A.CUSTOMER_ID,
			4 AS ORGANIZATION_ID,
			A.OFFER_ID,
			A.CONTROL,
			A.TARGETING,
			A.SHABIT
		FROM --SELECT * FROM
			DESA_CLIENTES.CT.TMP_TB_APP_M10_TMP_ALLOCATION_FILE_NEW A
		WHERE
			A.TARGETING = 'Lapser'
			--END REGION
	)A	
	CROSS JOIN
	(
			--REGION CYCLE_ID
		SELECT
			CYCLE_ID
		FROM
			NZ_CLIENTES.IC.DIM_CYCLE_DH A
		WHERE
			A.CAMPAIGN_ID = 96
			AND A.CYCLE_NUMBER = $CICLO
			AND A.CYCLE_ID IN(1219) 
			--= $CYCLE_ID_FUGADOS
			AND A.CAMPAIGN_TYPE_ID = 13 --TOTAL BOLETA
		--END REGION
	)B
;
--23242
--END REGION

INSERT INTO NZ_CLIENTES.IC.FACT_CUSTOMER_OFFER_CYCLE_DH 

SELECT
	DISTINCT
	B.CYCLE_ID
	, A.CUSTOMER_ID
	, A.OFFER_ID
	, A.OFFER_RANK
	, A.EAN
FROM
	(
		--REGION CLIENTE OFERTA
		SELECT
			DISTINCT
			13 AS CAMPAIGN_TYPE_ID
			, B.CUSTOMER_ID
			, A.ID_OFERTA AS OFFER_ID
			, A.RANKING_OFERTA AS OFFER_RANK
			, TRIM(A.IMAGEN)::BIGINT AS EAN
		FROM--SELECT * FROM
		   DESA_CLIENTES.CT.TMP_BASE_CARGA_CUSTOMER_OFFER_CYCLE_TB_M10 A
		INNER JOIN
			NZ_CLIENTES.IC.CL_HASH B
		ON
			A.HASH_RUT = B.HASH_STRING
		INNER JOIN
			(
				--REGION OFERTAS ACTIVAS
				SELECT
					DISTINCT OFFER_ID
				FROM
					DESA_CLIENTES.CT.APP_M10_TOTAL_BOLETA_OFERTAS
				WHERE
					CYCLE = $CICLO
				--END REGION
			) C
		ON
			A.ID_OFERTA = C.OFFER_ID
		INNER JOIN
			(
				--REGION GRUPO CONTROL
				SELECT
					DISTINCT FC.CUSTOMER_ID
				FROM
					NZ_CLIENTES.IC.FACT_CUSTOMER_FUGADOS_CAIDOS_CYCLE_DH FC
				WHERE
					FC.CYCLE_ID = $CYCLE_ID_FUGADOS
					AND FC.CONTROL = 'M'
					AND FC.TARGETING = 'Lapser'
				--END REGION
			) D
		ON
			D.CUSTOMER_ID = B.CUSTOMER_ID	
		--END REGION
	) A
INNER JOIN
	(
		--REGION CYCLE OF PER AND PEN CATEGORY
		SELECT
			A.CYCLE_ID
			, A.CAMPAIGN_TYPE_ID
		FROM
			NZ_CLIENTES.IC.DIM_CYCLE_DH A
		WHERE
			A.CAMPAIGN_ID = 96
			AND A.CYCLE_NUMBER = $CICLO
			AND A.CYCLE_ID = $CYCLE_ID_FUGADOS
		--END REGION
	) B
ON
	A.CAMPAIGN_TYPE_ID = B.CAMPAIGN_TYPE_ID
;--22076
--END REGION

--REGION CAIDOS
SELECT
	A.CYCLE_ID
	, A.OFFER_ID
	, COUNT(*)	
FROM--SELECT * FROM
	NZ_CLIENTES.IC.FACT_CUSTOMER_OFFER_CYCLE_DH A
WHERE
	CYCLE_ID = $CYCLE_ID_CAIDOS--ID_CAIDOS
	--CYCLE_ID IN (52,56,60,66,68,72)--PC
	--CYCLE_ID IN (53,57,62,65,73) --MAS  NO VA
	--CYCLE_ID IN (54,58,61,63,74) --TOTALBOLETA  no va	
GROUP BY 1,2
;

SELECT
	A.CYCLE_ID
	, COUNT(*)
FROM--SELECT * FROM
	NZ_CLIENTES.IC.FACT_CUSTOMER_FUGADOS_CAIDOS_CYCLE_DH A
WHERE
	CYCLE_ID = $CYCLE_ID_CAIDOS--ID_CAIDOS
	--CYCLE_ID IN (52,56,60,66,68,72)--PC
	--CYCLE_ID IN (53,57,62,65,73) --MAS  NO VA
	--CYCLE_ID IN (54,58,61,63,74) --TOTALBOLETA  no va	
GROUP BY 1
;

--REGION GRUPO CONTROL CAIDOS
INSERT INTO NZ_CLIENTES.IC.FACT_CUSTOMER_FUGADOS_CAIDOS_CYCLE_DH
SELECT
	B.CYCLE_ID AS CYCLE_ID
	, A.*
FROM
	(	
	SELECT
		DISTINCT
			A.CUSTOMER_ID,
			4 AS ORGANIZATION_ID,
			A.OFFER_ID,
			A.CONTROL,
			A.TARGETING,
			A.SHABIT
		FROM 
			DESA_CLIENTES.CT.TMP_TB_APP_M10_TMP_ALLOCATION_FILE_NEW A
		WHERE
			A.TARGETING = 'Decliner'	
	)A	
	CROSS JOIN
	(
			--REGION CYCLE_ID
		SELECT
			CYCLE_ID
		FROM
			NZ_CLIENTES.IC.DIM_CYCLE_DH A
		WHERE
			A.CAMPAIGN_ID = 96
			AND A.CYCLE_NUMBER = $CICLO
			AND A.CYCLE_ID = $CYCLE_ID_CAIDOS
			AND A.CAMPAIGN_TYPE_ID = 13 --TOTAL BOLETA
		--END REGION
	)B
;
--32341
--END REGION

INSERT INTO NZ_CLIENTES.IC.FACT_CUSTOMER_OFFER_CYCLE_DH 
SELECT
	DISTINCT
	B.CYCLE_ID
	, A.CUSTOMER_ID
	, A.OFFER_ID
	, A.OFFER_RANK
	, A.EAN
FROM
	(
		--REGION CLIENTE OFERTA
		SELECT
			DISTINCT
			13 AS CAMPAIGN_TYPE_ID
			, B.CUSTOMER_ID
			, A.ID_OFERTA AS OFFER_ID
			, A.RANKING_OFERTA AS OFFER_RANK
			, TRIM(A.IMAGEN)::BIGINT AS EAN
		FROM--SELECT * FROM
		   DESA_CLIENTES.CT.TMP_BASE_CARGA_CUSTOMER_OFFER_CYCLE_TB_M10 A
		INNER JOIN
			NZ_CLIENTES.IC.CL_HASH B
		ON
			A.HASH_RUT = B.HASH_STRING
		INNER JOIN
			(
				--REGION OFERTAS ACTIVAS
				SELECT
					DISTINCT OFFER_ID
				FROM
					DESA_CLIENTES.CT.APP_M10_TOTAL_BOLETA_OFERTAS
				WHERE
					CYCLE = $CICLO
				--END REGION
			) C
		ON
			A.ID_OFERTA = C.OFFER_ID
		INNER JOIN
			(
				--REGION GRUPO CONTROL
				SELECT
					DISTINCT FC.CUSTOMER_ID
				FROM
					NZ_CLIENTES.IC.FACT_CUSTOMER_FUGADOS_CAIDOS_CYCLE_DH FC
				WHERE
					FC.CYCLE_ID = $CYCLE_ID_CAIDOS
					AND FC.CONTROL = 'M'
					AND FC.TARGETING = 'Decliner'
				--END REGION
			) D
		ON
			D.CUSTOMER_ID = B.CUSTOMER_ID	
		--END REGION
	) A
INNER JOIN
	(
		--REGION CYCLE OF PER AND PEN CATEGORY
		SELECT
			A.CYCLE_ID
			, A.CAMPAIGN_TYPE_ID
		FROM
			NZ_CLIENTES.IC.DIM_CYCLE_DH A
		WHERE
			A.CAMPAIGN_ID = 96
			AND A.CYCLE_NUMBER = $CICLO
			AND A.CYCLE_ID = $CYCLE_ID_CAIDOS
		--END REGION
	) B
ON
	A.CAMPAIGN_TYPE_ID = B.CAMPAIGN_TYPE_ID
;--30759
--END REGION

--END REGION

--REGION CLIENTE CICLO FUGADOS Y CAIDOS

--REGION FUGADOS
SELECT
	CYCLE_ID
	, COUNT(*)
FROM--select * from
	NZ_CLIENTES.IC.FACT_CUSTOMER_CYCLE_DH
WHERE
	CYCLE_ID = $CYCLE_ID_FUGADOS --FUGADOS 
	--CYCLE_ID IN (52,56,60,66,68)--PC
	--CYCLE_ID IN (53,57,62,65) --MAS 
	--CYCLE_ID IN (54,58,61,63) --TOTALBOLETA  
GROUP BY 1	
;

INSERT INTO NZ_CLIENTES.IC.FACT_CUSTOMER_CYCLE_DH
SELECT
	B.CYCLE_ID
	, A.*
FROM
	(
		--REGION CLIENTES DH
		SELECT DISTINCT
			Y.CUSTOMER_ID
			, NOW()::DATE AS INSERT_DATE
			, 1 AS TARGET_GROUP
			, X.RANKING AS DH_SCORE
		FROM--SELECT * FROM
		    (
				SELECT
					X.*
				FROM 
					DESA_CLIENTES.RU.TMP_STG_OUTPUT_DIGITAL_FILE_CUSTOMER_V2_M10 X
				INNER JOIN
					DESA_CLIENTES.RU.TMP_STG_OUTPUT_DIGITAL_FILE_CUSTOMER_OFFER_TB_M10 A
				ON
					X.HASH_RUT = A.HASH_RUT
				WHERE
					A.LOAD_DATE = '2022-07-12 13:20:03'
			) X 
		INNER JOIN
			NZ_CLIENTES.IC.CL_HASH Y
		ON
			X.HASH_RUT = Y.HASH_STRING
		INNER JOIN
			NZ_CLIENTES.IC.FACT_CUSTOMER_OFFER_CYCLE_DH CO
		ON
			CO.CUSTOMER_ID = Y.CUSTOMER_ID
		AND CO.CYCLE_ID = $CYCLE_ID_FUGADOS	
		--END REGION
	) A
CROSS JOIN
	(
		--REGION CICLOS OP Y PC
		SELECT
			DISTINCT CYCLE_ID
		FROM--SELECT * FROM
			NZ_CLIENTES.IC.DIM_CYCLE_DH 
		WHERE
			CAMPAIGN_ID = 96
			AND CYCLE_ID = $CYCLE_ID_FUGADOS
			AND CYCLE_NUMBER = $CICLO
		--END REGION
	) B
	;
--22076
--END REGION

--REGION CAIDOS
SELECT
	CYCLE_ID
	, COUNT(*)
FROM--select * from
	NZ_CLIENTES.IC.FACT_CUSTOMER_CYCLE_DH
WHERE
	CYCLE_ID = $CYCLE_ID_CAIDOS --CAIDOS 
	--CYCLE_ID IN (52,56,60,66,68)--PC
	--CYCLE_ID IN (53,57,62,65) --MAS 
	--CYCLE_ID IN (54,58,61,63) --TOTALBOLETA  
GROUP BY 1	
;

INSERT INTO NZ_CLIENTES.IC.FACT_CUSTOMER_CYCLE_DH
SELECT
	B.CYCLE_ID
	, A.*
FROM
	(
		--REGION CLIENTES DH
		SELECT DISTINCT
			Y.CUSTOMER_ID
			, NOW()::DATE AS INSERT_DATE
			, 1 AS TARGET_GROUP
			, X.RANKING AS DH_SCORE
		FROM--SELECT * FROM
		    (
				SELECT
					X.*
				FROM 
					DESA_CLIENTES.RU.TMP_STG_OUTPUT_DIGITAL_FILE_CUSTOMER_V2_M10 X
				INNER JOIN
					DESA_CLIENTES.RU.TMP_STG_OUTPUT_DIGITAL_FILE_CUSTOMER_OFFER_TB_M10 A
				ON
					X.HASH_RUT = A.HASH_RUT
				WHERE
					A.LOAD_DATE = '2022-07-12 13:20:03'
			) X 
		INNER JOIN
			NZ_CLIENTES.IC.CL_HASH Y
		ON
			X.HASH_RUT = Y.HASH_STRING
		INNER JOIN
			NZ_CLIENTES.IC.FACT_CUSTOMER_OFFER_CYCLE_DH CO
		ON
			CO.CUSTOMER_ID = Y.CUSTOMER_ID
		AND CO.CYCLE_ID = $CYCLE_ID_CAIDOS	
		--END REGION
	) A
CROSS JOIN
	(
		--REGION CICLOS OP Y PC
		SELECT
			DISTINCT CYCLE_ID
		FROM--SELECT * FROM
			NZ_CLIENTES.IC.DIM_CYCLE_DH 
		WHERE
			CAMPAIGN_ID = 96
			AND CYCLE_ID = $CYCLE_ID_CAIDOS
			AND CYCLE_NUMBER = $CICLO
		--END REGION
	) B
	;--30759
--END REGION

--END REGION

DROP TABLE DESA_CLIENTES.RU.TMP_BASE_CARGA_CUSTOMER_OFFER_CYCLE_TB IF EXISTS;










