--REGION INSERCION DE CAMPAÑAS
SELECT
	*
FROM
	NZ_CLIENTES.IC.DIM_CAMPAIGN_DH A
	--NZ_CLIENTES.IC.DIM_CYCLE_DH
	WHERE UPPER(CAMPAIGN_NAME) LIKE '%M10%'
WHERE
	A.CAMPAIGN_ID = 123
;

INSERT INTO NZ_CLIENTES.IC.DIM_CAMPAIGN_DH
SELECT
	4 AS ORGANIZATION_ID
	, MAX(DCD.CAMPAIGN_ID) + 1 AS CAMPAIGN_ID
	, 'APP M10 PERIODO 9' AS CAMPAIGN_NAME
	, B.FECHA_INICIO_PERIODO::DATE AS START_DATE
	, B.FECHA_FIN_PERIODO::DATE AS END_DATE
	, 'CAMPAÑA APP M10 PERIODO 9' AS DESCRIPTION
	, NOW()::DATE AS LOAD_DATE
	, 'JL' AS LOAD_OWNER
	, 'APP' AS CAMPAIGN_CHANEL
FROM
	NZ_CLIENTES.IC.DIM_CAMPAIGN_DH DCD
CROSS JOIN
	(
		--REGION PERIODO
		SELECT
			DISTINCT A.FECHA_INICIO_PERIODO
			, A.FECHA_FIN_PERIODO
		FROM
			DESA_CLIENTES.RU.APP_M10_OFERTAS A
		WHERE
			A.CYCLE = $CICLO
		--END REGION
	) B
GROUP BY 1,3,4,5,6,7,8
;
--END REGION
;
--123 hasta el 11 de Octubre

--REGION CAMPAING_TYPE AND CAMPAIGN_LVL
SELECT
	*
FROM
	NZ_CLIENTES.IC.DIM_CAMPAIGN_TYPE_DH
;

SELECT
	*
FROM
	NZ_CLIENTES.IC.DIM_CAMPAIGN_LVL_DH
--END REGION
;

--REGION INSERCION DE CICLO
SELECT
	*
FROM--SELECT * FROM
	NZ_CLIENTES.IC.DIM_CYCLE_DH
WHERE	
	CAMPAIGN_ID = 123
	AND CYCLE_ID >= 1216
;

INSERT INTO NZ_CLIENTES.IC.DIM_CYCLE_DH
--REGION OFERTAS PERSONALIZADAS
SELECT
	4 AS ORGANIZATION_ID
	, 123 AS CAMPAIGN_ID
	, 2 AS CAMPAIGN_TYPE_ID
	, MAX(CYCLE_ID) + 1 AS CYCLE_ID
	, B.CYCLE_NUMBER AS CYCLE_NUMBER
	, B.CYCLE_DESCRIPTION AS CYCLE_DESCRIPTION
	, B.START_DATE AS START_DATE
	, B.END_DATE AS END_DATE
	, 5 AS SOURCE_ID
	, NOW()::DATE AS LOAD_DATE
	, 'JL' AS LOAD_OWNER
FROM --SELECT * FROM
	NZ_CLIENTES.IC.DIM_CYCLE_DH A
CROSS JOIN
	(
		--REGION OFERTAS PERSONALIZADAS
		SELECT
			DISTINCT
			'C'||CYCLE|| ' APP PERSONALIZED OFFERS' AS CYCLE_DESCRIPTION
			, CYCLE AS CYCLE_NUMBER
			, A.FECHA_INICIO_CICLO::DATE AS START_DATE
			, A.FECHA_FIN_CICLO::DATE AS END_DATE
		FROM
			DESA_CLIENTES.RU.APP_M10_OFERTAS A
		WHERE
			A.CYCLE = $CICLO
			AND UPPER(A.TIPO_OFERTA) LIKE UPPER('Personalizada%')
		--END REGION
	) B
GROUP BY 1,2,3,5,6,7,8,9
--END REGION
UNION ALL
--REGION PENETRACION CATEGORIA
SELECT
	4 AS ORGANIZATION_ID
	, 123 AS CAMPAIGN_ID
	, 6 AS CAMPAIGN_TYPE_ID
	, MAX(CYCLE_ID) + 2 AS CYCLE_ID
	, B.CYCLE_NUMBER AS CYCLE_NUMBER
	, B.CYCLE_DESCRIPTION AS CYCLE_DESCRIPTION
	, B.START_DATE AS START_DATE
	, B.END_DATE AS END_DATE
	, 5 AS SOURCE_ID
	, NOW()::DATE AS LOAD_DATE
	, 'JL' AS LOAD_OWNER
FROM --SELECT * FROM
	NZ_CLIENTES.IC.DIM_CYCLE_DH A
CROSS JOIN
	(
		--REGION OFERTAS PERSONALIZADAS
		SELECT
			DISTINCT
			'C'||CYCLE|| ' APP CATEGORY PENETRATION' AS CYCLE_DESCRIPTION
			, CYCLE AS CYCLE_NUMBER
			, A.FECHA_INICIO_CICLO::DATE AS START_DATE
			, A.FECHA_FIN_CICLO::DATE AS END_DATE
		FROM
			DESA_CLIENTES.RU.APP_M10_OFERTAS A
		WHERE
			A.CYCLE = $CICLO
			AND UPPER(A.TIPO_OFERTA) LIKE UPPER('Personalizada%')
		--END REGION
	) B
GROUP BY 1,2,3,5,6,7,8,9
--END REGION
UNION ALL
--REGION MASIVA
SELECT
	4 AS ORGANIZATION_ID
	, 123 AS CAMPAIGN_ID
	, 4 AS CAMPAIGN_TYPE_ID
	, MAX(CYCLE_ID) + 3 AS CYCLE_ID
	, B.CYCLE_NUMBER AS CYCLE_NUMBER
	, B.CYCLE_DESCRIPTION AS CYCLE_DESCRIPTION
	, B.START_DATE AS START_DATE
	, B.END_DATE AS END_DATE
	, 5 AS SOURCE_ID
	, NOW()::DATE AS LOAD_DATE
	, 'JL' AS LOAD_OWNER
FROM --SELECT * FROM
	NZ_CLIENTES.IC.DIM_CYCLE_DH A
CROSS JOIN
	(
		--REGION OFERTAS MASIVAS
		SELECT
			DISTINCT
			'C'||CYCLE|| ' APP MASSIVE OFFERS' AS CYCLE_DESCRIPTION
			, CYCLE AS CYCLE_NUMBER
			, A.FECHA_INICIO_CICLO::DATE AS START_DATE
			, A.FECHA_FIN_CICLO::DATE AS END_DATE
		FROM--SELECT * FROM
			DESA_CLIENTES.RU.APP_M10_OFERTAS A
		WHERE
			A.CYCLE = $CICLO
			AND (UPPER(A.TIPO_OFERTA) LIKE UPPER('Masiva%') OR UPPER(A.TIPO_OFERTA) LIKE UPPER('Destaca%'))
		--END REGION
	) B
GROUP BY 1,2,3,5,6,7,8,9
--END REGION
;
--END REGION
;

--REGION SPOT.DIM_OFFER_CYCLE--VALIDAR LO DE LA LISTA_PROD
SELECT
	*
FROM
	NZ_CLIENTES.SPOT.DIM_OFFER_CYCLE_DH
	--ORDER BY CYCLE_ID DESC
WHERE
	CYCLE_ID >= 1216
	--CYCLE_ID IN (116,117,118) --OP 
	--CYCLE_ID IN (52,56,60,66,68,72) --PC
	--CYCLE_ID IN (53,57,62,65,69,73) --MAS 
	--CYCLE_ID IN (54,58,61,63,70,74) --TOTALBOLETA 
;
--ambos son el ciclo que esta pasando
INSERT INTO NZ_CLIENTES.SPOT.DIM_OFFER_CYCLE_DH
--REGION OFERTAS PERSONALIZADAS
SELECT
	B.CYCLE_ID AS CYCLE_ID
	, A.*
FROM
	(
		--REGION OFERTAS
		SELECT
			DISTINCT
			A.OFFER_ID AS OFFER_ID
			, A.OFFER_RANK AS OFFER_RANK
			, A.MAX_UNITS AS MAX_UNITS
			, A.MAX_UNITS AS MAX_UNITS_GEO
			, A.UNIDAD_MEDIDA AS UNIDAD_MEDIDA
			, CASE
				WHEN A.OFFER_ID = 90000 THEN NZ_CLIENTES.ADMIN.REPLACE(NZ_CLIENTES.ADMIN.REPLACE(DCTO,',','.'),'X','')::INTEGER
				WHEN A.DCTO LIKE '%X%' THEN NULL
				WHEN NZ_CLIENTES.ADMIN.REPLACE(NZ_CLIENTES.ADMIN.REPLACE(DCTO,',','.'),'X','')::INTEGER > 100 THEN NZ_CLIENTES.ADMIN.REPLACE(NZ_CLIENTES.ADMIN.REPLACE(DCTO,',','.'),'X','')::INTEGER
				WHEN ROUND(NZ_CLIENTES.ADMIN.REPLACE(NZ_CLIENTES.ADMIN.REPLACE(DCTO,',','.'),'X','')::FLOAT,2)*100::INTEGER < 100 THEN ROUND(NZ_CLIENTES.ADMIN.REPLACE(NZ_CLIENTES.ADMIN.REPLACE(DCTO,',','.'),'X','')::FLOAT,2)*100::INTEGER
				WHEN ROUND(NZ_CLIENTES.ADMIN.REPLACE(NZ_CLIENTES.ADMIN.REPLACE(DCTO,',','.'),'X','')::FLOAT,2)*100::INTEGER > 1 THEN ROUND(NZ_CLIENTES.ADMIN.REPLACE(NZ_CLIENTES.ADMIN.REPLACE(DCTO,',','.'),'X','')::FLOAT,2)*100::INTEGER
				END AS DISCOUNT_PERC
			, 'DIGMAY'||LPAD($Periodo,3, '0')||LPAD($CICLO,3, '0')||LPAD(A.OFFER_ID,5, '0') AS LOYALTY_ID 
			, SQLEXT..REPLACE(ID_PROMOTION, 'IMP_', '')::INT AS DISCOUNT_ID --DCTO REAL
			, ID_PROMOTION AS OFFER_KPI_CODE --------------------------------DCTO REAL
			, NULL AS OFFER_BAR_CODE
			, A.OFFER_DESC AS OFFER_DESC
			, A.OFFER_MAX_USES AS OFFER_MAX_USES
			, A.FECHA_INICIO_CICLO::DATE AS OFFER_START_DATE
			, A.FECHA_INICIO_CICLO::DATE AS OFFER_START_DATE_GEO
			, A.FECHA_FIN_CICLO::DATE AS OFFER_END_DATE
			, A.FECHA_FIN_CICLO::DATE AS OFFER_END_DATE_GEO
			, (CASE WHEN A.OFFER_ID = 90000 THEN 'Oferta válida para miembros del Club Ahorro Mayorista 10, mayores de 18 años, que descarguen la APP Club Ahorro, activen su cupón y lo canjeen en caja, entre el '||A.FECHA_INICIO_CICLO::VARCHAR(50)||' y '||A.FECHA_FIN_CICLO::VARCHAR(50)||', ambas fechas inclusive. El descuento es válido para una sola compra por cliente. Cupón INTRANSFERIBLE. Descuento no acumulable con otras ofertas y/o promociones. Promoción válida sólo para compras con boleta.' 
				ELSE NZ_CLIENTES.ADMIN.REPLACE(NZ_CLIENTES.ADMIN.REPLACE(NZ_CLIENTES.ADMIN.REPLACE(NZ_CLIENTES.ADMIN.REPLACE(NZ_CLIENTES.ADMIN.REPLACE(NZ_CLIENTES.ADMIN.REPLACE(A.OFFER_LEGAL,'{FECHA_INICIO_CICLO}',A.FECHA_INICIO_CICLO::VARCHAR(50)),'{FECHA_FIN_CICLO}',A.FECHA_FIN_CICLO::VARCHAR(50)),'{MAX_UNITS}',A.MAX_UNITS::VARCHAR(1000)),'{UNIDAD_MEDIDA}', A.UNIDAD_LEGAL::VARCHAR(1000)),'{STOCK}',A.OFFER_STOCK::VARCHAR(1000)),'{OFFER_DESC}',A.OFFER_DESC::VARCHAR(1000)) END)::VARCHAR(5000) AS OFFER_LEGAL
			, CASE 
			WHEN 
			A.OFFER_ID <> 90000 AND OFERTA_NUEVA = 'X'
			THEN 
			'APP'||LPAD(A.ORGANIZATION_ID,2,0)||LPAD(A.ID_PERIODO,2,0)||LPAD($cycle_lista_productos,3,0) || A.OFFER_ID 
			WHEN 
			A.OFFER_ID <> 90000 
			THEN 
			'APP'||LPAD(A.ORGANIZATION_ID,2,0)||LPAD(A.ID_PERIODO,2,0)||LPAD($cycle_lista_productos-1,3,0) || A.OFFER_ID 
			END AS OFFER_PRODUCT_LIST
			, 'APP' AS OFFER_PROMOTION_TYPE
			, A.TIPO_FINANCIAMIENTO||' CRM_M10_APP_'||A.CICLO_COMERCIAL||'_'||A.OFFER_ID AS FINANCE_TYPE
			, NULL AS FINANCING_FLAG
			, A.OFFER_STOCK AS OFFER_STOCK
			, 1 AS OFFER_TYPE_ID --PROMO REAL --------------------------<<<<<<<<<<<<<<<<<<<<<  OFFER TYPE ID (TARJETA)
			,CASE
				WHEN A.DCTO LIKE '%X%' THEN A.DCTO END AS CONTENIDO_MECANICA
		FROM--SELECT * FROM
			(
			SELECT 
				OF.* 
				, CASE WHEN OF.UNIDAD_MEDIDA = 'UN' THEN 'unidades' ELSE OF.UNIDAD_MEDIDA END UNIDAD_LEGAL
			FROM--select * FROM
				DESA_CLIENTES.RU.APP_M10_OFERTAS OF
			) A
		INNER JOIN--SELECT * FROM
			DESA_CLIENTES.RU.APP_M10_REL_IDS B
		ON
			A.OFFER_ID = SUBSTR(B.ID_GEOLOYALTY, 13, 5)::INT
			AND A.CYCLE = B.CICLO -----------comentar para total boleta
		WHERE
		--	A.OFFER_ID = 90000
			A.CYCLE = $CICLO
			AND UPPER(A.TIPO_OFERTA) LIKE UPPER('Personalizada%')
		--END REGION
	) A
CROSS JOIN
	(
		--REGION CYCLE_ID
		SELECT
			CYCLE_ID
		FROM
			NZ_CLIENTES.IC.DIM_CYCLE_DH A
		WHERE
			A.CAMPAIGN_ID = 123
			AND A.CYCLE_NUMBER = $CICLO
			AND A.CAMPAIGN_TYPE_ID = 2 --OFERTAS PERSONALIZADAS
		--END REGION
	) B
--END REGION--101
UNION ALL
--REGION PENETRACION CATEGORIA
SELECT
	B.CYCLE_ID AS CYCLE_ID
	, A.*
FROM
	(
		--REGION OFERTAS
		SELECT
			DISTINCT
			A.OFFER_ID AS OFFER_ID
			, A.OFFER_RANK AS OFFER_RANK
			, A.MAX_UNITS AS MAX_UNITS
			, A.MAX_UNITS AS MAX_UNITS_GEO
			, A.UNIDAD_MEDIDA AS UNIDAD_MEDIDA
			, CASE
				WHEN A.OFFER_ID = 90000 THEN NZ_CLIENTES.ADMIN.REPLACE(NZ_CLIENTES.ADMIN.REPLACE(DCTO,',','.'),'X','')::INTEGER
				WHEN A.DCTO LIKE '%X%' THEN NULL
				WHEN NZ_CLIENTES.ADMIN.REPLACE(NZ_CLIENTES.ADMIN.REPLACE(DCTO,',','.'),'X','')::INTEGER > 100 THEN NZ_CLIENTES.ADMIN.REPLACE(NZ_CLIENTES.ADMIN.REPLACE(DCTO,',','.'),'X','')::INTEGER
				WHEN ROUND(NZ_CLIENTES.ADMIN.REPLACE(NZ_CLIENTES.ADMIN.REPLACE(DCTO,',','.'),'X','')::FLOAT,2)*100::INTEGER < 100 THEN ROUND(NZ_CLIENTES.ADMIN.REPLACE(NZ_CLIENTES.ADMIN.REPLACE(DCTO,',','.'),'X','')::FLOAT,2)*100::INTEGER
				WHEN ROUND(NZ_CLIENTES.ADMIN.REPLACE(NZ_CLIENTES.ADMIN.REPLACE(DCTO,',','.'),'X','')::FLOAT,2)*100::INTEGER > 1 THEN ROUND(NZ_CLIENTES.ADMIN.REPLACE(NZ_CLIENTES.ADMIN.REPLACE(DCTO,',','.'),'X','')::FLOAT,2)*100::INTEGER
				END AS DISCOUNT_PERC
			, 'DIGMAY'||LPAD($Periodo,3, '0')||LPAD($CICLO,3, '0')||LPAD(A.OFFER_ID,5, '0') AS LOYALTY_ID 
			, SQLEXT..REPLACE(ID_PROMOTION, 'IMP_', '')::INT AS DISCOUNT_ID --DCTO REAL
			, ID_PROMOTION AS OFFER_KPI_CODE --------------------------------DCTO REAL
			, NULL AS OFFER_BAR_CODE
			, A.OFFER_DESC AS OFFER_DESC
			, A.OFFER_MAX_USES AS OFFER_MAX_USES
			, A.FECHA_INICIO_CICLO::DATE AS OFFER_START_DATE
			, A.FECHA_INICIO_CICLO::DATE AS OFFER_START_DATE_GEO
			, A.FECHA_FIN_CICLO::DATE AS OFFER_END_DATE
			, A.FECHA_FIN_CICLO::DATE AS OFFER_END_DATE_GEO
			, (CASE WHEN A.OFFER_ID = 90000 THEN 'Oferta válida para miembros del Club Ahorro Mayorista 10, mayores de 18 años, que descarguen la APP Club Ahorro, activen su cupón y lo canjeen en caja, entre el '||A.FECHA_INICIO_CICLO::VARCHAR(50)||' y '||A.FECHA_FIN_CICLO::VARCHAR(50)||', ambas fechas inclusive. El descuento es válido para una sola compra por cliente. Cupón INTRANSFERIBLE. Descuento no acumulable con otras ofertas y/o promociones. Promoción válida sólo para compras con boleta.' 
				ELSE NZ_CLIENTES.ADMIN.REPLACE(NZ_CLIENTES.ADMIN.REPLACE(NZ_CLIENTES.ADMIN.REPLACE(NZ_CLIENTES.ADMIN.REPLACE(NZ_CLIENTES.ADMIN.REPLACE(NZ_CLIENTES.ADMIN.REPLACE(A.OFFER_LEGAL,'{FECHA_INICIO_CICLO}',A.FECHA_INICIO_CICLO::VARCHAR(50)),'{FECHA_FIN_CICLO}',A.FECHA_FIN_CICLO::VARCHAR(50)),'{MAX_UNITS}',A.MAX_UNITS::VARCHAR(1000)),'{UNIDAD_MEDIDA}', A.UNIDAD_LEGAL::VARCHAR(1000)),'{STOCK}',A.OFFER_STOCK::VARCHAR(1000)),'{OFFER_DESC}',A.OFFER_DESC::VARCHAR(1000)) END)::VARCHAR(5000) AS OFFER_LEGAL
			, CASE 
			WHEN 
			A.OFFER_ID <> 90000 AND OFERTA_NUEVA = 'X'
			THEN 
			'APP'||LPAD(A.ORGANIZATION_ID,2,0)||LPAD(A.ID_PERIODO,2,0)||LPAD($cycle_lista_productos,3,0) || A.OFFER_ID 
			WHEN 
			A.OFFER_ID <> 90000 
			THEN 
			'APP'||LPAD(A.ORGANIZATION_ID,2,0)||LPAD(A.ID_PERIODO,2,0)||LPAD($cycle_lista_productos-1,3,0) || A.OFFER_ID 
			END AS OFFER_PRODUCT_LIST
			, 'APP' AS OFFER_PROMOTION_TYPE
			, A.TIPO_FINANCIAMIENTO||' CRM_M10_APP_'||A.CICLO_COMERCIAL||'_'||A.OFFER_ID AS FINANCE_TYPE
			, NULL AS FINANCING_FLAG
			, A.OFFER_STOCK AS OFFER_STOCK
			, 1 AS OFFER_TYPE_ID --PROMO REAL --------------------------<<<<<<<<<<<<<<<<<<<<<  OFFER TYPE ID (TARJETA)
			,CASE
				WHEN A.DCTO LIKE '%X%' THEN A.DCTO END AS CONTENIDO_MECANICA
		FROM
			(
			SELECT 
				OF.* 
				, CASE WHEN OF.UNIDAD_MEDIDA = 'UN' THEN 'unidades' ELSE OF.UNIDAD_MEDIDA END UNIDAD_LEGAL
			FROM
				DESA_CLIENTES.RU.APP_M10_OFERTAS OF
			) A
		INNER JOIN--SELECT * FROM
			DESA_CLIENTES.RU.APP_M10_REL_IDS B
		ON
			A.OFFER_ID = SUBSTR(B.ID_GEOLOYALTY, 13, 5)::INT
			AND A.CYCLE = B.CICLO -----------comentar para total boleta
		WHERE
		--	A.OFFER_ID = 90000
			A.CYCLE = $CICLO
			AND UPPER(A.TIPO_OFERTA) LIKE UPPER('Personalizada%')
		--END REGION
	) A
CROSS JOIN
	(
		--REGION CYCLE_ID
		SELECT
			CYCLE_ID
		FROM
			NZ_CLIENTES.IC.DIM_CYCLE_DH A
		WHERE
			A.CAMPAIGN_ID = 123
			AND A.CYCLE_NUMBER = $CICLO
			AND A.CAMPAIGN_TYPE_ID = 6 --PENETRACION CATEGORIA
		--END REGION
	) B
--END REGION--101
UNION ALL
--REGION MASIVAS
SELECT
	B.CYCLE_ID AS CYCLE_ID
	, A.*
FROM
	(
		--REGION OFERTAS
		SELECT
			DISTINCT
			A.OFFER_ID AS OFFER_ID
			, A.OFFER_RANK AS OFFER_RANK
			, A.MAX_UNITS AS MAX_UNITS
			, A.MAX_UNITS AS MAX_UNITS_GEO
			, A.UNIDAD_MEDIDA AS UNIDAD_MEDIDA
			, CASE
				WHEN A.OFFER_ID = 90000 THEN NZ_CLIENTES.ADMIN.REPLACE(NZ_CLIENTES.ADMIN.REPLACE(DCTO,',','.'),'X','')::INTEGER
				WHEN A.DCTO LIKE '%X%' THEN NULL
				WHEN NZ_CLIENTES.ADMIN.REPLACE(NZ_CLIENTES.ADMIN.REPLACE(DCTO,',','.'),'X','')::INTEGER > 100 THEN NZ_CLIENTES.ADMIN.REPLACE(NZ_CLIENTES.ADMIN.REPLACE(DCTO,',','.'),'X','')::INTEGER
				WHEN ROUND(NZ_CLIENTES.ADMIN.REPLACE(NZ_CLIENTES.ADMIN.REPLACE(DCTO,',','.'),'X','')::FLOAT,2)*100::INTEGER < 100 THEN ROUND(NZ_CLIENTES.ADMIN.REPLACE(NZ_CLIENTES.ADMIN.REPLACE(DCTO,',','.'),'X','')::FLOAT,2)*100::INTEGER
				WHEN ROUND(NZ_CLIENTES.ADMIN.REPLACE(NZ_CLIENTES.ADMIN.REPLACE(DCTO,',','.'),'X','')::FLOAT,2)*100::INTEGER > 1 THEN ROUND(NZ_CLIENTES.ADMIN.REPLACE(NZ_CLIENTES.ADMIN.REPLACE(DCTO,',','.'),'X','')::FLOAT,2)*100::INTEGER
				END AS DISCOUNT_PERC
			, 'DIGMAY'||LPAD($Periodo,3, '0')||LPAD($CICLO,3, '0')||LPAD(A.OFFER_ID,5, '0') AS LOYALTY_ID 
			, SQLEXT..REPLACE(ID_PROMOTION, 'IMP_', '')::INT AS DISCOUNT_ID --DCTO REAL
			, ID_PROMOTION AS OFFER_KPI_CODE --------------------------------DCTO REAL
			, NULL AS OFFER_BAR_CODE
			, A.OFFER_DESC AS OFFER_DESC
			, A.OFFER_MAX_USES AS OFFER_MAX_USES
			, A.FECHA_INICIO_CICLO::DATE AS OFFER_START_DATE
			, A.FECHA_INICIO_CICLO::DATE AS OFFER_START_DATE_GEO
			, A.FECHA_FIN_CICLO::DATE AS OFFER_END_DATE
			, A.FECHA_FIN_CICLO::DATE AS OFFER_END_DATE_GEO
			, (CASE WHEN A.OFFER_ID = 90000 THEN 'Oferta válida para miembros del Club Ahorro Mayorista 10, mayores de 18 años, que descarguen la APP Club Ahorro, activen su cupón y lo canjeen en caja, entre el '||A.FECHA_INICIO_CICLO::VARCHAR(50)||' y '||A.FECHA_FIN_CICLO::VARCHAR(50)||', ambas fechas inclusive. El descuento es válido para una sola compra por cliente. Cupón INTRANSFERIBLE. Descuento no acumulable con otras ofertas y/o promociones. Promoción válida sólo para compras con boleta.' 
				ELSE NZ_CLIENTES.ADMIN.REPLACE(NZ_CLIENTES.ADMIN.REPLACE(NZ_CLIENTES.ADMIN.REPLACE(NZ_CLIENTES.ADMIN.REPLACE(NZ_CLIENTES.ADMIN.REPLACE(NZ_CLIENTES.ADMIN.REPLACE(A.OFFER_LEGAL,'{FECHA_INICIO_CICLO}',A.FECHA_INICIO_CICLO::VARCHAR(50)),'{FECHA_FIN_CICLO}',A.FECHA_FIN_CICLO::VARCHAR(50)),'{MAX_UNITS}',A.MAX_UNITS::VARCHAR(1000)),'{UNIDAD_MEDIDA}', A.UNIDAD_LEGAL::VARCHAR(1000)),'{STOCK}',A.OFFER_STOCK::VARCHAR(1000)),'{OFFER_DESC}',A.OFFER_DESC::VARCHAR(1000)) END)::VARCHAR(5000) AS OFFER_LEGAL
			, CASE 
			WHEN 
			A.OFFER_ID <> 90000 AND OFERTA_NUEVA = 'X'
			THEN 
			'APP'||LPAD(A.ORGANIZATION_ID,2,0)||LPAD(A.ID_PERIODO,2,0)||LPAD($cycle_lista_productos,3,0) || A.OFFER_ID 
			WHEN 
			A.OFFER_ID <> 90000 
			THEN 
			'APP'||LPAD(A.ORGANIZATION_ID,2,0)||LPAD(A.ID_PERIODO,2,0)||LPAD($cycle_lista_productos-1,3,0) || A.OFFER_ID 
			END AS OFFER_PRODUCT_LIST
			, 'APP' AS OFFER_PROMOTION_TYPE
			, A.TIPO_FINANCIAMIENTO||' CRM_M10_APP_'||A.CICLO_COMERCIAL||'_'||A.OFFER_ID AS FINANCE_TYPE
			, NULL AS FINANCING_FLAG
			, A.OFFER_STOCK AS OFFER_STOCK
			, 1 AS OFFER_TYPE_ID --PROMO REAL --------------------------<<<<<<<<<<<<<<<<<<<<<  OFFER TYPE ID (TARJETA)
			,CASE
				WHEN A.DCTO LIKE '%X%' THEN A.DCTO END AS CONTENIDO_MECANICA
		FROM--SELECT * FROM
			(
			SELECT 
				OF.* 
				, CASE WHEN OF.UNIDAD_MEDIDA = 'UN' THEN 'unidades' ELSE OF.UNIDAD_MEDIDA END UNIDAD_LEGAL
			FROM
				DESA_CLIENTES.RU.APP_M10_OFERTAS OF
			) A
		INNER JOIN--SELECT * FROM
			DESA_CLIENTES.RU.APP_M10_REL_IDS B
		ON
			A.OFFER_ID = SUBSTR(B.ID_GEOLOYALTY, 13, 5)::INT
			AND A.CYCLE = B.CICLO -----------comentar para total boleta
		WHERE
		--	A.OFFER_ID = 90000
			A.CYCLE = $CICLO
			AND UPPER(A.TIPO_OFERTA) LIKE UPPER('Masiva%')
		--END REGION
	) A
CROSS JOIN
	(
		--REGION CYCLE_ID
		SELECT
			CYCLE_ID
		FROM
			NZ_CLIENTES.IC.DIM_CYCLE_DH A
		WHERE
			A.CAMPAIGN_ID = 123
			AND A.CYCLE_NUMBER = $CICLO
			AND A.CAMPAIGN_TYPE_ID = 4 --MASIVAS
		--END REGION
	) B
--END REGION--14
--END REGION
;

--REGION INSERCION CICLO CENTRO
--INSERT INTO NZ_CLIENTES.IC.FACT_CENTER_CYCLE_DH
SELECT
	A.CYCLE_ID
	, COUNT(*)
FROM--SELECT * FROM
	NZ_CLIENTES.IC.FACT_CENTER_CYCLE_DH A
WHERE
	A.CYCLE_ID >= 1216
GROUP BY 1
;

INSERT INTO NZ_CLIENTES.IC.FACT_CENTER_CYCLE_DH
SELECT
	B.CYCLE_ID
	, A.CENTER_ID
FROM
	(
		--REGION CENTROS M10
		SELECT 
			DISTINCT
			FM.CENTER_ID
		FROM
			NZ_PRODUCCION.BDF.FACT_MONTH_CENTER FM
		INNER JOIN
			NZ_PRODUCCION.BDF.DIM_CENTER DC
		ON
			FM.CENTER_ID = DC.CENTER_ID
			AND DC.ORGANIZATION_ID = 4
		WHERE
			FM.MONTH_ID >= 202207
		--END REGION
	) A
CROSS JOIN
	(
		--REGION CICLOS CAMPAÑA 20
		SELECT
			DISTINCT CYCLE_ID
		FROM
			NZ_CLIENTES.IC.DIM_CYCLE_DH A
		WHERE
			A.CAMPAIGN_ID = 123
			AND A.CYCLE_NUMBER = $CICLO
			AND A.CYCLE_ID >= $CYCLE_ID
		--END REGION
	) B

--END REGION
;


--REGION OFFER_CYCLE
SELECT
	*
FROM
	NZ_CLIENTES.IC.FACT_OFFER_CYCLE_DH A
WHERE
	A.CYCLE_ID >= 1216
;

INSERT INTO NZ_CLIENTES.IC.FACT_OFFER_CYCLE_DH
SELECT
	DISTINCT
	A.CYCLE_ID
	, A.OFFER_ID
	, A.DISCOUNT_ID
	, CASE WHEN A.DISCOUNT_PERC > 100000 THEN A.DISCOUNT_PERC/100 ELSE A.DISCOUNT_PERC END || CASE WHEN A.DISCOUNT_PERC < 100 THEN '% ' ELSE ' ' END || A.OFFER_DESC AS OFFER_DESC
	, A.OFFER_TYPE_ID
	, A.OFFER_MAX_USES
	, CASE WHEN A.DISCOUNT_PERC > 100000 THEN A.DISCOUNT_PERC/100 ELSE A.DISCOUNT_PERC END AS DISCOUNT_PERC
	, A.CONTENIDO_MECANICA
FROM--SELECT A.* FROM 
	NZ_CLIENTES.SPOT.DIM_OFFER_CYCLE_DH A
INNER JOIN
	NZ_CLIENTES.IC.DIM_CYCLE_DH B
ON
	A.CYCLE_ID = B.CYCLE_ID
WHERE
	B.CAMPAIGN_ID = 123
	AND B.CYCLE_NUMBER = $CICLO
	AND B.CYCLE_ID >= $CYCLE_ID

--END REGION
;


--REGION CLIENTE OFERTA CICLO
SELECT
	A.CYCLE_ID
	, A.OFFER_ID
	, COUNT(*)
FROM--SELECT * FROM
	NZ_CLIENTES.IC.FACT_CUSTOMER_OFFER_CYCLE_DH A
WHERE
	CYCLE_ID >=1216--OP 
	--CYCLE_ID IN (52,56,60,66,68,72)--PC
	--CYCLE_ID IN (53,57,62,65,73) --MAS  NO VA
	--CYCLE_ID IN (54,58,61,63,74) --TOTALBOLETA  no va	
GROUP BY 1,2
;

SELECT
	*
FROM
	DESA_CLIENTES.RU.TMP_BASE_CARGA_CUSTOMER_OFFER_CYCLE_M10 A
LIMIT 100
;

DROP TABLE DESA_CLIENTES.RU.TMP_BASE_CARGA_CUSTOMER_OFFER_CYCLE_M10 IF EXISTS;
CREATE TABLE DESA_CLIENTES.RU.TMP_BASE_CARGA_CUSTOMER_OFFER_CYCLE_M10 AS
--REGION CLIENTE OFERTA CICLO
SELECT
	*----SELECT MAX(A.LOAD_DATE)
FROM
	DESA_CLIENTES.RU.TMP_STG_OUTPUT_DIGITAL_FILE_CUSTOMER_OFFER_M10 A
WHERE
	A.LOAD_DATE = '2022-07-12 16:18:35'
	AND (A.NOMBRE_ARCHIVO LIKE '%_2_4.csv' OR A.NOMBRE_ARCHIVO LIKE '%_6_4.csv')
--END REGION
;
--53196032 

INSERT INTO NZ_CLIENTES.IC.FACT_CUSTOMER_OFFER_CYCLE_DH 
SELECT
	DISTINCT
	B.CYCLE_ID
	, A.CUSTOMER_ID
	, A.OFFER_ID
	, A.OFFER_RANK
	, A.EAN
FROM
	(
		--REGION CLIENTE OFERTA
		SELECT
			DISTINCT
			CASE WHEN A.NOMBRE_ARCHIVO LIKE '%_2_4.csv' THEN 2 WHEN A.NOMBRE_ARCHIVO LIKE '%_6_4.csv' THEN 6 END AS CAMPAIGN_TYPE_ID
			, B.CUSTOMER_ID
			, A.ID_OFERTA AS OFFER_ID
			, A.RANKING_OFERTA AS OFFER_RANK
			, TRIM(A.IMAGEN)::BIGINT AS EAN
		FROM--SELECT * FROM--SELECT DISTINCT NOMBRE_ARCHIVO, LOAD_DATE FROM
		   DESA_CLIENTES.RU.TMP_BASE_CARGA_CUSTOMER_OFFER_CYCLE_M10 A
		INNER JOIN
			NZ_CLIENTES.IC.CL_HASH B
		ON
			A.HASH_RUT = B.HASH_STRING
		INNER JOIN
			(
				--REGION OFERTAS ACTIVAS
				SELECT
					DISTINCT OFFER_ID
				FROM
					DESA_CLIENTES.RU.APP_M10_OFERTAS 
				WHERE
					UPPER(TIPO_OFERTA) LIKE UPPER('Personalizada%')
					AND CYCLE = $CICLO
				--END REGION
			) C
		ON
			A.ID_OFERTA = C.OFFER_ID
		WHERE
			(A.NOMBRE_ARCHIVO LIKE '%_2_4.csv' OR A.NOMBRE_ARCHIVO LIKE '%_6_4.csv')
		--END REGION
	) A
INNER JOIN
	(
		--REGION CYCLE OF PER AND PEN CATEGORY
		SELECT
			A.CYCLE_ID
			, A.CAMPAIGN_TYPE_ID
		FROM
			NZ_CLIENTES.IC.DIM_CYCLE_DH A
		WHERE
			A.CAMPAIGN_ID = 123
			AND A.CAMPAIGN_TYPE_ID IN (2,6)
			AND A.CYCLE_ID >= $CYCLE_ID
		--END REGION
	) B
ON
	A.CAMPAIGN_TYPE_ID = B.CAMPAIGN_TYPE_ID
	
	
--END REGION
;

--REGION CLIENTE CICLO
SELECT
	CYCLE_ID
	, COUNT(*)
FROM--select * from
	NZ_CLIENTES.IC.FACT_CUSTOMER_CYCLE_DH
WHERE
	--CYCLE_ID IN (100,101,102) --OP 
	CYCLE_ID >= 1216--PC
	--CYCLE_ID IN (53,57,62,65) --MAS 
	--CYCLE_ID IN (54,58,61,63) --TOTALBOLETA  
GROUP BY 1
	
;
INSERT INTO NZ_CLIENTES.IC.FACT_CUSTOMER_CYCLE_DH
SELECT
	B.CYCLE_ID
	, A.*
FROM
	(
		--REGION CLIENTES DH
		SELECT DISTINCT
			Y.CUSTOMER_ID
			, NOW()::DATE AS INSERT_DATE
			, 1 AS TARGET_GROUP
			, X.RANKING AS DH_SCORE
		FROM
			(
				SELECT 
					DISTINCT A.HASH_RUT
					, A.RANKING
				FROM--SELECT * FROM 
			    	DESA_CLIENTES.RU.TMP_STG_OUTPUT_DIGITAL_FILE_CUSTOMER_M10 A
			) X
		INNER JOIN
			NZ_CLIENTES.IC.CL_HASH Y
		ON
			X.HASH_RUT = Y.HASH_STRING
		
		--END REGION
	) A
CROSS JOIN
	(
		--REGION CICLOS OP Y PC
		SELECT
			DISTINCT CYCLE_ID
		FROM--SELECT * FROM
			NZ_CLIENTES.IC.DIM_CYCLE_DH 
		WHERE
			CAMPAIGN_ID = 123
			AND CAMPAIGN_TYPE_ID IN (2,6)
			AND CYCLE_ID >=$CYCLE_ID
			AND CYCLE_NUMBER = $CICLO
		--END REGION
	) B
--END REGION
;
--9583188 
--VALIDA EL TOTAL DE INSERT X 2
----4791594
/*SELECT
	COUNT(DISTINCT A.CUSTOMER_ID)
FROM
	DESA_CLIENTES.RU.APP_M10_TMP_ALLOCATION_FILE_OP A
;
*/

--REGION OFERTA EAN	
SELECT
	*
FROM
	NZ_CLIENTES.SPOT.DIM_OFFER_CYCLE_SKU_EAN_DH A
WHERE 
	A.CYCLE_ID >= 1216
;

--REGION INSERT SPOT
INSERT INTO NZ_CLIENTES.SPOT.DIM_OFFER_CYCLE_SKU_EAN_DH
SELECT
	DISTINCT
	B.CYCLE_ID
	, B.OFFER_ID
	, A.MATERIAL
	, A.EAN
FROM
	(
		--REGION OFERTA EAN
			SELECT
				DISTINCT
				A.OFFER_ID
				, B.MATERIAL
				, A.EAN
			FROM--SELECT * FROM
				DESA_CLIENTES.RU.APP_M10_OFERTAS_PLU A
			INNER JOIN
				(
					--REGION LINEA POR EAN
					SELECT DISTINCT
						TRIM(P.EAN)::BIGINT AS EAN
						, LTRIM(H.SKU_PRODUCT,'0') AS MATERIAL
				 	FROM
						PROD_AMP_MART.AMP.DIM_PRODUCT P
					INNER JOIN --SELECT * FROM 
				        PROD_AMP_MART.AMP.DIM_SKU_HIERARCHY_H H
				 	ON
				        P.SKU_KEY = H.SKU_KEY
					--END REGION
				) B
			ON
				A.EAN = B.EAN
		--END REGION
	) A
INNER JOIN
	(
		--REGION OFERTA CICLO <<<<<<<<<<<<<< CAMPAÑA 18
		SELECT
			DISTINCT
			A.CYCLE_ID
			, A.OFFER_ID	
		FROM
			NZ_CLIENTES.IC.FACT_OFFER_CYCLE_DH  A
		INNER JOIN
			NZ_CLIENTES.IC.DIM_CYCLE_DH B
		ON
			A.CYCLE_ID = B.CYCLE_ID
		WHERE
			B.CAMPAIGN_ID = 123
			AND B.CYCLE_NUMBER = $CICLO
			AND B.CYCLE_ID >= $CYCLE_ID
		--END REGION
	) B
ON
	A.OFFER_ID = B.OFFER_ID
--END REGION
;--1470

SELECT
	*
FROM
	NZ_CLIENTES.IC.FACT_OFFER_CYCLE_ARTICLE_DH A
WHERE 
	A.CYCLE_ID >= 1216
;


INSERT INTO	NZ_CLIENTES.IC.FACT_OFFER_CYCLE_ARTICLE_DH
--REGION INSERT FACT
SELECT DISTINCT
	DI.ORGANIZATION_ID
	, ART.CYCLE_ID AS CYCLE_ID
	, ART.OFFER_ID
	, DI.ITEM_ARTICLE_ID
FROM--select * from
	NZ_CLIENTES.SPOT.DIM_OFFER_CYCLE_SKU_EAN_DH ART
INNER JOIN
	PROD_AMP_MART.AMP.DIM_PRODUCT_HIERARCHY DPH
ON
	ART.EAN::BIGINT = TRIM(DPH.EAN)
INNER JOIN
	NZ_PRODUCCION.BDF.DIM_ITEM_ARTICLE DI
ON
	LTRIM(DPH.SKU_PRODUCT,'0') = LTRIM(DI.ITEM_ARTICLE_ID_NUM,'0')
	AND DI.ORGANIZATION_ID = 4
INNER JOIN--SELECT DISTINCT DC.CAMPAIGN_ID, DC.CYCLE_ID FROM
	NZ_CLIENTES.IC.DIM_CYCLE_DH DC
ON
	ART.CYCLE_ID = DC.CYCLE_ID
WHERE
	DC.CAMPAIGN_ID = 123
	AND DC.CYCLE_NUMBER = $CICLO
	AND DC.CYCLE_ID >= $CYCLE_ID
--END REGION

--END REGION
;--1452

DROP TABLE DESA_CLIENTES.RC.TMP_BASE_CARGA_CUSTOMER_OFFER_CYCLE_M10 IF EXISTS;
;









