--REGION INSERCION DE CAMPAÑAS
SELECT
	*
FROM
	NZ_CLIENTES.IC.DIM_CAMPAIGN_DH
WHERE
	CAMPAIGN_ID = 109
	
;
INSERT INTO NZ_CLIENTES.IC.DIM_CAMPAIGN_DH
SELECT
	1 AS ORGANIZATION_ID
	, MAX(DCD.CAMPAIGN_ID) + 1 AS CAMPAIGN_ID
	, 'APP PERIODO 11' AS CAMPAIGN_NAME
	, B.FECHA_INICIO_PERIODO::DATE AS START_DATE
	, B.FECHA_FIN_PERIODO::DATE AS END_DATE
	, 'CAMPAÑA APP PERIODO 11' AS DESCRIPTION
	, NOW()::DATE AS LOAD_DATE
	, 'NS' AS LOAD_OWNER
	, 'APP' AS CAMPAIGN_CHANEL
FROM
	NZ_CLIENTES.IC.DIM_CAMPAIGN_DH DCD
CROSS JOIN
	(
		--REGION PERIODO
		SELECT
			DISTINCT A.FECHA_INICIO_PERIODO
			, A.FECHA_FIN_PERIODO
		FROM --SELECT * FROM
			DESA_CLIENTES.RC.APP_OFERTAS A
		WHERE
			A.CYCLE = $CYCLE
		--END REGION
	) B
GROUP BY 1,3,4,5,6,7,8
;
--END REGION
;
--USAR 123 hasta el 11 de OCT
--REGION CAMPAING_TYPE AND CAMPAIGN_LVL
SELECT
	*
FROM
	NZ_CLIENTES.IC.DIM_CAMPAIGN_TYPE_DH
;

SELECT
	*
FROM
	NZ_CLIENTES.IC.DIM_CAMPAIGN_LVL_DH
--END REGION
;

--REGION INSERCION DE CICLO
SELECT
	*
FROM--SELECT MAX(CYCLE_ID) FROM
	NZ_CLIENTES.IC.DIM_CYCLE_DH
WHERE	
	CAMPAIGN_ID = 123
	AND CYCLE_ID >=1221
;
-- debo identificar los op y pc 

--op=1193
--pc=1194

INSERT INTO NZ_CLIENTES.IC.DIM_CYCLE_DH
--REGION OFERTAS PERSONALIZADAS
SELECT
	4 AS ORGANIZATION_ID
	, 123 AS CAMPAIGN_ID
	, 2 AS CAMPAIGN_TYPE_ID -- 2 personalizada
	, MAX(CYCLE_ID) + 1 AS CYCLE_ID
	, B.CYCLE_NUMBER AS CYCLE_NUMBER
	, B.CYCLE_DESCRIPTION AS CYCLE_DESCRIPTION
	, B.START_DATE AS START_DATE
	, B.END_DATE AS END_DATE
	, 5 AS SOURCE_ID
	, NOW()::DATE AS LOAD_DATE
	, 'JL' AS LOAD_OWNER
FROM --SELECT * FROM
	NZ_CLIENTES.IC.DIM_CYCLE_DH A 
CROSS JOIN
	(
		--REGION OFERTAS PERSONALIZADAS
		SELECT
			DISTINCT
			'C'||CYCLE|| ' APP BIRTHDAY PERSONALIZED OFFERS' AS CYCLE_DESCRIPTION
			, CYCLE AS CYCLE_NUMBER
			, A.FECHA_INICIO_CICLO::DATE AS START_DATE
			, A.FECHA_FIN_CICLO::DATE AS END_DATE
		FROM -- select * from 
			DESA_CLIENTES.RU.APP_M10_OFERTAS A
		WHERE
			A.CYCLE = $CICLO
			AND UPPER(A.TIPO_OFERTA) LIKE UPPER('Personalizada%')
			AND A.OFFER_ID IN (SELECT
									DISTINCT OFFER_ID
								FROM 
									DESA_CLIENTES.JL.TMP_ALLOCATION_FILE_BIRTHDAY
								WHERE
									CAMPAIGN_TYPE_ID = 2)
		--END REGION
	) B
GROUP BY 1,2,3,5,6,7,8,9
--END REGION
UNION ALL
--REGION PENETRACION CATEGORIA
SELECT
	4 AS ORGANIZATION_ID
	, 123 AS CAMPAIGN_ID
	, 6 AS CAMPAIGN_TYPE_ID -- 6  (PC)
	, MAX(CYCLE_ID) + 2 AS CYCLE_ID
	, B.CYCLE_NUMBER AS CYCLE_NUMBER
	, B.CYCLE_DESCRIPTION AS CYCLE_DESCRIPTION
	, B.START_DATE AS START_DATE
	, B.END_DATE AS END_DATE
	, 5 AS SOURCE_ID
	, NOW()::DATE AS LOAD_DATE
	, 'JL' AS LOAD_OWNER
FROM --SELECT * FROM
	NZ_CLIENTES.IC.DIM_CYCLE_DH A
CROSS JOIN
	(
		--REGION OFERTAS PERSONALIZADAS
		SELECT
			DISTINCT
			'C'||CYCLE|| ' APP BIRTHDAY CATEGORY PENETRATION' AS CYCLE_DESCRIPTION
			, CYCLE AS CYCLE_NUMBER
			, A.FECHA_INICIO_CICLO::DATE AS START_DATE
			, A.FECHA_FIN_CICLO::DATE AS END_DATE
		FROM
			DESA_CLIENTES.RU.APP_M10_OFERTAS A
		WHERE
			A.CYCLE = $CICLO
			AND UPPER(A.TIPO_OFERTA) LIKE UPPER('Personalizada%')
			AND A.OFFER_ID IN (SELECT
									DISTINCT OFFER_ID
								FROM 
									DESA_CLIENTES.JL.TMP_ALLOCATION_FILE_BIRTHDAY
								WHERE
									CAMPAIGN_TYPE_ID = 6)
		--END REGION
	) B
GROUP BY 1,2,3,5,6,7,8,9
--END REGION
;
--END REGION
;

--REGION SPOT.DIM_OFFER_CYCLE
SELECT
	A.CYCLE_ID,
	COUNT(*)
FROM--select * from
	NZ_CLIENTES.SPOT.DIM_OFFER_CYCLE_DH A
WHERE
	CYCLE_ID IN ('1221','1222')
GROUP BY 1
;

INSERT INTO NZ_CLIENTES.SPOT.DIM_OFFER_CYCLE_DH
--REGION OFERTAS PERSONALIZADAS
SELECT
	B.CYCLE_ID AS CYCLE_ID
	, A.*
FROM
	(
		--REGION OFERTAS
		SELECT
			DISTINCT
			NZ_CLIENTES.ADMIN.REPLACE(A.OFFER_ID,'P','999')::BIGINT AS OFFER_ID
			, A.OFFER_RANK AS OFFER_RANK
			, A.MAX_UNITS::INTEGER AS MAX_UNITS
			, A.MAX_UNITS::INTEGER AS MAX_UNITS_GEO
			, A.UNIDAD_MEDIDA AS UNIDAD_MEDIDA
			, CASE
				WHEN A.OFFER_ID = '90000' THEN NZ_CLIENTES.ADMIN.REPLACE(NZ_CLIENTES.ADMIN.REPLACE(DCTO,',','.'),'X','')::INTEGER
				WHEN ROUND(NZ_CLIENTES.ADMIN.REPLACE(NZ_CLIENTES.ADMIN.REPLACE(DCTO,',','.'),'X','')::FLOAT,2)*100::INTEGER < 100 THEN ROUND(NZ_CLIENTES.ADMIN.REPLACE(NZ_CLIENTES.ADMIN.REPLACE(DCTO,',','.'),'X','')::FLOAT,2)*100::INTEGER
				WHEN ROUND(NZ_CLIENTES.ADMIN.REPLACE(NZ_CLIENTES.ADMIN.REPLACE(DCTO,',','.'),'X','')::FLOAT,2)*100::INTEGER > 100 THEN ROUND(NZ_CLIENTES.ADMIN.REPLACE(NZ_CLIENTES.ADMIN.REPLACE(DCTO,',','.'),'X','')::FLOAT,2)::INTEGER 
				END AS DISCOUNT_PERC
			, 'DIGUNI'||LPAD(A.ID_PERIODO,3, '0')||LPAD($CICLO,3, '0')||LPAD(A.OFFER_ID,5, '0') AS LOYALTY_ID 
			, SQLEXT..REPLACE(SQLEXT..REPLACE(ID_PROMOTION, 'IMP_', ''),',','.')::INT AS DISCOUNT_ID --DCTO REAL
			, ID_PROMOTION AS OFFER_KPI_CODE --------------------------------DCTO REAL
			, NULL AS OFFER_BAR_CODE
			, A.OFFER_DESC AS OFFER_DESC
			, A.OFFER_MAX_USES AS OFFER_MAX_USES
			, A.FECHA_INICIO_CICLO::DATE AS OFFER_START_DATE
			, A.FECHA_INICIO_CICLO::DATE AS OFFER_START_DATE_GEO
			, A.FECHA_FIN_CICLO::DATE AS OFFER_END_DATE
			, A.FECHA_FIN_CICLO::DATE AS OFFER_END_DATE_GEO
			, (CASE WHEN A.OFFER_ID = '90000' THEN 'Oferta válida para miembros del Club Ahorro Unimarc, mayores de 18 años, que descarguen la APP Club Ahorro, activen su cupón y lo canjeen en caja, entre el '||A.FECHA_INICIO_CICLO::VARCHAR(50)||' y '||A.FECHA_FIN_CICLO::VARCHAR(50)||', ambas fechas inclusive. El descuento es válido para una sola compra por cliente. Cupón INTRANSFERIBLE. Descuento no acumulable con otras ofertas y/o promociones. Promoción válida sólo para compras con boleta. Bases legales en www.unimarc.cl.' 
				ELSE NZ_CLIENTES.ADMIN.REPLACE(NZ_CLIENTES.ADMIN.REPLACE(NZ_CLIENTES.ADMIN.REPLACE(NZ_CLIENTES.ADMIN.REPLACE(NZ_CLIENTES.ADMIN.REPLACE(NZ_CLIENTES.ADMIN.REPLACE(A.OFFER_LEGAL,'{FECHA_INICIO_CICLO}',A.FECHA_INICIO_CICLO::VARCHAR(50)),'{FECHA_FIN_CICLO}',A.FECHA_FIN_CICLO::VARCHAR(50)),'{MAX_UNITS}',A.MAX_UNITS::VARCHAR(1000)),'{UNIDAD_MEDIDA}', A.UNIDAD_LEGAL::VARCHAR(1000)),'{STOCK}',A.OFFER_STOCK::VARCHAR(1000)),'{OFFER_DESC}',A.OFFER_DESC::VARCHAR(1000)) END)::VARCHAR(5000) AS OFFER_LEGAL
			, CASE 
				WHEN A.OFFER_ID <> '90000' AND A.OFERTA_NUEVA = 'X' THEN 'APP'||LPAD(A.ORGANIZATION_ID,2,0)||LPAD(A.ID_PERIODO,2,0)||LPAD($CICLO,3,0)||LPAD(A.OFFER_ID,5,0) 
				ELSE 'APP'||LPAD(A.ORGANIZATION_ID,2,0)||LPAD(A.ID_PERIODO,2,0)||LPAD($CICLO-1,3,0)||LPAD(A.OFFER_ID,5,0) 
				END AS OFFER_PRODUCT_LIST
			, 'APP' AS OFFER_PROMOTION_TYPE
			, A.TIPO_FINANCIAMIENTO||' CRM_UNIMARC_APP_'||A.CYCLE||'_'||A.OFFER_ID AS FINANCE_TYPE
			, NULL AS FINANCING_FLAG
			, A.OFFER_STOCK AS OFFER_STOCK
			, 1 AS OFFER_TYPE_ID --PROMO REAL --------------------------<<<<<<<<<<<<<<<<<<<<<  OFFER TYPE ID (TARJETA)
		FROM--SELECT * FROM
			(
			SELECT 
				OF.* 
				, CASE WHEN OF.UNIDAD_MEDIDA = 'UN' THEN 'unidades' ELSE OF.UNIDAD_MEDIDA END UNIDAD_LEGAL
			FROM--SELECT * FROM
				DESA_CLIENTES.RU.APP_M10_OFERTAS OF
			) A
		INNER JOIN--SELECT * FROM
			DESA_CLIENTES.RU.APP_M10_REL_IDS B
		ON
			(A.OFFER_ID = SUBSTR(B.ID_GEOLOYALTY, 15, 3)::VARCHAR(5) 
			or 
			A.OFFER_ID = SUBSTR(B.ID_GEOLOYALTY, 14, 4)::VARCHAR(5))
			AND A.CYCLE = B.CICLO -----------comentar para total boleta
		WHERE
			A.CYCLE = $CICLO
			AND UPPER(A.TIPO_OFERTA) LIKE UPPER('Personalizada%')
			AND A.OFFER_ID IN (SELECT
									DISTINCT OFFER_ID
								FROM 
									DESA_CLIENTES.JL.TMP_ALLOCATION_FILE_BIRTHDAY
								WHERE
									CAMPAIGN_TYPE_ID = 2)
		--END REGION
	) A
CROSS JOIN
	(
		--REGION CYCLE_ID
		SELECT
			CYCLE_ID
		FROM
			NZ_CLIENTES.IC.DIM_CYCLE_DH A
		WHERE
			A.CAMPAIGN_ID = 123
			AND A.CYCLE_NUMBER = $CICLO
			AND A.CAMPAIGN_TYPE_ID = 2 --OFERTAS PERSONALIZADAS
			AND A.CYCLE_ID = $CYCLE_ID_OP
		--END REGION
	) B
--END REGION
UNION ALL
--REGION PENETRACION CATEGORIA
SELECT
	B.CYCLE_ID AS CYCLE_ID
	, A.*
FROM
	(
		--REGION OFERTAS
		SELECT
			DISTINCT
			NZ_CLIENTES.ADMIN.REPLACE(A.OFFER_ID,'P','999')::BIGINT AS OFFER_ID
			, A.OFFER_RANK AS OFFER_RANK
			, A.MAX_UNITS::INTEGER AS MAX_UNITS
			, A.MAX_UNITS::INTEGER AS MAX_UNITS_GEO
			, A.UNIDAD_MEDIDA AS UNIDAD_MEDIDA
			, CASE
				WHEN A.OFFER_ID = '90000' THEN NZ_CLIENTES.ADMIN.REPLACE(NZ_CLIENTES.ADMIN.REPLACE(DCTO,',','.'),'X','')::INTEGER
				WHEN ROUND(NZ_CLIENTES.ADMIN.REPLACE(NZ_CLIENTES.ADMIN.REPLACE(DCTO,',','.'),'X','')::FLOAT,2)*100::INTEGER < 100 THEN ROUND(NZ_CLIENTES.ADMIN.REPLACE(NZ_CLIENTES.ADMIN.REPLACE(DCTO,',','.'),'X','')::FLOAT,2)*100::INTEGER
				WHEN ROUND(NZ_CLIENTES.ADMIN.REPLACE(NZ_CLIENTES.ADMIN.REPLACE(DCTO,',','.'),'X','')::FLOAT,2)*100::INTEGER > 100 THEN ROUND(NZ_CLIENTES.ADMIN.REPLACE(NZ_CLIENTES.ADMIN.REPLACE(DCTO,',','.'),'X','')::FLOAT,2)::INTEGER 
				END AS DISCOUNT_PERC
			, 'DIGUNI'||LPAD(A.ID_PERIODO,3, '0')||LPAD($CICLO,3, '0')||LPAD(A.OFFER_ID,5, '0') AS LOYALTY_ID 
			, SQLEXT..REPLACE(SQLEXT..REPLACE(ID_PROMOTION, 'IMP_', ''),',','.')::INT AS DISCOUNT_ID --DCTO REAL
			, ID_PROMOTION AS OFFER_KPI_CODE --------------------------------DCTO REAL
		--	, SQLEXT..REPLACE(ID_TARJETA, 'IMP_', '')::INT AS DISCOUNT_ID ---------------DCTO TAJRETA
		--	, ID_TARJETA AS OFFER_KPI_CODE ----------------------------------------------DCTO TARJETA
			, NULL AS OFFER_BAR_CODE
			, A.OFFER_DESC AS OFFER_DESC
			, A.OFFER_MAX_USES AS OFFER_MAX_USES
			--OFERTAS REGULARES
			, A.FECHA_INICIO_CICLO::DATE AS OFFER_START_DATE
			, A.FECHA_INICIO_CICLO::DATE AS OFFER_START_DATE_GEO
			, A.FECHA_FIN_CICLO::DATE AS OFFER_END_DATE
			, A.FECHA_FIN_CICLO::DATE AS OFFER_END_DATE_GEO
			--OFERTAS REGULARES FIN
			--TOTAL BOLETA
		--	, 20191218::DATE AS OFFER_START_DATE
		--	, 20191218::DATE AS OFFER_START_DATE_GEO
		--	, 20200107::DATE AS OFFER_END_DATE
		--	, 20200107::DATE AS OFFER_END_DATE_GEO
			----TOTAL BOLETA FINNN
			, (CASE WHEN A.OFFER_ID = '90000' THEN 'Oferta válida para miembros del Club Ahorro Unimarc, mayores de 18 años, que descarguen la APP Club Ahorro, activen su cupón y lo canjeen en caja, entre el '||A.FECHA_INICIO_CICLO::VARCHAR(50)||' y '||A.FECHA_FIN_CICLO::VARCHAR(50)||', ambas fechas inclusive. El descuento es válido para una sola compra por cliente. Cupón INTRANSFERIBLE. Descuento no acumulable con otras ofertas y/o promociones. Promoción válida sólo para compras con boleta. Bases legales en www.unimarc.cl.' 
				ELSE NZ_CLIENTES.ADMIN.REPLACE(NZ_CLIENTES.ADMIN.REPLACE(NZ_CLIENTES.ADMIN.REPLACE(NZ_CLIENTES.ADMIN.REPLACE(NZ_CLIENTES.ADMIN.REPLACE(NZ_CLIENTES.ADMIN.REPLACE(A.OFFER_LEGAL,'{FECHA_INICIO_CICLO}',A.FECHA_INICIO_CICLO::VARCHAR(50)),'{FECHA_FIN_CICLO}',A.FECHA_FIN_CICLO::VARCHAR(50)),'{MAX_UNITS}',A.MAX_UNITS::VARCHAR(1000)),'{UNIDAD_MEDIDA}', A.UNIDAD_LEGAL::VARCHAR(1000)),'{STOCK}',A.OFFER_STOCK::VARCHAR(1000)),'{OFFER_DESC}',A.OFFER_DESC::VARCHAR(1000)) END)::VARCHAR(5000) AS OFFER_LEGAL
			, CASE 
				WHEN A.OFFER_ID <> '90000' AND A.OFERTA_NUEVA = 'X' THEN 'APP'||LPAD(A.ORGANIZATION_ID,2,0)||LPAD(A.ID_PERIODO,2,0)||LPAD($CICLO,3,0)||LPAD(A.OFFER_ID,5,0) 
				ELSE 'APP'||LPAD(A.ORGANIZATION_ID,2,0)||LPAD(A.ID_PERIODO,2,0)||LPAD($CICLO-1,3,0)||LPAD(A.OFFER_ID,5,0) 
				END AS OFFER_PRODUCT_LIST
			, 'APP' AS OFFER_PROMOTION_TYPE
			, A.TIPO_FINANCIAMIENTO||' CRM_UNIMARC_APP_'||A.CYCLE||'_'||A.OFFER_ID AS FINANCE_TYPE
			, NULL AS FINANCING_FLAG
			, A.OFFER_STOCK AS OFFER_STOCK
			, 1 AS OFFER_TYPE_ID --PROMO REAL --------------------------<<<<<<<<<<<<<<<<<<<<<  OFFER TYPE ID (TARJETA)
		FROM--SELECT * FROM
			(
			SELECT 
				OF.* 
				, CASE WHEN OF.UNIDAD_MEDIDA = 'UN' THEN 'unidades' ELSE OF.UNIDAD_MEDIDA END UNIDAD_LEGAL
			FROM
				DESA_CLIENTES.RU.APP_M10_OFERTAS OF
			WHERE OF.OFFER_ID IN (SELECT
									DISTINCT OFFER_ID
								FROM 
									DESA_CLIENTES.JL.TMP_ALLOCATION_FILE_BIRTHDAY
								WHERE
									CAMPAIGN_TYPE_ID = 6)
			) A
		INNER JOIN--SELECT * FROM
			DESA_CLIENTES.RU.APP_M10_REL_IDS B
		ON
			(A.OFFER_ID = SUBSTR(B.ID_GEOLOYALTY, 15, 3)::VARCHAR(5) 
			or 
			A.OFFER_ID = SUBSTR(B.ID_GEOLOYALTY, 14, 4)::VARCHAR(5))
			AND A.CYCLE = B.CICLO -----------comentar para total boleta
		WHERE
		--	A.OFFER_ID = 90000
			A.CYCLE = $CICLO
			AND UPPER(A.TIPO_OFERTA) LIKE UPPER('Personalizada%')
		
		--END REGION
	) A
CROSS JOIN
	(
		--REGION CYCLE_ID
		SELECT
			CYCLE_ID
		FROM
			NZ_CLIENTES.IC.DIM_CYCLE_DH A
		WHERE
			A.CAMPAIGN_ID = 123
			AND A.CYCLE_NUMBER = $CICLO
			AND A.CAMPAIGN_TYPE_ID = 6 --PENETRACION CATEGORIA
			AND A.CYCLE_ID = $CYCLE_ID_PC
		--END REGION
	) B
--END REGION

--END REGION
;

--REGION INSERCION CICLO CENTRO

SELECT
	A.CYCLE_ID
	, COUNT(*)	
FROM--SELECT * FROM
	NZ_CLIENTES.IC.FACT_CENTER_CYCLE_DH A
WHERE
	A.CYCLE_ID  IN ('1221','1222')
GROUP BY 1
;

INSERT INTO NZ_CLIENTES.IC.FACT_CENTER_CYCLE_DH
SELECT
	B.CYCLE_ID
	, A.CENTER_ID
FROM
	(
		--REGION CENTROS M10
		SELECT 
			DISTINCT
			FM.CENTER_ID
		FROM
			NZ_PRODUCCION.BDF.FACT_MONTH_CENTER FM
		INNER JOIN
			NZ_PRODUCCION.BDF.DIM_CENTER DC
		ON
			FM.CENTER_ID = DC.CENTER_ID
			AND DC.ORGANIZATION_ID = 4
		WHERE
			FM.MONTH_ID >= 202207
		--END REGION
	) A
CROSS JOIN
	(
		--REGION CICLOS CAMPAÑA 18
		SELECT
			DISTINCT CYCLE_ID
		FROM
			NZ_CLIENTES.IC.DIM_CYCLE_DH A
		WHERE
			A.CAMPAIGN_ID = 123
			AND A.CYCLE_NUMBER = $CICLO
			AND A.CYCLE_ID >=$CYCLE_ID
		--END REGION
	) B

--END REGION
;


--REGION OFFER_CYCLE
SELECT
	*
FROM
	NZ_CLIENTES.IC.FACT_OFFER_CYCLE_DH A
WHERE
	A.CYCLE_ID IN ('1221','1222')
;

INSERT INTO NZ_CLIENTES.IC.FACT_OFFER_CYCLE_DH
SELECT
	DISTINCT
	A.CYCLE_ID
	, A.OFFER_ID
	, A.DISCOUNT_ID
	, CASE WHEN A.DISCOUNT_PERC > 100000 THEN A.DISCOUNT_PERC/100 ELSE A.DISCOUNT_PERC END || CASE WHEN A.DISCOUNT_PERC < 100 THEN '% ' ELSE ' ' END || A.OFFER_DESC AS OFFER_DESC
	, A.OFFER_TYPE_ID
	, A.OFFER_MAX_USES
	, CASE WHEN A.DISCOUNT_PERC > 100000 THEN A.DISCOUNT_PERC/100 ELSE A.DISCOUNT_PERC END AS DISCOUNT_PERC
FROM--SELECT A.* FROM 
	NZ_CLIENTES.SPOT.DIM_OFFER_CYCLE_DH A
INNER JOIN
	NZ_CLIENTES.IC.DIM_CYCLE_DH B
ON
	A.CYCLE_ID = B.CYCLE_ID
WHERE
	B.CAMPAIGN_ID = 123
	AND B.CYCLE_NUMBER = $CICLO
	AND B.CYCLE_ID >=$CYCLE_ID

--END REGION
;


--REGION CLIENTE OFERTA CICLO
SELECT
	A.CYCLE_ID
	, A.OFFER_ID
	, COUNT(*)	
FROM--SELECT * FROM
	NZ_CLIENTES.IC.FACT_CUSTOMER_OFFER_CYCLE_DH A
WHERE
	CYCLE_ID IN ('1221','1222')
	--CYCLE_ID IN (52,56,60,66,68,72)--PC
	--CYCLE_ID IN (53,57,62,65,73) --MAS  NO VA
	--CYCLE_ID IN (54,58,61,63,74) --TOTALBOLETA  no va	
GROUP BY 1,2
;

--REGION OFERTA PERSONALIZADA
--eSTA WEA ES TEMPORAL, BORRALA NOMAS !!!

DROP TABLE DESA_CLIENTES.JL.TMP_BASE_CARGA_CUSTOMER_OFFER_CYCLE_BD IF EXISTS;
CREATE TABLE DESA_CLIENTES.JL.TMP_BASE_CARGA_CUSTOMER_OFFER_CYCLE_BD AS
--REGION CLIENTE OFERTA CICLO
SELECT
	A.*--SELECT DISTINCT A.LOAD_DATE
FROM--select * from
	DESA_CLIENTES.RU.TMP_STG_OUTPUT_DIGITAL_FILE_CUSTOMER_OFFER_M10 A
INNER JOIN
	NZ_CLIENTES.IC.CL_HASH H
ON
	A.HASH_RUT = H.HASH_STRING
INNER JOIN
	DESA_CLIENTES.JL.TMP_ALLOCATION_FILE_BIRTHDAY B
ON
	H.CUSTOMER_ID = B.CUSTOMER_ID
	AND A.ID_OFERTA = B.OFFER_ID
WHERE
	A.LOAD_DATE = '2022-07-12 16:18:35'
	AND 
	A.IMAGEN_DEFECTO = 'Cumpleanos'
	AND B.CAMPAIGN_TYPE_ID = 2
--END REGION
--op 5923
;

INSERT INTO NZ_CLIENTES.IC.FACT_CUSTOMER_OFFER_CYCLE_DH 
SELECT
	DISTINCT
	B.CYCLE_ID
	, A.CUSTOMER_ID
	, A.OFFER_ID
	, A.OFFER_RANK
	, A.EAN
FROM
	(
		--REGION CLIENTE OFERTA
		SELECT
			DISTINCT
			2 AS CAMPAIGN_TYPE_ID
			, B.CUSTOMER_ID
			, NZ_CLIENTES.ADMIN.REPLACE(A.ID_OFERTA,'P','999')::BIGINT AS OFFER_ID
			, A.RANKING_OFERTA AS OFFER_RANK
			, TRIM(A.IMAGEN)::BIGINT AS EAN
		FROM--SELECT DISTINCT NOMBRE_ARCHIVO, LOAD_DATE FROM
		-- select * from
		   DESA_CLIENTES.JL.TMP_BASE_CARGA_CUSTOMER_OFFER_CYCLE_BD A
		INNER JOIN
			NZ_CLIENTES.IC.CL_HASH B
		ON
			A.HASH_RUT = B.HASH_STRING
		INNER JOIN
			(
				--REGION OFERTAS ACTIVAS
				SELECT
					DISTINCT OFFER_ID
				FROM-- SELECT * FROM 
					DESA_CLIENTES.RU.APP_M10_OFERTAS
				WHERE
					UPPER(TIPO_OFERTA) LIKE UPPER('Personalizada%')
					AND CYCLE = $CICLO
				--END REGION
			) C
		ON
			A.ID_OFERTA = C.OFFER_ID
		--END REGION
	) A
INNER JOIN
	(
		--REGION CYCLE OF PER AND PEN CATEGORY
		SELECT
			A.CYCLE_ID
			, A.CAMPAIGN_TYPE_ID
		FROM
			NZ_CLIENTES.IC.DIM_CYCLE_DH A
		WHERE
			A.CAMPAIGN_ID = 123
			AND A.CAMPAIGN_TYPE_ID = 2
			AND A.CYCLE_NUMBER = $CICLO
			AND A.CYCLE_ID = $CYCLE_ID_OP
		--END REGION
	) B
ON
	A.CAMPAIGN_TYPE_ID = B.CAMPAIGN_TYPE_ID
--END REGION
;--13062

--REGION OFERTA POR CATEGORIA
DROP TABLE DESA_CLIENTES.JL.TMP_BASE_CARGA_CUSTOMER_OFFER_CYCLE_DB IF EXISTS;
CREATE TABLE DESA_CLIENTES.JL.TMP_BASE_CARGA_CUSTOMER_OFFER_CYCLE_DB AS
--REGION CLIENTE OFERTA CICLO
SELECT
	A.*--SELECT DISTINCT A.LOAD_DATE
FROM
	DESA_CLIENTES.RU.TMP_STG_OUTPUT_DIGITAL_FILE_CUSTOMER_OFFER_M10 A
INNER JOIN
	NZ_CLIENTES.IC.CL_HASH H
ON
	A.HASH_RUT = H.HASH_STRING
INNER JOIN
	DESA_CLIENTES.JL.TMP_ALLOCATION_FILE_BIRTHDAY B
ON
	H.CUSTOMER_ID = B.CUSTOMER_ID
	AND A.ID_OFERTA = B.OFFER_ID
WHERE
	A.LOAD_DATE = '2022-07-12 16:18:35'
	AND
	A.IMAGEN_DEFECTO = 'Cumpleanos'
	AND B.CAMPAIGN_TYPE_ID = 6
--END REGION
--pc 1684
;
SELECT * FROM NZ_CLIENTES.IC.FACT_CUSTOMER_OFFER_CYCLE_DH 
WHERE CYCLE_ID = 1221


INSERT INTO NZ_CLIENTES.IC.FACT_CUSTOMER_OFFER_CYCLE_DH 
SELECT
	DISTINCT
	B.CYCLE_ID
	, A.CUSTOMER_ID
	, A.OFFER_ID
	, A.OFFER_RANK
	, A.EAN
FROM
	(
		--REGION CLIENTE OFERTA
		SELECT
			DISTINCT
			6 AS CAMPAIGN_TYPE_ID
			, B.CUSTOMER_ID
			, NZ_CLIENTES.ADMIN.REPLACE(A.ID_OFERTA,'P','999')::BIGINT AS OFFER_ID
			, A.RANKING_OFERTA AS OFFER_RANK
			, TRIM(A.IMAGEN)::BIGINT AS EAN
		FROM--SELECT DISTINCT NOMBRE_ARCHIVO, LOAD_DATE FROM
		   DESA_CLIENTES.JL.TMP_BASE_CARGA_CUSTOMER_OFFER_CYCLE_DB A
		INNER JOIN
			NZ_CLIENTES.IC.CL_HASH B
		ON
			A.HASH_RUT = B.HASH_STRING
		INNER JOIN
			(
				--REGION OFERTAS ACTIVAS
				SELECT
					DISTINCT OFFER_ID
				FROM
					DESA_CLIENTES.RU.APP_M10_OFERTAS
				WHERE
					UPPER(TIPO_OFERTA) LIKE UPPER('Personalizada%')
					AND CYCLE = $CICLO
				--END REGION
			) C
		ON
			A.ID_OFERTA = C.OFFER_ID
		--END REGION
	) A
INNER JOIN
	(
		--REGION CYCLE OF PER AND PEN CATEGORY
		SELECT
			A.CYCLE_ID
			, A.CAMPAIGN_TYPE_ID
		FROM
			NZ_CLIENTES.IC.DIM_CYCLE_DH A
		WHERE
			A.CAMPAIGN_ID = 123
			AND A.CAMPAIGN_TYPE_ID = 6
			AND A.CYCLE_NUMBER = $CICLO
			AND A.CYCLE_ID = $CYCLE_ID_PC
		--END REGION
	) B
ON
	A.CAMPAIGN_TYPE_ID = B.CAMPAIGN_TYPE_ID
--END REGION
;--16105
--END REGION

--REGION CLIENTE CICLO
SELECT
	CYCLE_ID
	, COUNT(*)
FROM--select * from
	NZ_CLIENTES.IC.FACT_CUSTOMER_CYCLE_DH
WHERE
	CYCLE_ID IN ('1221','1222')
	--CYCLE_ID IN (52,56,60,66,68)--PC
	--CYCLE_ID IN (53,57,62,65) --MAS 
	--CYCLE_ID IN (54,58,61,63) --TOTALBOLETA  
GROUP BY 1
;

--REGION CLIENTE OP

--CON ESTA CREO LA TABLA CLIENTES QUE PIDE EL INSERT DE LA FACT CUSTOMER
DROP TABLE DESA_CLIENTES.JL.TMP_STG_OUTPUT_DIGITAL_FILE_CUSTOMER_BD IF EXISTS;
CREATE TABLE DESA_CLIENTES.JL.TMP_STG_OUTPUT_DIGITAL_FILE_CUSTOMER_BD AS 
--REGION CICLO
SELECT 
	B.NOMBRE_ARCHIVO    
	, A.*
FROM
	(
		--REGION CLIENTES
	SELECT DISTINCT
		1 ID_FORMATO
		, NULL AS GEO_CUSTOMER
		, B.HASH_STRING AS HASH_RUT
		, A.PROFILE
		, A.RANKING
	FROM
		(
			--REGION CLIENTES CICLO
			SELECT
				DISTINCT
				CL.CUSTOMER_ID
				, 'P' AS PROFILE
				, COALESCE(CL.CUSTOMER_SCORE, 0) AS RANKING
			FROM--SELECT * FROM	
				(
					--REGION TOTAL CLIENTES
					SELECT
						CUSTOMER_ID
						, CASE 
							WHEN (COUNT_OFFER_ID < 4) THEN 1
							WHEN (COUNT_OFFER_ID = 4) THEN 2
							WHEN (COUNT_OFFER_ID = 5) THEN 3
							WHEN (COUNT_OFFER_ID = 6) THEN 4
							WHEN (COUNT_OFFER_ID > 6) THEN 5
							ELSE 1 END AS CUSTOMER_SCORE
					FROM
						(
						SELECT
							A.CUSTOMER_ID
							, COUNT(DISTINCT A.OFFER_ID) AS COUNT_OFFER_ID
						FROM--SELECT * FROM
							DESA_CLIENTES.RU.APP_M10_TMP_ALLOCATION_FILE_OP A
						GROUP BY 1
						) A
					--END REGION
				) CL
			--END REGION
		) A
	INNER JOIN
		NZ_CLIENTES.IC.CL_HASH B
	ON
		A.CUSTOMER_ID = B.CUSTOMER_ID
	--END REGION
	) A
CROSS JOIN
	(
		--REGION NOMBRE ARCHIVO CLIENTES
		SELECT
			DISTINCT 'CLIENTES_'||TO_CHAR(FECHA_INICIO_CICLO, 'YYMMDD')||'_'||TO_CHAR(FECHA_FIN_CICLO, 'YYMMDD')||'_1.csv' AS NOMBRE_ARCHIVO
		FROM
			DESA_CLIENTES.RU.APP_M10_OFERTAS
		WHERE
			CYCLE = $CICLO_
		--END REGION
	) B

--END REGION
;

INSERT INTO NZ_CLIENTES.IC.FACT_CUSTOMER_CYCLE_DH
SELECT
	B.CYCLE_ID
	, A.*
FROM
	(
		--REGION CLIENTES DH
		SELECT DISTINCT
			Y.CUSTOMER_ID
			, NOW()::DATE AS INSERT_DATE
			, 1 AS TARGET_GROUP
			, X.RANKING AS DH_SCORE
		FROM--SELECT * FROM
		    DESA_CLIENTES.RU.TMP_STG_OUTPUT_DIGITAL_FILE_CUSTOMER X 
		INNER JOIN
			NZ_CLIENTES.IC.CL_HASH Y
		ON
			X.HASH_RUT = Y.HASH_STRING
		INNER JOIN --SELECT * FROM
			DESA_CLIENTES.JL.TMP_ALLOCATION_FILE_BIRTHDAY B
		ON
			Y.CUSTOMER_ID = B.CUSTOMER_ID
		WHERE
			B.CAMPAIGN_TYPE_ID = 2
		--END REGION
	) A
CROSS JOIN
	(
		--REGION CICLOS OP
		SELECT
			DISTINCT CYCLE_ID
		FROM--SELECT * FROM
			NZ_CLIENTES.IC.DIM_CYCLE_DH 
		WHERE
			CAMPAIGN_ID = 123
			AND CAMPAIGN_TYPE_ID = 2
			AND CYCLE_NUMBER = $CICLO
			AND CYCLE_ID = $CYCLE_ID_OP
		--END REGION
	) B
--END REGION
--13062 

--REGION CLIENTE PC

INSERT INTO NZ_CLIENTES.IC.FACT_CUSTOMER_CYCLE_DH
SELECT
	B.CYCLE_ID
	, A.*
FROM
	(
		--REGION CLIENTES DH
		SELECT DISTINCT
			Y.CUSTOMER_ID
			, NOW()::DATE AS INSERT_DATE
			, 1 AS TARGET_GROUP
			, X.RANKING AS DH_SCORE
		FROM--SELECT * FROM
		    DESA_CLIENTES.RU.TMP_STG_OUTPUT_DIGITAL_FILE_CUSTOMER X 
		INNER JOIN
			NZ_CLIENTES.IC.CL_HASH Y
		ON
			X.HASH_RUT = Y.HASH_STRING
		INNER JOIN
			DESA_CLIENTES.JL.TMP_ALLOCATION_FILE_BIRTHDAY B
		ON
			Y.CUSTOMER_ID = B.CUSTOMER_ID
			WHERE
			B.CAMPAIGN_TYPE_ID = 6
		--END REGION
	) A
CROSS JOIN
	(
		--REGION CICLOS PC
		SELECT
			DISTINCT CYCLE_ID
		FROM--SELECT * FROM
			NZ_CLIENTES.IC.DIM_CYCLE_DH 
		WHERE
			CAMPAIGN_ID = 123
			AND CAMPAIGN_TYPE_ID = 6
			AND CYCLE_NUMBER = $CICLO
			AND CYCLE_ID = $CYCLE_ID_PC
		--END REGION
	) B
--END REGION

--END REGION

;

--REGION OFERTA EAN	

SELECT
	*
FROM	
	NZ_CLIENTES.SPOT.DIM_OFFER_CYCLE_SKU_EAN_DH A
WHERE
	A.CYCLE_ID IN ('1221','1222')
;

--REGION INSERT SPOT
INSERT INTO NZ_CLIENTES.SPOT.DIM_OFFER_CYCLE_SKU_EAN_DH
SELECT
	DISTINCT
	B.CYCLE_ID
	, B.OFFER_ID
	, A.MATERIAL
	, A.EAN
FROM
	(
		--REGION OFERTA EAN
			SELECT
				DISTINCT
				NZ_CLIENTES.ADMIN.REPLACE(A.OFFER_ID,'P','999')::BIGINT AS OFFER_ID
				, B.MATERIAL
				, A.EAN
			FROM--SELECT * FROM
				DESA_CLIENTES.RU.APP_M10_OFERTAS_PLU A
			INNER JOIN
				(
					--REGION LINEA POR EAN
					SELECT DISTINCT
						TRIM(P.EAN)::BIGINT AS EAN
						, LTRIM(H.SKU_PRODUCT,'0') AS MATERIAL
				 	FROM
						PROD_AMP_MART.AMP.DIM_PRODUCT P
					INNER JOIN --SELECT * FROM 
				        PROD_AMP_MART.AMP.DIM_SKU_HIERARCHY_H H
				 	ON
				        P.SKU_KEY = H.SKU_KEY
					--END REGION
				) B
			ON
				A.EAN = B.EAN
			WHERE
				A.CYCLE = $CICLO
		--END REGION
	) A
INNER JOIN
	(
		--REGION OFERTA CICLO <<<<<<<<<<<<<< CAMPAÑA 21
		SELECT
			DISTINCT
			A.CYCLE_ID
			, A.OFFER_ID	
		FROM
			NZ_CLIENTES.IC.FACT_OFFER_CYCLE_DH  A
		INNER JOIN
			NZ_CLIENTES.IC.DIM_CYCLE_DH B
		ON
			A.CYCLE_ID = B.CYCLE_ID
		WHERE
			B.CAMPAIGN_ID = 123
			AND B.CYCLE_NUMBER = $CICLO
			AND B.CYCLE_ID >= $CYCLE_ID
		--END REGION
	) B
ON
	A.OFFER_ID = B.OFFER_ID
--END REGION
;--393

SELECT
	*
FROM
	NZ_CLIENTES.IC.FACT_OFFER_CYCLE_ARTICLE_DH A
WHERE
	A.CYCLE_ID IN (1221,1222)
;	

--REGION INSERT FACT
INSERT INTO	NZ_CLIENTES.IC.FACT_OFFER_CYCLE_ARTICLE_DH
SELECT DISTINCT
	DI.ORGANIZATION_ID
	, ART.CYCLE_ID AS CYCLE_ID
	, ART.OFFER_ID
	, DI.ITEM_ARTICLE_ID
FROM--select * from
	NZ_CLIENTES.SPOT.DIM_OFFER_CYCLE_SKU_EAN_DH ART
INNER JOIN
	PROD_AMP_MART.AMP.DIM_PRODUCT_HIERARCHY DPH
ON
	ART.EAN = TRIM(DPH.EAN)
INNER JOIN
	NZ_PRODUCCION.BDF.DIM_ITEM_ARTICLE DI
ON
	LTRIM(DPH.SKU_PRODUCT,'0') = LTRIM(DI.ITEM_ARTICLE_ID_NUM,'0')
	AND DI.ORGANIZATION_ID =1
INNER JOIN
	NZ_CLIENTES.IC.DIM_CYCLE_DH DC
ON
	ART.CYCLE_ID = DC.CYCLE_ID
WHERE
	DC.CAMPAIGN_ID = 123
	AND DC.CYCLE_NUMBER = $CICLO
	AND DC.CYCLE_ID >= $cycle_id
--END REGION

--END REGION
;--391
	
DROP TABLE DESA_CLIENTES.RC.TMP_BASE_CARGA_CUSTOMER_OFFER_CYCLE IF EXISTS;