/***********************************
REVISAR RANKING Y 
OFFER ID DUPLICADOS
************************************/

SELECT
	A.CUSTOMER_ID
	, A.OFFER_ID
	, COUNT(*)
FROM
	DESA_CLIENTES.JL.TMP_MAIPU_APP_ALVI_TMP_ALLOCATION_FILE A--43732583
GROUP BY 1,2
HAVING COUNT > 1
;

/************************************************************/

SELECT
	COUNT(*)
FROM
	DESA_CLIENTES.JL.TMP_MAIPU_APP_ALVI_TMP_ALLOCATION_FILE--470966
;


SELECT
*
FROM--SELECT * FROM
	DESA_CLIENTES.JL.APP_M10_MAIPU_OFERTAS A
WHERE
	A.CYCLE = $CICLO
;--8

SELECT
	COUNT(DISTINCT A.OFFER_ID)
FROM
	DESA_CLIENTES.JL.TMP_MAIPU_APP_ALVI_TMP_ALLOCATION_FILE A--204
INNER JOIN--SELECT * FROM
	DESA_CLIENTES.JL.APP_M10_MAIPU_OFERTAS P--207
ON--37284
	A.OFFER_ID = P.OFFER_ID
WHERE
	P.CYCLE = $CICLO
;--8
